### ISSUE TITLE
Import/convert metadata previously downloaded using the A1111 CivitAI extension

### ISSUE THREAD

**Issue by richardtallent** [mcmonkeyprojects/SwarmUI#101]
### Feature Idea

Coming over from A1111, I already have a number of models downloaded and organized, and I was using the CivitAI extension, so there are already JSON "sidecar" files for each model/embedding, which include critical metadata, such as trigger phrases.

I'm hoping it would be possible to, when said JSON file is detected, have SwarmUI import it *as if* it were downloaded by the new Model Download feature, to whatever degree that is possible.

This would be hugely useful for others who either are moving over from A1111 or who use both with a common library of models. Since the information in both cases comes from CivitAI, I'm hoping the metadata are largely compatible.

**Comment by mcmonkey4eva** [comment]
Swarm does already automatically import civitai metadata.

If you've shown swarm the models, _then_ opened auto to import civit data, _then_ reopened swarm, you'll have to break the metadata cache with this button:
![image](https://github.com/user-attachments/assets/3242317e-49cb-43a5-8c87-f3d59acbf349)

Note you can also request civit metadata be imported from online in the "Edit Metadata" menu on any model if you just give it the relevant civit link
