### ISSUE TITLE
Wildcard enhancements

### ISSUE THREAD

**Issue by efhosci** [mcmonkeyprojects/SwarmUI#105]
### Feature Idea

I'm loving SwarmUI, after moving from A1111 it's been a lot more stable and flexible. One area that I've struggled to adapt to is the current wildcard system, compared to the "Dynamic Prompt" extension available in A1111 there are some things that are not currently possible to do or can only be done in a somewhat clunky way. I'd like to suggest some additions to improve the utility of \<wildcard:\> and \<random:\>, I've provided some examples of how the syntax could work but if you have better ideas then definitely go with those. Apologies if this is a lot at once, while I'd love to help implement some of these my experience with Python is minimal and Git even less:

1. **Weighted selection**: Allow certain elements to be selected with higher probability, for example \<random:3=red|blue|0.5=green\> would select red with 3x the probability of blue and green at half the probability of red, for an approximate 66/22/11% split. I think Python’s random.choices() can do this pretty easily as long as the "weight" can be separated from the "entry".

2. **"Null" option**: allow wildcard entries (as well as possibly those in \<fromto:\>, \<alternate:\>, etc) to be blank or add a "blank" placeholder, such as <random:<blank>|cowboy|top> hat to produce either “hat”, “cowboy hat”, or “top hat”. It’s possible to use a “harmless” character like an underscore to almost do this, but an actual empty selection would be cleaner. It's also somewhat possible using <random[0-1]:> but that always gives a 50% chance for blank.

3. **Negative prompt**: allow part of the entry to be sent to the negative prompt. For example \<random:matthew|mark|luke\<negative:luke skywalker\>|john\<negative:john cena, john madden\>\>. Where the negative part ends up in the prompt may or may not be worth specifying, by default it would make sense to put it at the end but there could be an option like \<negative[front, middle, end]:\> to put it in a general location or \<negative[0.9]:\> to put it at a more specific position based on the word/token/separator count. See [here](https://github.com/acorderob/sd-webui-prompt-postprocessor) for an A1111 extension that does that and some similar things, some of the other tools there may be worth adapting as well.

4. **Wildcards inside other syntax**: Currently there doesn't seem to be a problem using wildcards inside other wildcards, but they don't seem to work inside \<fromto:\>, \<alternate:\>, or other syntax elements, though I haven't tested them all. It seems like they are being interpreted literally in the prompt according to the metadata, for example "\<fromto[0.5]:cowboy|\<random:red|blue\>\> hat" results in that string verbatim in the prompt. It also seems like some prompts such as "\<random:\<random:red|blue\>|\<random:cowboy|top\>\> hat" don't work as they should, resulting in options "\<random:red hat”, “blue\> hat”, “\<random:cowboy hat”, “top\> hat", I think this is due to the separator character being associated with the top-level \<random\> rather than the nested ones. There may be some cases where this feature could cause a problem, such as if the wildcard selection contains a LoRA or preset that conflicts with the initial generation parameters, or creates some sort of infinite loop trying to reference other wildcards/presets that reference itself, but I think if all selections are made prior to starting generation rather than at each step it should be possible to resolve those. With LoRAs, if one is present in the "to" section but not "from", or in one part of the "alternate" options, it could be loaded in those other steps but with weight set to zero. With presets, most generation settings would simply need to be ignored if they are not in the initial "from" section or the first "alternate", or possibly all presets present in any section would be combined as part of the initial generation settings with conflicting settings resolved based on first priority.

5. **Multiple wildcard selection**: Allow multiple wildcards to be selected from based on partial or full name matching. For example \<wildcard:species/*\> would pick an entry from all wildcards in the "species" folder (species/bird, species/lizard, species/shark, etc...). Similarly something like \<wildcard:*ar*\> would select from any wildcard files containing "ar" in the name (species/liz**ar**d, species/sh**ar**k, styles/c**ar**toon, c**ar**s/truck, c**ar**s/sport, etc...). More complicated regex expressions could be nice to implement, but may cause formatting issues and are less likely to be useful. Worth considering is what to do with wildcard files that have different numbers of elements - if wildcard "a" has 100 entries and wildcard "b" has only 3, should it make a 50/50 selection between a and b, then select either 1/100 options from a or 1/3 options from b? Or should it select a with 97% probability or b with 3% on that initial selection (or equivalently, combine all elements of a and b into one list to then pick from)? I don't know what the best answer for that is, I can see both options being "right" in certain situations. I can imagine it would get even harder to deal with for nested wildcards. Whichever method is used, weighted selection would be able to balance the probability in either direction depending on desired behavior.

6. Related and also potentially useful would be a similar “fuzzy search” for individual entries within wildcards, selecting from only matching lines within one/some/all wildcard files. Syntax could be something like \<wildcard:species/*ar*:*s\> to select only lines in species/lizard, species/shark, etc. ending with the letter "s". This could be either based just on the text in the entries themselves, or also based on the text in comments in the file and matching all entries below that comment until the next comment (basically creating subcategories in a wildcard file). This may not be as useful or easy to implement as matching by filename, and as long as wildcards are organized into good subcategories probably not as necessary. It would probably also be more difficult to get the desired behavior, with the potential for a lot of unintentional matches. Again I can forsee possible issues with nested wildcards and other prompt syntax within wildcards, that would probably require filtering out duplicates and incompatible settings.

Thanks for all the work you've done on this fantastic free program, let me know if you need clarification on any of these or more examples.

### Other

Dynamic Prompt extension: https://github.com/adieyal/sd-dynamic-prompts
Prompt postprocessing: https://github.com/acorderob/sd-webui-prompt-postprocessor

**Comment by mcmonkey4eva** [comment]
This is 6(?) entirely separate suggestions that would need 6(?) different responses and 6(?) different commits. Please open 6 separate issues

**Comment by efhosci** [comment]
Sorry about that, will split this into more specific feature requests
