### ISSUE TITLE
Convert from Mask Layer to Image Layer and back

### ISSUE THREAD

**Issue by davidgoering** [mcmonkeyprojects/SwarmUI#11]
When drag and dropping a file into the image editor, it is automatically added as an image layer with no way to convert it to a mask layer. In case of having a previously exported mask image it makes it impossible to use via image editor later on.

**Comment by F85x** [comment]
This would be very helpful! It could also be useful to add the image of an object in PNG format with transparency to superimpose it on the original image, being able to duplicate and convert the image to mask to only apply a little noise to that part.

**Comment by mcmonkey4eva** [comment]
` It could also be useful to add the image of an object in PNG format with transparency to superimpose it on the original image` you can already do that in the image editor, just drag an image in and it gets added as a layer, and you can position it with the General tool

**Comment by F85x** [comment]
> 'It could also be useful to add the image of an object in PNG format with transparency to superimpose it on the original image' you can already do that in the image editor, just drag an image in and it gets added as a layer, and you can position it with the General tool

I really didn't realize that transparency could be used! The layers in the editor are a fantastic feature. Thank you very much and congratulations for the excellent work you do with SwarmUI!!

**Comment by mcmonkey4eva** [comment]
There's now a convert button when you right click the layer
