### ISSUE TITLE
Use prompts from Generate tab while a Comfy Workflow is active

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#111]
### Feature Idea

I'm obviously using Swarm more and more and getting used to the interface vs. A1111/Forge that I was using before. Part of this is to get back up to speed with being able to do everything I used to be able to do in those. However, I use both Swarm's UI and Comfy Workflows in conjunction with each other. I'm finding limitations here and there that necessitates using both together. For example, I can't use ReActor in Swarm alone. In Comfy, I can kind of, sort of, use wildcards but they're awkward and fiddly and that's an understatement.

In Swarm alone (without a Comfy Workflow), I can simply start typing 'wildcard' and it'll autocomplete before I even finish the word. Then I can start typing something and Swarm will suggest a name of a wildcard file and it'll autocomplete that as well. You don't even need to remember the exact name of the wildcard. Awesome!

But I like to use ReActor and that means using Comfy to set that up before handing it over to the Generate tab. So far so good. In fact, who knows what I might want to use in the future that I can only do within Comfy?

Now, I've been wanting to use wildcards with a workflow that includes ReActor and the process for doing this in Comfy is... awkward. You can get it all set up and it might work well enough-ish but once you try to change something inside a wildcard.txt file it necessitates having to completely restart Comfy just to reload the file. If you want to add a new wildcard.txt file, you also have to completely restart Comfy for it to even be recognised. You also have to copy/move all the wildcard files you already have to a whole new directory. I have a ton of these which I've refined over time. An alternate way is to symlink the directories. And... and... and... Like I said: awkward and fiddly.

In order to use wildcards more easily, I've tried deleting (or at least bypassing) the positive prompt nodes in Comfy. My (super hopeful and laughably noobish) thinking is that if there was nothing connected to the positive connector on KSampler, then I could enter my positive prompt in the Generate tab and it would simply magic the two together. It sadly doesn't. I get this understandably-worded error:
```
TypeError: KSamplerAdvanced.sample() missing 1 required positional argument: 'positive'
```
So, I'd like to be able to do this. The benefit would be to be able to have complex Comfy Workflows in the background which I send to Swarm's Generate tab and just be able to switch it up at will by loading up whatever wildcard file I want at any time in the positive prompt box without having to switch to the Comfy tab and edit there. In fact, the hope is that I could then set up workflows which, once perfected, I never really need to touch ever again. If you want to edit or add a new wildcard you can then do that, before hitting the refresh in Swarm to reload everything and the wildcards just... work! It works so well in Swarm alone.

I notice there are a few Swarm-specific nodes I can use in the Comfy tab, one of which being 'SwarmSaveImageWS'. I remember reading somewhere someone said nothing worked for them until they realised they absolutely needed that Swarm node to be able to save anything when they sent the workflow to the Generate tab. I kind of hated Comfy before but I liked the sound of its efficiency. This is why I began using Swarm. Then I wanted to use ReActor so I had to dive into Comfy. So that little 'Import From Generate Tab' was the most useful thing. So, I figured that 'SwarmSaveImageWS' node it placed there was for a very good reason. I'm guessing it somehow hooks from Comfy into Swarm in some way? As you can tell, I'm a superduper programmer who knows all the right terminology. I would never have touched Comfy if it hadn't been for Swarm setting up the initial workflow for me. It's amazing.

So, my feature request is to have a Swarm-specific node you can drop into a workflow that then takes the text inputs in the Generate tab. Maybe some sort of 'SwarmDummyPositiveInput' and 'SwarmDummyNegativeInput'? Then hooking those up keeps KSampler happy but once you send the workflow over to the Generate tab, the positive and negative prompt boxes take over and are required. Maybe changing the greyed-out text to say that any positive and negative prompts are now required inside the Generate tab while those nodes are active in the workflow.

The benefit being that I could then continue to use ReActor but then kind of forget about it and just use the nice, easy Generate tab. Including, all it's nice built-in autocompletion gizmos.

Until I want to use regional prompting, which I have got working, but that's another story...

Unless... I'm missing something super obvious and there's already some way of doing this? If there is, I haven't found it.

Thanks for reading my short novella.

**Comment by mcmonkey4eva** [comment]
`Unless... I'm missing something super obvious and there's already some way of doing this? If there is, I haven't found it.` hahaha yeah, uh, awkward: it's this one.

You can either (A) just let it autodetect if you use common nodes, or (B) make a Primitive node and title it `SwarmUI: Prompt` to autouse the default prompt input, or (C) use a `SwarmInputText` node to make a custom text parameter

In all cases you then just click the big shiny button at the top left:
![image](https://github.com/user-attachments/assets/67e9071b-428c-4d56-870a-4b3e2db79bd6)

**Comment by mcmonkey4eva** [comment]
Comfy in-UI docs similar to Swarm's magic `?` doc buttons are coming soon, and as soon as that's live I'll def mark up all the swarm-comfy-nodes with thorough docs. For now nodes being indecipherable is unfortunately just the norm in comfyland.

This is not a very helpful link, but, the underlying docs for parameter config is currently https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/Text2Image/T2IParamTypes.cs#L55-L94
and prompt view type is https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/Text2Image/T2IParamTypes.cs#L36-L52

more helpful rn is just trying the different view types to see what they do.

----

`Let what autodetect what?`

Load up a basic/default workflow, and hit the _use in generate tab_ button
![image](https://github.com/user-attachments/assets/284e09fd-1897-4f9d-8c52-372d14a3ad82)

And then it automatically detects how to map which parameter where and presents a valid generate tab for that workflow
![image](https://github.com/user-attachments/assets/524de122-1d7d-4b3b-8cdb-60704fa09692)
