### ISSUE TITLE
Automatically remove/replace forward slashes in Model Downloader

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#113]
### Feature Idea

If I go to download a LoRA that contains a forward slash in its name, it will create a new unwanted directory.

Some models have their names reflect what types of checkpoints they'll work on. Even if you're downloading a version for a specific checkpoint, the name might still reflect the other versions.

Example:

```This is a model for SDXL/Pony that you can use```

So you'll end up with:

```models/This is a model for SDXL/Pony that you can use.safetensors```

When the model author has LoRA that works on even more:

```This is a model for SD1.5/SDXL/Pony that you can use```

It can get messy really quickly.

Ideally, I'd like to have a user-configurable option. I'd like to replace that forward slash with a hyphen. This makes the most sense to me as it bunches these types together and doesn't present them as separate words. Then my result would be:

```models/This is a model for SD1.5-SDXL-Pony that you can use.safetensors```

I always double-check when I'm downloading but even then I still miss these forward slashes every now and again.

Thanks.

EDIT: Also: Pipes. Why?! I don't want to see pipes in filenames. OCD! Urgh!

**Comment by mcmonkey4eva** [comment]
Symbols for the most part are stripped now
