### ISSUE TITLE
Autocompletion keywords are returned in a very Swarmy way

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#114]
### Feature Idea

I've been using autocompletions in the Comfy tab via [this node](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) and it's been working great. However, in Swarm's Generate tab, after copying the exact same autocomplete file I was using in the Comfy tab, the autocompletions are listed in a different order.

This might not sound like much of a problem but let me explain it this way:

Imagine I'm building myself a prompt and I have an idea of what I want. Let's say that, as an example, one of the things I want is some sort of machine but I don't yet know what exact keywords I'd like to use. Just 'machine'...something, or something...'machine'.

In the comfy node, anything that matches the word I type is listed, along with the (I assume) popularity number.

![comfy-autocomplete](https://github.com/user-attachments/assets/210c2a49-544c-40b6-978c-1c6cb8849944)

In Swarm's autocomplete, the results are returned without the associated number and in a completely different order.

![swarm-autocomplete](https://github.com/user-attachments/assets/492e84b9-1eaf-4acb-a82b-6d470c0b262c)

Why is this important? Plenty of models I've tested respond better to more popular tags. This is why I've been experimenting with Pony models. I have a higher success rate with models that are trained with more common tags than by letting the checkpoint try to sort itself out with guesswork.

In Comfy, I was using the numbers to help guide me to whichever tags seemed most likely to be understood by the model. 

My feature request is to have the resulting keywords appear either:

1. The keyword with a number to be displayed in the order of highest-lowest number.
2. Have an option to return results in the order in which they appear in the autocompletion file if the file does not contain the numbers.

Regarding the second one, [this file](https://gist.githubusercontent.com/pythongosssss/1d3efa6050356a08cea975183088159a/raw/a18fb2f94f9156cf4476b0c24a09544d6c0baec6/danbooru-tags.txt) is the one I've been using. I'm using the exact same file in the exact same order for both Comfy and Swarm autocomplete but Swarm reorders the results. In the file itself, all tags are already sorted in order of highest number to lowest. If keywords are returned by autocomplete with the highest numbered ones first, then I can make an educated guess as to what I'm likely to have most success with.

Dare I say it: Swarm's keyword matching is a little bit *too* clever for this use case.

It would be icing on the cake if Swarm would also list the corresponding number (as in the Comfy node) so I'm aware of whether or not I'm trying to generate a barely used obscure tag.

Thanks.

**Comment by mcmonkey4eva** [comment]
Oh, that's a unique format I haven't seen before

https://raw.githubusercontent.com/DominikDoom/a1111-sd-webui-tagcomplete/main/tags/danbooru.csv is I think the same data (danbooru tags list) but in a format Swarm _does_ support

I can add support for the other format.

And yes Swarm matching list is sorted by how good of a match it is rather than source order. I can add a user setting to disable the smarter matching logic if you don't like that

**Comment by mcmonkey4eva** [comment]
- Added support for the wonky 2-part csv with a `.txt` extension
- added `Match Mode` user setting to control whether or not startswith/contains get bucketed
- added `Sort Mode` user setting to control how tags are sorted

For what you requested, you'll want:
![image](https://github.com/user-attachments/assets/55f22671-a04f-40f2-82aa-fe72fde93ac8)

or 'Frequency' on sort mode at your own preference
