### ISSUE TITLE
Cannot save AutoCompleteSuffix

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#115]
### Expected Behavior

Edit the text box beside the setting:

User -> User Settings -> AutoCompleteSuffix

I added a comma and a space: ```', '```

There should be a button appear at the bottom to save the setting.

### Actual Behavior

No Save button appears.

You have to toggle some other setting to make the button appear. At which point you will see the text 'Save 2 edited setting(s)?' beside the Save button.

### Steps to Reproduce

As above - easy enough to see my steps.

### Debug Logs

```powershell
Not relevant.
```

**Comment by mcmonkey4eva** [comment]
The bug as described doesn't exist - it works exactly as intended.
What likely confused you was that html only triggers a change event for textboxes once you click out of the textbox, so if you just type and sit there waiting nothing happens. I've changed it to listen to the input event instead, so it responds as soon as you hit any keyboard key
