### ISSUE TITLE
Allow downloading Flux models with Model Downloader

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#118]
### Feature Idea

Entering a .sft file into the Model Downloader should download as with a .safetensors.

However, inputting a valid URL results in this message:
```
URL appears to be a huggingface link, but not a safetensors file. Only safetensors can be auto-downloaded.
```
Which, as mentioned [here](https://github.com/mcmonkeyprojects/SwarmUI/commit/b926e30f211ee495979ba567a1d5353ed579eff2) says that a .sft is a safetensors file by another name. (```treat '.sft' as '.safetensors' equiv```)

**Comment by mcmonkey4eva** [comment]
Should be good now
