### ISSUE TITLE
Flux metadata lists the previously loaded checkpoint

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#119]
### Expected Behavior

When looking at the metadata for previous image generations, the actual checkpoint used for the generation should be listed.

### Actual Behavior

The metadata for images generated with Flux still list the previously loaded checkpoint.

### Steps to Reproduce

After loading the provided [example workflow](https://comfyanonymous.github.io/ComfyUI_examples/flux/) for Schenll and sending it to the Generate tab:
```
User comment	{
  "sui_image_params": {
    "model": "sdxlpony/DucHaiten-Pony-Real - Pony-Real_v10",
    "aspectratio": "Custom",
    "width": 1024,
    "height": 1024,
    "comfyrawworkflowinputtextcliptextencodenodetextg": "a bottle with a rainbow galaxy inside it on top of a wooden table on a table in the middle of a modern kitchen",
    "automaticvae": true,
    "seed": 1332356456,
    "prompt": "",
    "negativeprompt": "",
    "swarm_version": "0.9.1.1",
    "date": "2024-08-02",
    "generation_time": "0.01 (prep) and 17.08 (gen) seconds"
  }
}	
```
When checking all the options on the left, their metadata are listed but it still lists the previous checkpoint.

Examples:

![Screenshot 2024-08-02 at 13-33-42 Image Generation - SwarmUI](https://github.com/user-attachments/assets/0bb3fc11-15ad-4a18-b0fb-aa9634eeb411)

![Screenshot 2024-08-02 at 13-33-57 Image Generation - SwarmUI](https://github.com/user-attachments/assets/422fd230-817a-4dec-b47e-af644e6aed6e)

### Debug Logs

```powershell
Not relevant.
```

**Comment by mcmonkey4eva** [comment]
This isn't a bug, this is a jankily configured custom comfy workflow. You do in fact have a stray pony model loading there, as the comfy workflow isn't taking on the Swarm `model` parameter (normally this automates itself with `CheckpointLoaderSimple` node, but Flux uses the `UNETLoader` node so it doesn't automate atm)

**Comment by mcmonkey4eva** [comment]
`I see. So whatever model I last loaded will always be (apparently) there while I'm using Flux?`
That is not what I said at all?

This is a problem specific to the comfy workflow setup you have, and is fixed by either just not doing the custom workflow, or by linking the swarm model param (Just make a primitive `SwarmUI: Model` and link it to the unetloader input)

**Comment by mcmonkey4eva** [comment]
That looks correct.
I can't diagnose that error without more info.

I just did myself to test:
![image](https://github.com/user-attachments/assets/dd10d1ca-3bd7-48c5-a28a-dd896dfb4efd)

and it works as intended:
![image](https://github.com/user-attachments/assets/444096ae-d793-44e1-8b6a-3de8b09f7b03)

This is on a very clean workflow though, so there might be something more to what's going wrong.
It might be in the swarm interface you have the wrong model selected? It should autoswap to the one in your workflow but sometimes that doesn't happen right

**Comment by mcmonkey4eva** [comment]
make sure your Swarm install is up to date, Flux support was naturally just added yesterday

**Comment by mcmonkey4eva** [comment]
Oh, nope, that was wonked in the code from the Flux update - my bad, fixed.
