### ISSUE TITLE
{prompt} in Segments

### ISSUE THREAD

**Issue by ByblosHex** [mcmonkeyprojects/SwarmUI#121]
### Feature Idea

When using segments in a prompt, if we add a prompt to that segment we have to retype, or copy and paste the entire text of the original prompt. I propose including the {prompt} (excluding segments in the prompt), in the segment prompt. 
**Example:**
 score_9, score_8_up, score_7_up, score_6_up, 1girl, dancing in the moonlight, dynamic pose, full body shot, dynamic angle
 <segment:yolo-face_yolov8n.pt,0.5,0.8>{prompt}, (my favorite fictional character here)

instead of....
 score_9, score_8_up, score_7_up, score_6_up, 1girl, dancing in the moonlight, dynamic pose, full body shot, dynamic angle
 <segment:yolo-face_yolov8n.pt,0.5,0.8>score_9, score_8_up, score_7_up, score_6_up, 1girl, dancing in the moonlight, dynamic pose, full body shot, dynamic angle, (my favorite fictional character here)

**Comment by mcmonkey4eva** [comment]
You can achieve this now with the `var` prompt syntax system, see docs @ https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Prompt%20Syntax.md#variables

eg: `<setvar[prompt]:score_9 score_8 etc ponycrap, prompt text here> maybe some global only prompt here
<segment:ponytail> <var:prompt> etc segment prompt here`
