### ISSUE TITLE
i can't find the "install ip-Adapter" button!

### ISSUE THREAD

**Issue by ali0une** [mcmonkeyprojects/SwarmUI#125]
### Your question

Hi there.

SwarmUI v0.9.1.1 (2024-08-04 05:47:31)
Display Advanced Options is checked.

i've used the install-linux.sh method, it might be obvious and i might be dumb but i've read the [doc about IP-Adapter](https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/IPAdapter-ReVision.md#ip-adapter) and i can't find the "Install IP Adapter" button in the parameter list!

What could be the cause please?

### Other

Also i've nothing in the ReVision Model dropdown menu.

**Comment by ali0une** [comment]
OK ... went on Discord and searched for a while but ... found it!

You have to drag and drop an image **in the text prompt area** then you have a "Install IP Adapter" button **in the ReVision parameter tab**.

**Comment by medoro** [comment]
nothing works
