### ISSUE TITLE
A different fix for cu124 instead of "revert fbgemm back to cu121 to hopefully dodge fbgemm error"

### ISSUE THREAD

**Issue by aoleg** [mcmonkeyprojects/SwarmUI#126]
### Expected Behavior

SwarmUI runs with cu124 without the fbgemm error.

### Actual Behavior

fbgemm error when attempting to run SwarmUI with cu124

### Steps to Reproduce

Update SwarmUI with cu124, run

### Debug Logs

```powershell
n/a
```

### Other

Proper fix for this behavior:
1. Either run ".\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build" once after installation, or
2. Go to comfy's site-packages\torch\lib\ folder and copy: libiomp5md.dll to libomp140.x86_64.dll

This bug (and fix) is described in https://github.com/comfyanonymous/ComfyUI/issues/3703

I tested solution 2), and it worked for me.

**Comment by mcmonkey4eva** [comment]
works for most but not all cases. 121 is stable, and torch nightly i'm told has a fix, so there'll be a fixed main torch release soon
