### ISSUE TITLE
Feature Request - Swarm-API-Backend - Authorization: Bearer

### ISSUE THREAD

**Issue by eedev** [mcmonkeyprojects/SwarmUI#13]
Hello mcmonkey4eva!

I have deployed another Swarm-API-Backend in OVH's Public Cloud, to be able to use the app securely, I would need to use the authentication.

see: https://help.ovhcloud.com/csm/fr-public-cloud-ai-deploy-tokens?id=kb_article_view&sysparm_article=KB0047992

Would you be able to implement authentication methods to Swarm-API-Backend ?

Thank you!

**Comment by mcmonkey4eva** [comment]
Added as a backend setting
