### ISSUE TITLE
Generating multiple images with same settings and different prompts

### ISSUE THREAD

**Issue by nitinmukesh** [mcmonkeyprojects/SwarmUI#131]
### Feature Idea

There should be a way in interface where multiple images can be generated using same settings like CFG, width, height, etc.. but different prompts.

For now you have to wait for an image to finish generation and then change prompt and generate.

### Other

Something similar exists in Auto1111 using X/Y/Z plot script. Not sure about using different prompt using X/Y/Z script.

**Comment by FurkanGozukara** [comment]
already possible with grid of swarmui i use it

actually for last tutorial i used that to generate images :)

last tutorial : https://youtu.be/bupRePUOA18

main tutorial which explains grid : https://youtu.be/HKX8_F1Er_w

**Comment by FurkanGozukara** [comment]
@Taruvi i also noticed that when using grid we cant set number of images right? in swarmui

**Comment by nitinmukesh** [comment]
Thank you. Will try both approach.

**Comment by FurkanGozukara** [comment]
@Taruvi makes sense
