### ISSUE TITLE
Ctrl+Up/Down weight editing bugs out when editing backslash

### ISSUE THREAD

**Issue by AshtakaOOf** [mcmonkeyprojects/SwarmUI#135]
### Expected Behavior

`\(bracket escape\)` turns into `(\(bracket escape\):1.1)` when doing Ctrl+Up

### Actual Behavior

`\(bracket escape\)` turns into `(\(bracket escape\:1.1))` when doing Ctrl+Up

### Steps to Reproduce

Type any text surrounded by parentheses then add backslash to escape them from prompt weighting, then select the text and do Ctrl+Up or Down you will get `(\(bracket escape\:0.9))` instead of `(\(bracket escape\):0.9)`.

### Debug Logs

```powershell
No logs :)
```

### Other

Discord message https://discord.com/channels/1243166023859961988/1243166025000943746/1269932339727958017

**Comment by mcmonkey4eva** [comment]
Don't look at the commit I made to fix this
