### ISSUE TITLE
Linux AMD install is broken

### ISSUE THREAD

**Issue by Ewanbetts** [mcmonkeyprojects/SwarmUI#141]
### Expected Behavior

Run pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0

### Actual Behavior

pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121

### Steps to Reproduce

Try AMD install on linux

### Debug Logs

```powershell
https://github.com/mcmonkeyprojects/SwarmUI/blob/423f3525aeee747340e7285ddc55ffe739d3a6c1/launchtools/comfy-install-linux.sh#L38
```

**Comment by mcmonkey4eva** [comment]
?
