### ISSUE TITLE
about <More GPUs In Your Machine>

### ISSUE THREAD

**Issue by Nuclear6** [mcmonkeyprojects/SwarmUI#143]
I am a comfyui user and am new to multi-GPU. The problem I am encountering now is that when using the AnimateDiff model to generate 48 or more frames of animation, there is a problem of insufficient memory on the 24G GPU. But I have a machine with 4 A10 cards, can this project solve the out of memory problem I have? Is it my understanding that the memory of four A10 cards can be combined and used as one A800 card?

**Comment by mcmonkey4eva** [comment]
`Is it my understanding that the memory of four A10 cards can be combined and used as one A800 card?`
This is unfortunately not the case, you cannot just combine the memory of all cards into one (at least not right now).
Swarm's multi-GPU is dynamic orchestration of large numbers of generations, not spreading one single generation across several GPUs.

**Comment by Nuclear6** [comment]
Got it, thanks for your reply!
