### ISSUE TITLE
loading Flux-merged model in SwarmUI

### ISSUE THREAD

**Issue by cbresciano** [mcmonkeyprojects/SwarmUI#144]
### Your question

Dear mcmonkey,

Thank you for your awesome interfase, I use for SD3 and FluxdevFP8
I'm writing to report an issue I'm having with loading a Flux-merged model in SwarmUI version 0.9.1.1, to have ´dev´ quality with 8 steps only. I'm using ComfyUI master@8115d8c as the backend.

I've followed the instructions for loading custom models in SwarmUI, but I'm encountering difficulties when attempting to load the Flux-merged model. The model is divided into multiple SafeTensor files, and I've placed them in a dedicated directory within the SwarmUI models folder. I've also tried using the index.json file provided with the model to guide the loading process.

I've attached a copy of the diffusion_pytorch_model.safetensors.index.json file for your reference.
https://huggingface.co/sayakpaul/FLUX.1-merged/tree/main/transformer

I've also tried the following troubleshooting steps:

Ensured that I have the latest versions of SwarmUI and ComfyUI.
Verified that all required dependencies are installed.
Checked for any typos in the file paths or configuration settings.
Tried loading other models to rule out any issues with my system.
Unfortunately, I'm still unable to load the Flux-merged model successfully. I would be grateful if you could provide any guidance or assistance.

Thank you for your time and consideration.
Sincerely,
cbresciano
cbrescia@yahoo.com

**Comment by FurkanGozukara** [comment]
there is merged version : https://huggingface.co/drbaph/FLUX.1-schnell-dev-merged

i didnt test yet but hopefully i will and add my tutorial : https://youtu.be/bupRePUOA18

**Comment by mcmonkey4eva** [comment]
You can also make your own merges as described in the Flux section of the Comfy Org blog: https://blog.comfy.org/august-2024-flux-support-new-frontend-for-loops-and-more/
The custom comfy merge is probably better than the HF 50/50 merge

And yeah you need a merged version for any model, HF's normal model splits you can jank into loading but in this case they hypersplit 1 file into 3 for no coherent reason
