### ISSUE TITLE
[Docker] Permanently store custom workflows in the simple tab

### ISSUE THREAD

**Issue by gymnae** [mcmonkeyprojects/SwarmUI#149]
### Expected Behavior

Custom workflows added to the simple tab should survive a rebuild of a docker image / spinning up a new container just like they remain available in ComfyUI tab and how models persist

### Actual Behavior

Every time I rebuild a fresh container from the image, these workflows are gone from the simple tab. They remain accessible in the ComfyUI tab, so they are persisted.

### Steps to Reproduce

1. Create a custom workflow in the ComfyUI tab
2. Use the exposed UI functionality to add it to the simple tab
3. Stop and remove the container
4. Spin up a new container based on the same run / docker-compose command
5. See how they are gone

### Debug Logs

```powershell
----
```

### Other

I'm using the official docker image and created some ComfyUI workflows, which I added to the Simple tab through the functionality exposed in the ComfyUI tab.

**Comment by mcmonkey4eva** [comment]
Haven't tested but should be fixed

**Comment by gymnae** [comment]
Not for me, even after a fresh build.
This is my run command:

```
#!/bin/bash

cd ~/apps/swarmui/gitsrc
git clone https://github.com/mcmonkeyprojects/SwarmUI.git .
git pull

docker build -t swarmui .
docker stop swarmui
docker rm swarmui

# add "--network=host" if you want to access other services on the host network (eg a separated comfy instance)
docker run -it -d \
    --name swarmui \
    --mac-address=<redacted>\
    --privileged \
    --restart always \
    -v /home/ai/apps/swarmui/swarmdata:/Data \
    -v /home/ai/apps/swarmui/swarmbackend:/dlbackend \
    -v /home/ai/apps/swarmui/Models:/Models \
    -v /home/ai/apps/swarmui/Output:/Output \
    --gpus=all -p 7801:7801 swarmui
```
