### ISSUE TITLE
IPEX Support for Intel Arc Cards please

### ISSUE THREAD

**Issue by HyunJae5463** [mcmonkeyprojects/SwarmUI#151]
### Feature Idea

Would be nice to get Ipex support and be able to select it during the install process.

**Comment by mcmonkey4eva** [comment]
ipex should work, though I have no way to test or tell you details here -- https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#intel-gpus

**Comment by HyunJae5463** [comment]
> ipex should work, though I have no way to test or tell you details here -- https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#intel-gpus

Yeah but for tech noobies its kinda hard to make it work. I followed instructions but stuff always broke and didn't work. For A1111 or SD.Next you simply have to use --use-ipex launch command and everything works perfectly.

**Comment by mcmonkey4eva** [comment]
Supposedly you should just install the intel extension driver thingy, and then it'll Just Work :tm: 

Anything past that requires I or any other technically skilled contributor to get our hands on an intel arc card and actually test it.

Until that happens... if you (or anyone else) tries to get it working and finds specific things needed to make it work that Swarm doesn't automatically cover (not counting intel driver install), please do lemme know and I can add handling for it
