### ISSUE TITLE
"Init Image reset to norm" on "Mask Shrink grow"

### ISSUE THREAD

**Issue by F85x** [mcmonkeyprojects/SwarmUI#153]
### Expected Behavior

Using values greater than 0 for "Init Image Reset To Norm" while also activating the "Mask Shrink Grow" option.

### Actual Behavior

When using the "Mask Shrink Grow" option, the mask generated by "Init Image Reset To Norm" becomes misaligned in the image composition.

### Steps to Reproduce

Edit an image, create a mask, activate "Mask Shrink Grow," and set a value greater than 0 for "Init Image Reset To Norm." NOTE: To intentionally visualize the problem, I set "Init Image Creativity" to 0.2 and "Init Image Reset To Norm" to 1.
![Captura de pantalla 2024-08-09 103943](https://github.com/user-attachments/assets/4442414f-2ed8-4f48-975f-f2a2069a965b)

### Debug Logs

```powershell
None
```

**Comment by mcmonkey4eva** [comment]
fixed
