### ISSUE TITLE
SwarmUI vs Comfyui

### ISSUE THREAD

**Issue by wuhaohezi** [mcmonkeyprojects/SwarmUI#158]
### Your question

Can I consider SwarmUI to be functionally at least as good as ComfyUI? Or does ComfyUI offer more support to the community (SwarmUI is slower and less compatible with some features and new plugins compared to ComfyUI)?

**Comment by mcmonkey4eva** [comment]
Swarm is "comfy, and then some". It's an expansion on top of comfy. There's never any reason to use raw comfy without swarm - the worst case scenario with swarm is always just "click into the comfy tab and use raw comfy". See also 'why use swarm' doc https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Why%20Use%20Swarm.md#i-am-a-comfyui-user
