### ISSUE TITLE
Unable to generate TensorRT engine

### ISSUE THREAD

**Issue by Lolagatorade** [mcmonkeyprojects/SwarmUI#16]
errors out after some time on the 1.5% progress

Arch linux (manjaro) , wayland, SD3 and SDXLturbo

![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/42100725/636d5090-959d-49e9-be05-767dede3d846)
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/42100725/f8ddd334-7bce-4c89-a072-aa8835d9aacf)

**Comment by Lolagatorade** [comment]
> errors out after some time on the 1.5% progress
> 
> Arch linux (manjaro) , wayland, SD3 and SDXLturbo
> 
> ![image](https://private-user-images.githubusercontent.com/42100725/341984934-636d5090-959d-49e9-be05-767dede3d846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzUzMzcsIm5iZiI6MTcxOTA3NTAzNywicGF0aCI6Ii80MjEwMDcyNS8zNDE5ODQ5MzQtNjM2ZDUwOTAtOTU5ZC00OWU5LWJlMDUtNzY3ZGVkZTNkODQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OThlMzU4NWZlODcxNDNhNzQxNGIwNzRhZTIwZWMzZjc4MzViMjM2ZTE3ZGNhMWQ3NGEwZDk5YmI2ZjI1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2u1AtrCVWk4O7swr1f_JxjkG-FV49xDlI_0daSejq4Y) ![image](https://private-user-images.githubusercontent.com/42100725/341984954-f8ddd334-7bce-4c89-a072-aa8835d9aacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzUzMzcsIm5iZiI6MTcxOTA3NTAzNywicGF0aCI6Ii80MjEwMDcyNS8zNDE5ODQ5NTQtZjhkZGQzMzQtN2JjZS00Yzg5LWEwNzItYWE4ODM1ZDlhYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OWI5MjFiMTNiNTE2N2FhZDI4OWQ5YWE5MmIzMGU3NDU2ZjU2OGVkZjJiMThjZGM4ZGJhNzMyYjQ4ZGFiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hy_ud7im-xOlQTZAu74bIR3i1dNEBErqDHWWV3Njy9E)

update tested it only on sd3 didnt work. saw documentation doesent soupport turbo models

**Comment by Lolagatorade** [comment]
Additionally it should be mentioned necessary, at least on the GTX 1060 as generating anything is very slow using anything other than the turbo models. When I was using stable cascade, it was very slow and now attempting to use SD3 is also very slow. I'm not sure if there's another accelerator that can be implemented, but that would be very helpful.

**Comment by mcmonkey4eva** [comment]
Should probably redirect the error report to the Comfy TensorRT repo: https://github.com/comfyanonymous/ComfyUI_TensorRT/issues
