### ISSUE TITLE
image region conditioning

### ISSUE THREAD

**Issue by yoinked-h** [mcmonkeyprojects/SwarmUI#162]
### Feature Idea

be able to select regions of the image to apply conditioning
example:
![image](https://github.com/user-attachments/assets/4563b517-469c-415a-844a-656e53100e43)

syntax (idea): <region: x_end, y_end, x_start (optional, default=0), y_start (optional, default=1), strength (optional, default=0.5)>
(numbers expressed as a percentage)

### Other

good luck with arbitrary string parsing

**Comment by mcmonkey4eva** [comment]
This literally already exists lol

**Comment by yoinked-h** [comment]
oh lol
