### ISSUE TITLE
Please consider adding support for GGUF Flux.dev

### ISSUE THREAD

**Issue by cthu1hoo** [mcmonkeyprojects/SwarmUI#165]
### Feature Idea

Basically, this: https://civitai.com/models/647237/flux1-dev-gguf-q4-q5-q8

Q8 seems to be superior in quality to fp8 while having a similar resource usage, which would be great for us on 16GB cards.

Thanks!

**Comment by FurkanGozukara** [comment]
I am waiting to test as well :D

**Comment by aoleg** [comment]
+1, Q8 seems like a good middle ground between FP16 and FP8, being much closer to FP16 quality wise.

**Comment by mcmonkey4eva** [comment]
There's a comfy custom node for it https://github.com/city96/ComfyUI-GGUF

**Comment by mcmonkey4eva** [comment]
Added! relevant docs here  https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#gguf-quantized-models

**Comment by cthu1hoo** [comment]
@mcmonkey4eva thanks, it works great!

**Comment by angelika3377** [comment]
Sorry to barge in but autoinstallation did not work for me, anything I can do? I don't get the popup :(

**Comment by mcmonkey4eva** [comment]
make your own issue post or ask on discord @ https://discord.gg/q2y38cqjNw
