### ISSUE TITLE
Wildcard Variables to callback previous wildcard values

### ISSUE THREAD

**Issue by Targren** [mcmonkeyprojects/SwarmUI#167]
### Feature Idea

When using wildcards in a prompt, users may want to be able to refer to the same value multiple times in the prompt. Dynamic Prompts for A1111 [supports this with its variable syntax](https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#variables)]. 

e.g.  prompts like these (using a hypothetical syntax to assign a variable)

`an idyllic image of an average family outing on a <random:spring,summer,autumn,winter:var_season> afternoon, in a nature park. The family is wearing casual <var:var_season> weekend clothes. The family dog is chasing a ball while it plays with the children. `

or 

`a mature woman born in 1980, looking at viewer, <wildcard:facial_expression:var_expr>, hazel eyes, dark hair, 
, biker tattoos, leather vest, jeans, leaning on a motorcycle
<segment:face>hazel eyes, laugh lines, <var:var_expr>`

 (Not good prompts, just throw-outs to illustrate some use cases)

**Comment by mcmonkey4eva** [comment]
added by https://github.com/mcmonkeyprojects/SwarmUI/pull/242
