### ISSUE TITLE
Regression - Unable to properly connect SwarmInputDropdown node to Upscale Image (using Model)

### ISSUE THREAD

**Issue by Sisimshow** [mcmonkeyprojects/SwarmUI#17]
I wanted to wait until after the move to the new repo to post this. It seems that sometime after you made it so one could connect a dropdown node to the upscale image node to make a dropdown menu to select a ESRGAN model in the Simple tab, it broke sometime after. Now, not even using the reroute node to forcefully connect the two seems to work anymore. I don't consider this a big deal for me personally but I feel it should be reported as an issue. I think reverting to the previous behavior (needing to use the reroute node) would be better if that's what needs to be done. 

![Screenshot 2024-06-22 225730](https://github.com/mcmonkeyprojects/SwarmUI/assets/126213271/285cf7a7-92e7-4514-a4e1-8d6af3acff04)
![Screenshot 2024-06-22 225745](https://github.com/mcmonkeyprojects/SwarmUI/assets/126213271/f03c67b4-ed0c-4d87-991d-06c9b78292f6)
![Screenshot 2024-06-22 225830](https://github.com/mcmonkeyprojects/SwarmUI/assets/126213271/843af49f-7b1f-409d-8fc6-c101ad8c197c)

**Comment by mcmonkey4eva** [comment]
Not a regression, still works as intended - minor workflow mixup per your screenshot, you're missing a node in between:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/fb583916-6bcd-433f-96ee-68e46e1456b2)

**Comment by Sisimshow** [comment]
Well I feel really silly now, sorry! But I think there's still a problem, unless I'm missing something else? I believe I set it up right this time but I'm still running into errors (granted, it does seem to be working in that the dropdown menu works in the simple tab)
![Screenshot 2024-06-24 082041](https://github.com/mcmonkeyprojects/SwarmUI/assets/126213271/196912de-f483-49ae-abd2-9d4586ed3dfb)
![Screenshot 2024-06-24 082117](https://github.com/mcmonkeyprojects/SwarmUI/assets/126213271/0f7d34ec-06a9-443b-a01e-b529164e6945)

**Comment by mcmonkey4eva** [comment]
Okay apparently while the UI was still working, there was indeed a regression in the serverside behavior - I've put the dirty hack code for the serverside part back, but still using the better UI handling that lets you direct connect

**Comment by Sisimshow** [comment]
Gracias :) still doing awesome
