### ISSUE TITLE
[Auto WebUI metadata importer] Separating prompts with line breaks is no longer working

### ISSUE THREAD

**Issue by Ashenai5** [mcmonkeyprojects/SwarmUI#172]
### Expected Behavior

When loading generated images into SwarmUI, it should recognize the entire prompt, treating line breaks as null characters or commas. For example, then prompt for this image...

![XL - DreamShaper XL (v21 Turbo DPM SDE) - 2024 02 21, 15-48-08, 642755 - 754400663](https://github.com/user-attachments/assets/44306621-b2cb-4ded-b14f-72019bec2399)

...is as follows:

Perfect, beautiful, gorgeous, best quality, digital art,
obama and george bush having a water balloon fight

(note the line break after "digital art")

### Actual Behavior

When loading generated images into SwarmUI, it no longer recognizes line breaks as a valid way of separating prompts. For example, for the image above:

![Clipboard Image](https://github.com/user-attachments/assets/84c9c33b-31a9-4ca5-81bb-42cba9e4326a)

It only recognizes the first line of the prompt.

### Steps to Reproduce

Seems to be a problem with any image that has line breaks in its prompts.

### Debug Logs

```powershell
-
```

### Other

The problem appears to be with this commit: https://github.com/mcmonkeyprojects/SwarmUI/commit/f79cf0978c8c613afa861b9bf45622e5a0af3e74

**Comment by mcmonkey4eva** [comment]
This is specifically auto webui images imported, right?

**Comment by mcmonkey4eva** [comment]
Should all be good with new commit. If you find any images that don't work still, please upload examples.

Note the root issue here is auto webui doesn't have any reliable static format (eg Swarm uses JSON), so the parser is just kinda trying its best

**Comment by brendanhoar** [comment]
Yeah, IIRC if you look in the auto source code it...kind of...has to figure out what older versions of it's own code did when creating metadata a lot of the time.
