### ISSUE TITLE
End of generation alert via Slack

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/SwarmUI#18]
Add slack alert functionality to alert when large generations are finished

**Comment by mcmonkey4eva** [comment]
Would be webhooks rather than specific to any service ideally

There is a Queue End Webhook but it's global on/off not easily toggled, while I imagine you only want it for certain large runs?
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/4174cc16-74ee-45b1-b74c-cb3dd59dbfac)

**Comment by rafstahelin** [comment]
> Would be webhooks rather than specific to any service ideally
> 
> 
> 
> There is a Queue End Webhook but it's global on/off not easily toggled, while I imagine you only want it for certain large runs?
> 
> ![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/4174cc16-74ee-45b1-b74c-cb3dd59dbfac)
> 
> 
> 
> 
> 
> Can probably do a new webhook that's a manual one that you can specify in params somewhere when you want to use it, and maybe manual JSON content to let you make it work as a slack/discord/wherever notif if you get reference json to use with it

Yes, that sounds exactly right, json and set in paramus. Ideal

**Comment by mcmonkey4eva** [comment]
There's now a wide range of webhooks and webhook settings, including custom fillable JSON and more, this should hopefully more than cover your needs! See docs @  https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Webhooks.md
