### ISSUE TITLE
Changing the Depth parameter in UI often does not lead to using that value when the 

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#183]
### Expected Behavior

Changing the depth from 3 to 6 should allow the user to potentially request more models/etc. to be sent back to the UI if the directory tree is deeper than 3.

### Actual Behavior

Monitoring the backend of the CS API with added debug statements, I keep seeing "3" being sent on a fresh browser, even though I am change the values.

I then verified this was a front end issue with F12 tools, looking at the outgoing websocket request.

### Steps to Reproduce

Place a model or other object five levels deep from the root.
Install a fresh browser or profile. [The reason to use a fresh browser or profile is that these values used to stick in the browser, and I have on stuck at "20" on Edge, and I cannot reduce it, lol. Incognito mode might work, haven't tested it.]
Start up SwarmUI.
Open SwarmUI url in browser.
Open F12 tools.
Navigate to the tab for that object type.
The default depth will be 3.
Search for the object.
Object is not found.
Set depth to 6.
Either click tab's refresh button or search for the object using the edit field.
Object is still not found.

Using F12 developer tools debugger, examine outgoing request, see that the change in the UI is not sent down to the API. (see attached picture) in the Other section.

### Debug Logs

```powershell
N/A
```

### Other

![image](https://github.com/user-attachments/assets/30a5430b-79cb-4e15-97ba-89fc0213e59c)

And yes, all four of the ListModels requests had "3".

**Comment by mcmonkey4eva** [comment]
fixed by https://github.com/mcmonkeyprojects/SwarmUI/commit/f82d49ff8b0fe42118f3def382d0dd1f66864ce3

Was a misapplied translate code resetting the html elems and losing the change event. Very annoyingly subtle bug (no error messages about it just a thing doesn't run)
