### ISSUE TITLE
Add an "insert at cursor" option for Wildcards

### ISSUE THREAD

**Issue by jwax33** [mcmonkeyprojects/SwarmUI#189]
### Feature Idea

Currently when a Wildcard is clicked to add it to a prompt, it gets added automatically to the end of the prompt.  This behavior is fine for tag and keyword based text interpreters but with the advent of Flux and NLP interpreters, the location and context of the wildcard output becomes much more critical.  Adding a toggle option to allow wildcards to be inserted at the cursor location in the prompt box would eliminate a lot of manual cutting and pasting when formulating Flux prompts using wildcards.

**Comment by mcmonkey4eva** [comment]
wildcards now go to your cursor pos
