### ISSUE TITLE
Inpainting (with mask shrink grow) & segmenting should use the model native resolution (or current resolution settings) IMHO

### ISSUE THREAD

**Issue by CholmesFr** [mcmonkeyprojects/SwarmUI#19]
Hi!
Awesome work with swarmUI.
It's almost perfect for my needs apart for an issue with inpainting and segmenting.

Sometime when using inpainting with **mask shrink grow**, the inpaint is deformed / low quality.
Looking at the generated workflow, it seems that swarm use the current image resolution for the inpaint:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/63900078/de212565-bc11-438e-9dd5-caba939b29f0)

Step to reproduce:
1°) import a big image (or scale an image to a big resolution)
2°) inpaint a small part using the **mask shrink grow** option
3°) import the workflow (great option for debuging btw)
4°) check the size of SwarmImageScaleForMP => it's set to the current image resolution

When working in native resolution (eg 1024x1024 for SDXL) it's not an issue.
However when working with a high resolution image, it's problematic because the inpaint resolution can exceed the range of the model and the memory can explode.

Here an example when trying to inpaint a small part of a big image with a sd1.5 model.
After importing it, if I force the native resolution in the workflow we can see that the inpaint lose quality as the resolution grows.
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/63900078/d76f9473-a8c3-4306-9812-99585b8d9cc8)
(Same seed but Gandy is not recognizable at >1024, the skin is smoother and the glasses frame is deformed)

One solution would be to always use the native resolution in this case: 
WorkflowGenerator.cs line 327 :

string scaledImage = CreateNode("SwarmImageScaleForMP", new JObject()
 {
     ["image"] = new JArray() { croppedImage, 0 },
     ["width"] = UserInput.Get(T2IParamTypes.Model).StandardWidth, // use model native resolution
     ["height"] = UserInput.Get(T2IParamTypes.Model).StandardHeight, 
     ["can_shrink"] = true // Shrink inpaint if mask is too big
 });

It works great but the inpaint is always square (not sure if it's better or not but it should be possible to keep the mask ratio if necessary)

The other solution would be to give the user more control and use the selected resolution in the UI.
I believe some changes in JS part would be necessary as I don't think that these parameters are accessible in the C# function.

Segmenting use the same portion of code but that's great because it suffer the same issue, so both would be fixed.

Let me know what you think and if I should work on a PR.

**Comment by mcmonkey4eva** [comment]
should be fixed now
