### ISSUE TITLE
Add support for gguf quantized T5 encoders

### ISSUE THREAD

**Issue by aoleg** [mcmonkeyprojects/SwarmUI#191]
### Feature Idea

Currently, SwarmUI supports quantized 'unet' models by city96 (https://huggingface.co/city96/FLUX.1-dev-gguf/tree/main). However, city96 also published quantized versions of the T5XXL encoder (https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf)

I downloaded the models, but was unable to make them work with SwarmUI. Please consider adding native support for these, as the T5 encoder is a major VRAM hog.

**Comment by mcmonkey4eva** [comment]
Aight, I suppose it's finally time to add a textenc selector param

Under Advanced->Advanced Model Addons, allows selecting GGUF models and will automatically swap to the gguf loader nodes for them
![image](https://github.com/user-attachments/assets/7ea46a9a-4630-4066-88a2-36d31a9c45ef)

Only applies at all when using 'unet' folder format models, which the current gguf flux models all are
