### ISSUE TITLE
Pass comfyui commannd prompt data to swarmui command prompt 

### ISSUE THREAD

**Issue by rugabunda** [mcmonkeyprojects/SwarmUI#193]
### Feature Idea

The only reason I sometimes do not use SwarmUI is so I can actually see the messages from comyui such as the iterations per second for benchmarking purposes, and the installation and updating of nodes and the like. I

s there any way to include an option to pass this data to the swarmui commandline window?

**Comment by mcmonkey4eva** [comment]
just change LogLevel to Debug in Server Configuration

**Comment by rugabunda** [comment]
Brilliant, Tx!
