### ISSUE TITLE
Using a no baked model without Clip,T5 and VAE in SwarmUI

### ISSUE THREAD

**Issue by cbresciano** [mcmonkeyprojects/SwarmUI#194]
### Your question

"All available backends failed to load model" is the message I receive when I try to use Flux-Dev-Kijai11Gb FP8 without Clip_L, T5FP8 and ae VAE, despite I set up it in the add ons options in the swarmUI interface and it also appears in the model´s list. Running backend: StabilityMatrix ComfyUI Self-Start. Must the Kijai model be put in a special place?. Other than Stablediffusion/Flux with the other baked models which work fine there? Using ComfyUI I must use LoadDiffusionModel because Kijai is only a model, not a checkpoint, the SwarmUI tab with a ComfyUI workflow only has an example for loading a checkpoint to generate images. Besides simple models there are more and more Flux1 GGUFs and bnbNF4 also. How to use a simple model in SwarmUI?

**Comment by mcmonkey4eva** [comment]
Those models go in the `(Swarm)/Models/unet` folder
