### ISSUE TITLE
Native Implementation of Automatic CFG

### ISSUE THREAD

**Issue by TheForgotten69** [mcmonkeyprojects/SwarmUI#195]
## Background

Automatic CFG can sometimes produce significantly better results with minimal configuration. However, as it stands, the only convenient way to utilize Automatic CFG is by importing it from the generate tab and adding it as a node there. This method, while functional, is suboptimal due to the limitations it imposes, such as missing configuration options when switching back to the generate tab.

# Feature Request

To improve usability and effectiveness, I propose implementing Automatic CFG natively, similar to how the GGUF loader is integrated. This would allow for better configuration and a more seamless workflow, avoiding the current limitations.

**Comment by mcmonkey4eva** [comment]
Use whatnow exactly?

**Comment by TheForgotten69** [comment]
Basically this: https://github.com/Extraltodeus/ComfyUI-AutomaticCFG

**Comment by dsp6414** [comment]
I am also troubled by the cfg parameter, which is not set correctly and often generates blurry images

**Comment by Quaggles** [comment]
@TheForgotten69 I've implemented a SwarmUI extension that adds SkimmedCFG to the generate tab, it looks like the successor to the AutomaticCFG node and the readme suggests moving to SkimmedCFG, does this do what you want? https://github.com/Quaggles/SwarmUI-SkimmedCFG

**Comment by dsp6414** [comment]
已收到！

**Comment by TheForgotten69** [comment]
oh nice thanks a ton for working on this @Quaggles ! Tbh I never used the skimmedCFG method but that seem like an interesting project. I'll edit my comment once tested :)
