### ISSUE TITLE
'cancel this gen' button (like it exists in comfy)

### ISSUE THREAD

**Issue by snottyone** [mcmonkeyprojects/SwarmUI#197]
### Feature Idea

when generating X pics or gen forever, it would be SO nice to have a readily accessible button that cancels just the current generation. ('interrupt and generate' no-go for 'forever' variant, and not accessible anyway)

**Comment by mcmonkey4eva** [comment]
duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/4
