### ISSUE TITLE
GGUF compatibility in default Generate tab

### ISSUE THREAD

**Issue by ScorpScorp** [mcmonkeyprojects/SwarmUI#199]
### Feature Idea

It would be excellent if Flux GGUF transformer models & GGUF Clip Encoders/t5xxl/vae were directly compatible and available for selection in the default Generation tab. (For example I am currently using **_t5-v1_1-xxl-encoder-q8_0_** with **_flux1-dev-q8_0_**.

I've been using GGUF nodes in the Comfy Workflow tab, however I miss the ease of generation/fine-tuning in Generation tab when it comes to LORAs, integrated image gallery, etc.

I've also tried modifying the default workflow, however it results in a mess when imported back to Generate tab and obviously LORAs aren't selectable as it becomes a custom workflow:
![image](https://github.com/user-attachments/assets/532c7ad1-04d9-4faf-9cbd-7e2a8e1988d9)
![image](https://github.com/user-attachments/assets/9538c2ac-31bc-4395-a87f-de1cc6f095a6)

I saw this feature was previously asked about, so my apologies if it has been decided to leave it out for now. Thank you for all the hard work!

**Comment by mcmonkey4eva** [comment]
GGUF is supported https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#gguf-quantized-models
