### ISSUE TITLE
Use SAM2 instead of CLIPSeg for <segment:>

### ISSUE THREAD

**Issue by Nina9194** [mcmonkeyprojects/SwarmUI#200]
### Feature Idea

Is this possible? From my brief research, SAM2 annotations exist, but I could not find any example usage similar to CLIPSeg. 

However, I suggest another method: create a box for the prompted object with CLIPSeg, then feed it to SAM2. This notebook shows the box usage: https://colab.research.google.com/github/facebookresearch/segment-anything-2/blob/main/notebooks/image_predictor_example.ipynb#scrollTo=226df881 / https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/image_predictor_example.ipynb
The example is near the end.

I will share a Comfy workflow if I can set up this process. Please consider this new functionality for the \<segment:\> prompt.

**Comment by mcmonkey4eva** [comment]
Not directly, no, as SAM does not have text input.

But you can use it for masking slightly more manually, see announce post @ https://github.com/mcmonkeyprojects/SwarmUI/discussions/1#discussioncomment-10296989
