### ISSUE TITLE
Error pops up on all API requests when using Colab.

### ISSUE THREAD

**Issue by kitty7779** [mcmonkeyprojects/SwarmUI#201]
### Expected Behavior

Functioning as usual.

### Actual Behavior

Blockage of all functionality.

### Steps to Reproduce

Happens even on a clean install in Colab.

### Debug Logs

```powershell
10:56:58.475 [Error] [WebAPI] Error handling API request '/API/InstallConfirmWS': Invalid request method: GET
```

### Other

Happened with my install in drive whenever I clicked generate and pops up again when I try to do a clean install in session storage without mounting drive. I have uninstalled my drive install and attempted to reinstall it (and obviously failed) in attempt to fix the problem so unfortunately I can't provide proper debug logs as I can't access the "server" menu

**Comment by mcmonkey4eva** [comment]
I think there might be a cloudflared bug? That looks like it's not properly forwarding websockets

**Comment by kitty7779** [comment]
Yep, it was cloudflared. There was a new release yesterday that messed everything up. Downgraded to the previous one and it let me click install.

**Comment by mcmonkey4eva** [comment]
ooh, nice - I pushed a change to the default to use the prior version

**Comment by yoinked-h** [comment]
you typed the link incorrectly (i blame github and their unstandardized link system) #203
