### ISSUE TITLE
Set and save custom resolutions with labels

### ISSUE THREAD

**Issue by SlothDotEXE** [mcmonkeyprojects/SwarmUI#202]
### Feature Idea

Suggestion: QOL Fix for Custom Resolutions

In the resolution dropdown when generating an image, a user is able to select from a variety of preset image resolutions;

- 1:1
- 16:9
- 3:4
- Etc

Users should be able to add additional resolutions that may benefit the user (ie. 512x512 and then upscale 2x to 1024x1024 to save on render times). After implementation the order could look like;

- 1:1
- 16:9
- 3:4
- (Quick Render) 512x512
- (Ryans Custom Dimensions) 400x800

**Comment by mcmonkey4eva** [comment]
the `Presets` menu is good for things like this, you can even embed the upscale params in the same preset if you want
