### ISSUE TITLE
Negative prompt for FLUX.1 [dev] is unsupported

### ISSUE THREAD

**Issue by Ilya87** [mcmonkeyprojects/SwarmUI#204]
### Expected Behavior

I use FLUX.1 [dev] model, flux1-dev-bnb-nf4-v2 (or GGUF format), select Clip.l and T5xxl_enconly from UI, positive prompt work, negative prompt also work.

### Actual Behavior

Negative prompt is totally ignored.

### Steps to Reproduce

Try to generate image with negative prompt and without - result is the same.

### Debug Logs

```powershell
https://paste.denizenscript.com/View/125886
```

**Comment by mcmonkey4eva** [comment]
Negative prompts don't work when CFG=1, you have to set CFG higher for negative to be calculated (at the cost that flux gets weird with higher CFG, and you might need eg the advanced dynamic thresholding to mimic scale back down to 1)

**Comment by Ilya87** [comment]
> at the cost that flux gets weird with higher CFG, and you might need eg the advanced dynamic thresholding to mimic scale back down to 1
Thank you! I have found this info in docs. After you wrote the solution.
