### ISSUE TITLE
Failed to initialize NumPy: _ARRAY_API not found

### ISSUE THREAD

**Issue by commonsmutual** [mcmonkeyprojects/SwarmUI#205]
### Expected Behavior

I'm pulling my hair out trying to get everything to work. I keep getting an error on loading Swarm. I am working in a Conda venv, Have made sure that all dependencies are compatible, conda python is 3.10.2, numpy 1.23.5, torch 2.0.1, have done a million clean installs. I'm on an m2 pro macbook pro, sonoma 14.5.

### Actual Behavior

Get an error: Error: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)

Full:
```
09:28:01.965 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):  File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/main.py", line 83, in <module>
09:28:01.966 [Warning] [ComfyUI-0/STDERR]     import comfy.utils
09:28:01.966 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 20, in <module>
09:28:01.966 [Warning] [ComfyUI-0/STDERR]     import torch
09:28:01.966 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
09:28:01.966 [Warning] [ComfyUI-0/STDERR]     from .functional import *  # noqa: F403
09:28:01.967 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
09:28:01.967 [Warning] [ComfyUI-0/STDERR]     import torch.nn.functional as F
09:28:01.967 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
09:28:01.967 [Warning] [ComfyUI-0/STDERR]     from .modules import *  # noqa: F403
09:28:01.967 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
09:28:01.967 [Warning] [ComfyUI-0/STDERR]     from .transformer import TransformerEncoder, TransformerDecoder, \
09:28:01.967 [Warning] [ComfyUI-0/STDERR]   File "/Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
09:28:01.967 [Warning] [ComfyUI-0/STDERR]     device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
09:28:01.967 [Warning] [ComfyUI-0/STDERR] /Users/cassie/AI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
```
### Steps to Reproduce

conda activate swarmui_env
./launch-macos.sh 

Have also tried it without venv and also in a venv outside of Conda.

### Debug Logs

https://paste.denizenscript.com/View/125891

**Comment by mcmonkey4eva** [comment]
Swarm by default installs the comfy backend for you in a venv, if you did custom install management you likely broke something that won't be broke if you just reinstall and let swarm handle it.

Specifics here look like just a mismatch between the version of Numpy and Transformers pip packages.
(Numpy should be 1.26.4, and transformers 4.44.2)

**Comment by commonsmutual** [comment]
OK thanks.

I relatively recently migrated from an Intel Macbook Pro to an M2 Prop Macbook Pro. The problem was that this meant that there were two instances of Homebrew on the computer as the migration moved all of my files and folders over and intel and M chips install it in different folders. I had Homebrew installed on my old computer and had re-installed in on my new computer. This meant that it was all a bit of a mess and programs were potentially not pulling the right dependencies. 

My solution was to uninstall both instances of Homebrew. I then installed the Numpy and Transformers versions specified. The re-installed Homebrew. Everything works now!
