### ISSUE TITLE
Loader (?) frame cuts off text in Small Thumbnail view mode inconsistently

### ISSUE THREAD

**Issue by jwax33** [mcmonkeyprojects/SwarmUI#207]
### Expected Behavior

Expected behavior: text to be not cut in half, or at least cut in half uniformly across the row.

### Actual Behavior

![image](https://github.com/user-attachments/assets/0a1cf6c3-85ae-4920-94d1-3e61f808a817)

Basically, as you can see, the second line of the filename for the LoRAs here is sometimes fully visible and sometimes cut halfway off.  There doesn't not seem to be a particular reason for it visible from here.  While the screenshot is for the LoRAs tab, it applies to all tabs down here in Small Thumbnail mode.

### Steps to Reproduce

Open a tab in the loader frame that has enough items to generate a second row and select the Small Thumbnail view option

### Debug Logs

https://paste.denizenscript.com/View/125919

**Comment by mcmonkey4eva** [comment]
fixed
