### ISSUE TITLE
Button for swapping height and width values under resolution options when "custom" is selected

### ISSUE THREAD

**Issue by k1logr4m** [mcmonkeyprojects/SwarmUI#210]
### Feature Idea

Add a button to swap Height and Width values when "custom" has been selected on Resolution options. It would make it easier for switching between portrait and landscape without changing the resolution/size of the image. 

### Other

I personally switch between portrait and landscape a lot. Every time I need to manually type the number because picking from the aspect ratio drop-down menu changes the resolution to a smaller one. I'm used to generating at 1152x896.

**Comment by mcmonkey4eva** [comment]
That resolution in Swarm's aspect ratio dropdown is 4:3 and 3:4

**Comment by brendanhoar** [comment]
+1 

I was about to add this as a feature request (when set to Custom) as well.

**Comment by Griphen116** [comment]
+1 to this request.

**Comment by k1logr4m** [comment]
Thank you all for implementing this feature. The feature has been merged, so I will close this issue.
