### ISSUE TITLE
DOTNET_INSTALL_DIR environment variable obeyed by dotnet-install.sh but not added to path by launch-linux.sh

### ISSUE THREAD

**Issue by matchatealeaf** [mcmonkeyprojects/SwarmUI#211]
### Expected Behavior

dotnet installed to `DOTNET_INSTALL_DIR` by `dotnet-install.sh` if set, and added to PATH in `launch-linux.sh`

### Actual Behavior

dotnet installed to `DOTNET_INSTALL_DIR` by `dotnet-install.sh` if set, but not added to PATH in `launch-linux.sh`.

### Steps to Reproduce

1. Set or export `DOTNET_INSTALL_DIR` to directory other than `$SCRIPT_DIR/.dotnet` and `~/.dotnet`.
2. `dotnet` command not found after installation.

### Debug Logs

```
./launch-linux.sh
cat: src/bin/last_build: No such file or directory


WARNING: You did a git pull without building. Will now build for you...

mv: cannot stat './src/bin/live_release': No such file or directory
./launch-linux.sh: line 38: dotnet: command not found
./launch-linux.sh: line 47: dotnet: command not found
```

**Comment by mcmonkey4eva** [comment]
... if you set a path that isn't the one the scripts are set for, and you're actively exporting your own env vars anyway, you'll naturally have to export your own custom PATH as well?

**Comment by matchatealeaf** [comment]
Very well. My reasoning is that DOTNET_INSTALL_DIR is standardized and so it's natural for some people to have it set in their `.profile`, but not necessarily has it in their PATH since `dotnet-install.sh` did not set PATH for it.
