### ISSUE TITLE
Mask Shrink Grow + ControlNet

### ISSUE THREAD

**Issue by F85x** [mcmonkeyprojects/SwarmUI#213]
### Expected Behavior

When selecting Mask Shrink Grow while editing an image with a mask, it is expected that ControlNet can be applied to the cropped image.

### Actual Behavior

It seems that the preprocessor uses the full image instead of the one cropped by the mask. This makes it impossible to efficiently apply ControlNet.

### Steps to Reproduce

Edit an image, apply a mask, and select Mask Shrink Grow. Enable the ControlNet option and use any available model.
![image](https://github.com/user-attachments/assets/4584f67a-f6f6-41c6-9aee-c100aa679fb7)

### Debug Logs

None

**Comment by limonadinis** [comment]
+1! This behaviour is bugging me since the day i started using Swarm. The same issue with controlnet being applied incorrectly happens when you enable tiling in refiner/upscaler.

**Comment by F85x** [comment]
Hello! I have no idea how to help with the code to fix this issue, but while playing around with the workflow tab, I found that the problem apparently gets resolved if, instead of inputting the "SwarmLoadImageB64" as the image in the "Apply ControlNet" node, we use the output from the "SwarmImageCrop" node. I hope this at least helps someone who knows how to modify the code. Thanks!
![image](https://github.com/user-attachments/assets/8bcf8467-1536-46a5-abb4-c9a4ecd8fa49)

**Comment by mcmonkey4eva** [comment]
Fixed controlnet with mask-shrunk init image
