### ISSUE TITLE
[Feature Request]: Team up with Manual developer and integrate its features into swarmui

### ISSUE THREAD

**Issue by Vigilence** [mcmonkeyprojects/SwarmUI#216]
### Feature Idea

[Manual ](https://www.reddit.com/r/StableDiffusion/comments/1erl7v1/about_manual_100_release_as_open_source_trying_to/)seems to be way ahead of any frontend, including invoke for much of its features.  It would be great if the [manual](https://manualai.art/) dev was helping develop the front end for comfyui.

https://www.youtube.com/watch?v=3NynPgEyLNA

**Comment by mcmonkey4eva** [comment]
that does look pretty cool, i'd love for him to join his efforts into swarm, if you want to reach out and suggest this to him. Not sure if he'd want to? it sounds like he just wants to drop that app and leave to take paid work. I can't offer money for swarm contribution or anything unfortunately. But if he does want to contribute his skills into foss that'd be awesome
