### ISSUE TITLE
Some images break image history

### ISSUE THREAD

**Issue by CaptainVarghoss** [mcmonkeyprojects/SwarmUI#217]
### Expected Behavior

Image history should show all images in the directory.

### Actual Behavior

Image history window is blank when subfolder is selected containing a non-generated image file.

### Steps to Reproduce

I found this issue by generating an image, then editing the image in an external browser and then saving the image, over writing the original.

I've included the image just in case, I'm guessing it's a metadata problem or something

![new-images20240827_215855_45135496](https://github.com/user-attachments/assets/e8989680-1159-421a-bafb-97a4d781a34a)

### Debug Logs

https://paste.denizenscript.com/View/126054

**Comment by mcmonkey4eva** [comment]
I wasn't able to replicate the history view breaking? but I did replicate an internal error when clicking it, which is fixed

**Comment by CaptainVarghoss** [comment]
After further testing, it looks like it only breaks the 'Starred' folder, putting the image in the new images folder doesn't cause the problem

**Comment by mcmonkey4eva** [comment]
Oo, yep, replicated, fixed
