### ISSUE TITLE
Considerable slowdown after updating on 8/28 at 8 am pst

### ISSUE THREAD

**Issue by MiloMindbender** [mcmonkeyprojects/SwarmUI#218]
### Your question

I've been using this setup with flux D for awhile but after pulling updates this morning I am noticing a considerable slowdown.  Like from a typical generation time of 40 seconds going up to as long as 3 minutes.  No errors or other strange stuff, it's just taking a lot longer to generate.  Was something changed that could account for this?  Some generations are still quick but there is no pattern I can see.  I've had ones using just one character lora take a lot longer than the same setup did yesterday.

### Logs

There don't seem to be any errors in the logs, looks the same as before.

### Other

The machine has 256g RAM, 24gb 4090 gpu

**Comment by mcmonkey4eva** [comment]
either (A) your system is just having a time, or (B) it's an issue with a recent [comfy update](https://github.com/comfyanonymous/ComfyUI)

in the case of B: go to server->backends->edit the comfy backend->set autoupdate to false->then save and shutdown swarm
then open the folder `(Swarm)/dlbackend/comfy/ComfyUI`, open a terminal in the folder, and run `git checkout v0.1.3` or `v0.1.2`, then relaunch swarm and try that
