### ISSUE TITLE
Is there a way to add preset names to file outputs?

### ISSUE THREAD

**Issue by MartyMcStarfox** [mcmonkeyprojects/SwarmUI#219]
### Your question

In the [docs](https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/User%20Settings.md#path-format), it says to put [some parameter name here], but whatever name I try in the OutputPathBuilder doesn't work. I've tried [presets_used], [presetsused], [presetname]. [presets] and [preset_name].

Speaking of presets, could there be a way to sort them?

**Comment by mcmonkey4eva** [comment]
re out path: currently no, they're tracked a bit weirdly, so that's a needed feature to add that.

Re sorting them: what do you mean?

**Comment by MartyMcStarfox** [comment]
I meant being able to drag them or some kind of option to sort them alphabetically. New presets are always put last, and Swarm jumbles up the ordering of imported csv files for some reason, which can make them hard to find. 

In a1111, I'd just edit the styles csv to change the ordering. Does Swarm have a file where the presets are stored I could edit? The only files I can find related to presets look like scripts and stuff.

**Comment by mcmonkey4eva** [comment]
You can now use `[presetsused]` or `[presets_used]` or whichever to read presets in the output path.

For the sorting thing, make a separate feature request

**Comment by MartyMcStarfox** [comment]
Awesome, thanks :D
