### ISSUE TITLE
Feature Request: Paste from Clipboard for Initial Image (img2img) or image in-paint 

### ISSUE THREAD

**Issue by TheEliteGeek** [mcmonkeyprojects/SwarmUI#22]
There doesn't appear to be any obvious way to paste an image from the clipboard to use as the Initial image for img2img or in-painting.
Instead, ctrl+v pastes the image to be read by CLIP. There should be an option to also use it as the initial image.

This breaks the workflow for anyone who uses external image editors to make specific edits to images before feeding them back into img2img, without the need to save the intermediary edited photo.
 
For example, my workflow when using Auto1111 was to make quick edits to a photo in Photoshop, copy (not save) the entire image and then paste into Img2Img or for in-painting, generate, copy, Photoshop, rinse/repeat until I'm happy with the results.

**Comment by mcmonkey4eva** [comment]
Right now, you can:
- Drag a file into the image input
- CTRL+V in prompt then drag to the init image and remove from prompt
- click the init image to get a file selector and go that way

The main thing to handle to allow CTRL+V direct into the image inputs is proper focus handling iirc

**Comment by TheEliteGeek** [comment]
> Right now, you can:
> 
>     * Drag a file into the image input
> 
>     * CTRL+V in prompt then drag to the init image and remove from prompt
> 
>     * click the init image to get a file selector and go that way
> 
> 
> The main thing to handle to allow CTRL+V direct into the image inputs is proper focus handling iirc

I really appreciate your reply and providing a solution. This works well for me!

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/user-attachments/assets/aaa04039-3b5f-4e2c-baae-bad4e18b5566)

Dwedit's PR has added a little box you can CTRL+V inside of
