### ISSUE TITLE
Unable to create TensorRT engine

### ISSUE THREAD

**Issue by Lolagatorade** [mcmonkeyprojects/SwarmUI#221]
### Expected Behavior

![image](https://github.com/user-attachments/assets/18b7417b-1c4b-47e5-aeed-e126ec174052)
![image](https://github.com/user-attachments/assets/fcb5c61c-f83e-479f-8bfd-dcb871d0ef8d)

### Actual Behavior

creates tensor

### Steps to Reproduce

wont work on my desktop manjaro, gtx 1060, 32gb ram, 6gb vram wont generate for sdv1.5 nor turbo even though it stays well below 5gb when starting with sdv1.5....

### Debug Logs

in image

**Comment by mcmonkey4eva** [comment]
Probably an error to post to https://github.com/comfyanonymous/ComfyUI_TensorRT
