### ISSUE TITLE
Swarm unable to load comfyui backend

### ISSUE THREAD

**Issue by michaelkhboo** [mcmonkeyprojects/SwarmUI#226]
### Your question

I have trouble loading comfy backend with swarm, been using stability matrix to launch and after  fellow advice from the team, i launched it externally with the launch-windows.bat file, and it is still the same issue that im facing.

Here's the comfy status on swarm
<img width="889" alt="image" src="https://github.com/user-attachments/assets/0d7fcad1-ba19-497d-b4a5-6b8c9ae00432">

Heres the cmd log if it helps

Time Elapsed 00:00:03.48
15:20:23.712 [Init] === SwarmUI v0.9.2.2 Starting at 2024-08-30 15:20:23 ===
15:20:23.747 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
15:20:23.753 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
15:20:23.753 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
15:20:23.754 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
15:20:23.754 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
15:20:23.755 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
15:20:23.788 [Init] Parsing command line...
15:20:23.789 [Init] Loading settings file...
15:20:23.804 [Init] Re-saving settings file...
15:20:23.819 [Init] Applying command line settings...
15:20:23.843 [Init] Prepping options...
15:20:23.873 [Init] Current git commit marked as date 2024-08-30 00:54:24
15:20:23.930 [Init] CPU Cores: 32 | RAM: 63.15 GiB total, 41.54 GiB available
15:20:23.930 [Init] GPU 0: NVIDIA GeForce RTX 4090 | Temp 41C | Util 13% GPU, 1% Memory | VRAM 23.99 GiB total, 20.39 GiB free, 3.19 GiB used
15:20:23.945 [Init] Loading models list...
15:20:24.097 [Init] Loading backends...
15:20:24.098 [Init] Loading backends from file...
15:20:24.101 [Init] Prepping API...
15:20:24.101 [Init] Initializing backend # 3 - ComfyUI Self-Starting...
15:20:24.102 [Init] Prepping webserver...
15:20:24.104 [Init] Backend request handler loop ready...
15:20:24.270 [Init] Scan for web extensions...
15:20:24.272 [Init] Readying extensions for launch...
15:20:24.272 [Init] Launching server...
15:20:24.273 [Init] Starting webserver on http://localhost:7801
15:20:24.705 [Init] Swarm is up to date! You have version 0.9.2.2, and 0.9.2-Beta is the latest.
15:20:24.706 [Init] Program is running.
15:20:25.208 [Init] Launch web browser to install page...
15:20:25.664 [Error] [WebAPI] Error handling API request '/API/GetCurrentStatus': Request input has unknown session id (if you're not writing API code you can ignore this message)
15:20:25.668 [Info] Creating new admin session 'local' for ::1
15:20:25.969 [Init] Self-Start ComfyUI-3 on port 7821 is loading...

**Comment by mcmonkey4eva** [comment]
so, (A), ... go back and actually use the swarm installer. You're still trying to use your matrix copy of comfy instead of letting swarm install things.

(B) if you have issues on a clean install, go to server -> logs -> hit pastebin -> paste the link back to here
