### ISSUE TITLE
Add configurable paths for clip and diffusion_models/unet

### ISSUE THREAD

**Issue by GodEmperor785** [mcmonkeyprojects/SwarmUI#227]
### Feature Idea

In SwarmUI there are already some configurable paths in: Server -> Server Configuration -> Paths
But not all paths are there, for example paths for clip models or diffusion_models/unet are missing.
I know that there is ModelRoot but it still probably requires the same name and directory structure.

I have several image generation UIs and I would like to share all models between them, without duplicating the big model files or making workarounds like symbolic links/junctions - configurable paths allow to have any location that user wants.

Would it be possible to add missing configurable paths (at least clip and diffusion_models/unet, perhaps also upscale_models)?

**Comment by brendanhoar** [comment]
+1, especially after the admonishment in discord reminding users that paths are configurable and links should be unnecessary.

**Comment by The-Istar** [comment]
+1 here as well. It is especially frustrating that the clip folder is called clip in SwarmUI but CLIP in StabilityMatrix. Causing me 2 have 2 folders for clip and neither of the paths is configurable at the moment.

**Comment by mcmonkey4eva** [comment]
added

**Comment by The-Istar** [comment]
> added

And thanks for the addition. Not wanting to sound unthankful. :)

**Comment by GodEmperor785** [comment]
For example in webui-forge loading Flux models works from the same directory as SD/SDXL models, so they must have handled model type detection somehow - loading will only fail if you don't specify text encoders or VAE.

**Comment by mcmonkey4eva** [comment]
oh - don't do multiple requests in one issue please, open a separate issue for diffusion_models

**Comment by GodEmperor785** [comment]
> oh - don't do multiple requests in one issue please, open a separate issue for diffusion_models

Made new issue of type "Feature Request" - see #281
