### ISSUE TITLE
UNET bnb_NF4 model image generation

### ISSUE THREAD

**Issue by cbresciano** [mcmonkeyprojects/SwarmUI#237]
### Your question

I´ve put the UNET bnb_NF4 model in the unet directory and it appears in the models list in the interface. I selected it and clicked Generate. Then a message appears "all backends failed to load the model". The baked bnb_NF4 version works OK, it´s in the StableDiffusion directory. In the SwarmUI "Workflow ComfyUI" tab, I created a workflow with UNETLoaderNF4 and the node finds the model in the directory and the generation works fine. The form interface in unable to generate images with UNET bnb_NF4 models yet?

**Comment by mcmonkey4eva** [comment]
nf4 unets aren't supported in https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4 which is what swarm uses for that atm

but you should just use gguf for quants anyway, works better than nf4
