### ISSUE TITLE
UNC Path support for output folders

### ISSUE THREAD

**Issue by smbell1979** [mcmonkeyprojects/SwarmUI#239]
### Expected Behavior

UNC Paths to work correctly when specified as an output folder.

### Actual Behavior

`2024-09-02 10:35:01.797 [Error] Refusing dangerous access, got path '/AMETHYST/RaidStore/AI/SwarmUI/Output/local/raw/
2024-09-02/1035--flux1-dev-1244152968.png' which resolves to 'F:\AMETHYST\RaidStore\AI\SwarmUI\Output\local\raw\2024-09-02' which does not obey expected root '//AMETHYST/RaidStore/AI/SwarmUI/Output'`

### Steps to Reproduce

Set a UNC path as the output folder.

### Debug Logs

https://paste.denizenscript.com/View/126190

### Other

It does actually write the image correctly, it seems to not like the UNC path when I refresh the Image History in the GUI.

I thought that "AllowUnsafeOutpaths" might help, but it did not.

**Comment by mcmonkey4eva** [comment]
Do you have Swarm installed on a network drive? Or is this... you're using network drive format paths, but it's a local drive?

You can set `OutputPath` in ServerConfiguration to `F:\AMETHYST\RaidStore\AI\SwarmUI\Output` to fix this error, but other issues may arise from weird install paths.
Generally you should only ever run software from local installs on OS-appropriate drives (on Windows that'd be a local NTFS drive). You can of course store your models and outputs wherever via server config (as long as the path resolves to itself!)
