### ISSUE TITLE
For Flux add Aspect Ratio for Social Media Presets

### ISSUE THREAD

**Issue by Firef4rt** [mcmonkeyprojects/SwarmUI#244]
### Feature Idea

With Flux the Aspect Ratio is not realy limited. But the give template ratios are not so usefull for Flux.
Maybe copy the AR Setting from the CR Aspect Ratio Social Media Node : 

The aspect_ratio parameter allows you to select from a list of predefined aspect ratios tailored for various social media platforms. This parameter ensures that your image is resized and cropped to fit the selected aspect ratio perfectly. Options include
 "Instagram Portrait-  1080x1350", "Instagram Square - 1080x1080", "Instagram Landscape - 1080x608", "Instagram Stories/Reels - 1080x1920", "Facebook Landscape - 1080x1350", "Facebook Marketplace - 1200x1200", "Facebook Stories - 1080x1920", "TikTok - 1080x1920", "YouTube Banner - 2560×1440", "LinkedIn Profile Banner - 1584x396", "LinkedIn Page Cover - 1128x191", "LinkedIn Post - 1200x627", "Pinterest Pin Image - 1000x1500", "CivitAI Cover - 1600x400", and "OpenArt App - 1500x1000".

**Comment by mcmonkey4eva** [comment]
Superseding this via https://github.com/mcmonkeyprojects/SwarmUI/issues/257 as a better way to achieve the same goal
