### ISSUE TITLE
SwarmUI with MultiGPUs/backends queues equally at start, instead of sequentially

### ISSUE THREAD

**Issue by Crono141** [mcmonkeyprojects/SwarmUI#247]
### Your question

Not sure if I'm just "doing it wrong" or not, but I just recently set up SwarmUI with 2 GPUs/2 comfy backends. One GPU is **much** faster than the other (3060 12gb vs a 1080 8gb). I usually batch 4 images at a time, so I was testing if I'd get any speed improvements by adding the second GPU. Well, my tests are inconclusive, because presently it seems that SwarmUI schedules the generations equally between the 2 cards, instead of sequentially as they come.

So for example, I queue up a prompt, 4 images, and hit generate. 2 images begin to generate, with the 3060 blowing through its first 2 before the 1080 can get through one. But instead of picking up the 3rd generation the 3060 just stops, and I have to wait until the 1080 finishes its first, and THEN it starts on the second.

This absolutely kills the point of multigpu, unless all GPUs are identical. Maybe my use case is weird (it is), but it seems to me that scheduling these sequentially as cards become available would be more efficient than just evenly splitting the workload between the number of backends/gpus.

Please let me know if I'm just doing it wrong, or if not, please consider this a feature request. Thanks.

**Comment by FurkanGozukara** [comment]
Can you try like 30? i think it should requeue once first GPU completed

**Comment by mcmonkey4eva** [comment]
There are queued sequentially, not evenly. It just queues 2 at a time per GPU (OverQueue setting) to avoid latency delays from the main queue.

As Furkan said - when you queue a lot of images at once you'll see the actual queuing behavior in action. With very small numbers of gens there's often not optimal queuing methods available.

set OverQueue on the weaker GPU to zero to never queue extra requests onto it.

There is a potential valid feature request here for finer controls over queuing preference, eg an option to heavily favor one GPU and only use others when queue is above a minimum count.

**Comment by Crono141** [comment]
Thank you very much. That setting is what I was looking for.
