### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by mspacemedia** [mcmonkeyprojects/SwarmUI#248]
### Your question

Probably not a problem with SwarmUI but most likely my install, however when attempting to create a TensorRT from Flux I get the following error in the console:

`Error in websocket handler: ComfyUI errored: {
  "error": {
    "type": "invalid_prompt",
    "message": "Cannot execute because node DYNAMIC_TRT_MODEL_CONVERSION does not exist.",
    "details": "Node ID '#10'",
    "extra_info": {}
  },
  "node_errors": []`
  
  The server backend usually falls over and this is also in the console:
  
  `20:33:32.113 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
20:33:32.116 [Warning] [ComfyUI-0/STDERR]   File "F:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1993, in load_custom_node
20:33:32.117 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
20:33:32.118 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
20:33:32.119 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
20:33:32.120 [Warning] [ComfyUI-0/STDERR]   File "F:\SwarmUI\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_TensorRT\__init__.py", line 1, in <module>
20:33:32.121 [Warning] [ComfyUI-0/STDERR]     from .tensorrt_convert import DYNAMIC_TRT_MODEL_CONVERSION
20:33:32.122 [Warning] [ComfyUI-0/STDERR]   File "F:\SwarmUI\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_TensorRT\tensorrt_convert.py", line 7, in <module>
20:33:32.123 [Warning] [ComfyUI-0/STDERR]     import tensorrt as trt
20:33:32.124 [Warning] [ComfyUI-0/STDERR] ModuleNotFoundError: No module named 'tensorrt'
20:33:32.125 [Warning] [ComfyUI-0/STDERR]`

### Logs

https://paste.denizenscript.com/View/126403

**Comment by FurkanGozukara** [comment]
i don't think so FLUX has TensorRT yet - but if had would be great

**Comment by mcmonkey4eva** [comment]
Flux TRT conversion requires more than 24 gigs of VRAM and 100+ gigs of system RAM. So it's technically supported but basically no normal computer is going to be able to run it

**Comment by FurkanGozukara** [comment]
> Flux TRT conversion requires more than 24 gigs of VRAM and 100+ gigs of system RAM. So it's technically supported but basically no normal computer is going to be able to run it

wow nice i didnt know this. it is good for massed compute then i should test and show
