### ISSUE TITLE
Blurry images

### ISSUE THREAD

**Issue by DiggyDre** [mcmonkeyprojects/SwarmUI#250]
### Your question

I keep getting FLUX blurry images. I decided to try out the new version of Forge and I get clear images using the same settings there but I don't want to use Forge because for some reason, my negative tab is greyed out on FLUX models. 
What am I doing wrong in Swarm that I can't generate a crystal clear FLUX image?

**Comment by Jelosus2** [comment]
You probably used CFG higher than 1

**Comment by DiggyDre** [comment]
> You probably used CFG higher than 1

I was using 3.5 on the Dev model.

**Comment by Jelosus2** [comment]
Try with 1

**Comment by DiggyDre** [comment]
> Try with 1

So I realize that when it is at 1, the negative tab is greyed out in Swarm, which is odd because it was automatically greyed out in Forge. I am still getting images that have blurred skin, no skin details. Nothing that looks REAL like other images that people post.

**Comment by jwax33** [comment]
Flux was designed to not use negative prompts.  Your blurred issue is probably a settings issue.  What Sampler and Scheduler are you using?  If possible, screenshot everything so we can look at it.

**Comment by DiggyDre** [comment]
> Flux was designed to not use negative prompts. Your blurred issue is probably a settings issue. What Sampler and Scheduler are you using? If possible, screenshot everything so we can look at it.

![Flux](https://github.com/user-attachments/assets/f8f7d8f2-83fd-45ff-a1b8-793e86e4f620)
Those are the only things that I have set. I actually never used Swarm until I decided I wanted to try Flux. It is so weird because some people say the CFG should be 3.5, some say 1. No matter what I try to generate, it could be a closeup of a woman's face, I still get smooth, plastic textured skin, as if the surface is blurry.

**Comment by jwax33** [comment]
![image](https://github.com/user-attachments/assets/7569044a-9ab4-41e1-b7e2-33645d102025)
So the actual CFG Scale should be set to 1.  There is another setting called Flux Guidance Scale which is by default set to 3.5.  But...that tends to make things look too plastic.  Somewhere around 2.8 is a good compromise.  Try lowering that to 2.8 and see if that helps with the blurred skin issue.

**Comment by DiggyDre** [comment]
> ![image](https://private-user-images.githubusercontent.com/16256444/365484278-7569044a-9ab4-41e1-b7e2-33645d102025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDUzNzEsIm5iZiI6MTcyNTg0NTA3MSwicGF0aCI6Ii8xNjI1NjQ0NC8zNjU0ODQyNzgtNzU2OTA0NGEtOWFiNC00MWUxLWI3ZTItMzM2NDVkMTAyMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAxMjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmNmMGYxMjg3NWQyNjEwYzlhY2VjMmY1MDQ3ZDUzYmRmZWNmOGExNTFlZTZmNTM5MTUzNzM0OGYzMmRlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRxArYPZ2aPFb4NntwQpGV8EHJrufBK-MZr6SLNv-II) So the actual CFG Scale should be set to 1. There is another setting called Flux Guidance Scale which is by default set to 3.5. But...that tends to make things look too plastic. Somewhere around 2.8 is a good compromise. Try lowering that to 2.8 and see if that helps with the blurred skin issue.

WOW! It's a shame that they hide the Guidance Scale in the advanced section since it is so vital to making a better image when using a Flux model. It made a big difference. I wonder if there are any settings in the Refiner/Upscale section that I could use to push things further? Thank you so much!

**Comment by jwax33** [comment]
There is another function called Perturbed-Attention Guidance Scale that has some impact on images.  Lowering it tends to make the sampler more creative in my experience.  The downside to it is it doubles the image generation time if you turn it on.  It's at the very bottom of the Advanced Sampling menu.

![image](https://github.com/user-attachments/assets/41e45189-a12b-44f8-a222-909b653fd4fe)

**Comment by mcmonkey4eva** [comment]
+ unmarked Flux Guidance as advanced
