### ISSUE TITLE
Just in time asset downloading

### ISSUE THREAD

**Issue by Thedougler** [mcmonkeyprojects/SwarmUI#251]
### Feature Idea

When a backend is missing a necessary asset for a generation, say a new Runpod install for example, rather than just warn the user that the backend does not have the necessary asset, the backend should remotely download it. If the user downloaded the asset using the Model downloader, that download link + API keys could be passed to the remote backend upon SwarmUI detecting the backend is missing an asset, and trigger a remote download + refresh of available models to that backend. If the model was not downloaded from Civitai or Huggingface, rsync could potentially be used instead to transfer the local model to the remote backend. 

The end result would be something I think fits quite well in SwarmUI's philosophy, automating the nitty gritty away without hiding the power of the backend. I intend to take a crack at the code myself here shortly, just made this feature request to gauge whether this is something others would want/are already working on,

**Comment by mcmonkey4eva** [comment]
Most things already work this way, eg clip models and all will autodownload.

The exception is code installs (eg custom nodes), which have a warning before downloading as it's downloading a third party code repo, ie there are potential security concerns and in some case license issues, so it's best to inform users on those.

If you're referring to some file asset that's not covered by that, please specify

**Comment by Thedougler** [comment]
I meant community assets downloaded from Civitai
