### ISSUE TITLE
Support for the new Civitai.green urls

### ISSUE THREAD

**Issue by SouthbayJay** [mcmonkeyprojects/SwarmUI#252]
### Feature Idea

With civitai.com now having a (supposedly) "SFW" website the new url civitai.green doesn't seem to be supported in the Swarm model downloader. 

Request support for .green urls for the model downloader...

<img width="753" alt="swarmgreen" src="https://github.com/user-attachments/assets/1b33ac01-0125-457d-8c29-ead34f2d9a49">

**Comment by mcmonkey4eva** [comment]
added an autoconverter that lets you paste in green URLs and it will swap to .com URLs and work as intended
