### ISSUE TITLE
Improved upscale after generation

### ISSUE THREAD

**Issue by TheNarcDad97** [mcmonkeyprojects/SwarmUI#253]
### Feature Idea

Replace the “2x upscale” option after image generation with an option to upscale using the current upscale settings. At the moment it’s not a smooth experience to quickly upscale the best generated images with your preferred settings, so allowing us to quickly upscale the image would be a very welcome feature.

**Comment by mcmonkey4eva** [comment]
duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/122
