### ISSUE TITLE
Gap in new <trigger> feature

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#254]
### Expected Behavior

The trigger keyword should work just the same if  you are using SwarmUI-style Lora selection or inline-style Lora selection

### Actual Behavior

trigger keyword(s) only get applied if SwarmUI-style Lora selection was used, it returns an empty string if inline-style Lora selection is used.

### Steps to Reproduce

0. Set a fixed seed,
1. Find a lora with a trigger phrase/keyword where you can easily tell that the LORA is applied with or without the trigger keyword/phrase.
2. Add <break><trigger> to prompt.
3. Select the Lora in the UI, this will add it to the Model selection bar. For completeness, if the weight is not 1, set it to 1.
4. Generate image.
5. Note trigger keyword/phrase in metadata.
6. Deselect the Lora in the UI, this will remove it from the Model selection bar.
7. Add the lora at the top of the prompt box by typing <lora:filepath:1> where filepath is the relative path to the lora, including the lora filename.
8. Generate image, it will be different, but will illustrate the the LORA was applied.
9. Note that the trigger keyword/phrase is missing from the metadata.

### Debug Logs

N/A

### Other

N/A

**Comment by mcmonkey4eva** [comment]
unfortunately for my sanity, special edge case handling is my speciality, so, there ya go
