### ISSUE TITLE
Editing model metadata affects model hash for Civitai

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#26]
Hey there,

I was taking a look around how SwarmUI gets its model metadata and noticed that it writes it into the `.safetensors` file headers when you edit the metadata directly. I do see there is the [Stability AI Model Metadata Standard Specification](https://github.com/Stability-AI/ModelSpec) that describes this, but I was wondering whether this could cause issues with other applications that rely on the hash to link back to Civitai and whether this has been taken into consideration?

Since the hash Civitai uses is based off the contents of the entire file (including the headers), it seems like modifying the headers would affect the hash and you'd no longer be able to link the file back to the Civitai source.

Some examples:
 - [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/7d42436754e5fb8c43e7c87868106e37a24bae5a/py/model_info.py#L110-L111)
 - [Stable-Diffusion-Webui-Civitai-Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/6e9c228820d1ef401ed967bd21c2b1fd8229e521/scripts/ch_lib/util.py#L34)
 - [StabilityMatrix](https://github.com/LykosAI/StabilityMatrix/blob/debd131ae831f26dd8738b94b11f539c15ed47b2/StabilityMatrix.Core/Helper/FileHash.cs#L42)

Interested to hear your thoughts.

**Comment by mcmonkey4eva** [comment]
Someone on Discord the other day said that "autov3" hash is equivalent to ModelSpec standard hash, ie tensorhash (skipping the metadata header).
(I haven't looked into the definition of autov3 to verify, but either way ModelSpec tensorhash is a good standard, and any projects not using a tensorhash should switch to that asap imo)

**Comment by Lawrr** [comment]
I wasn't aware of autov3. Good to know that's a thing. Possibly other projects aren't using it yet because the Civitai api doesn't support autov3 yet in that case.

**Comment by mcmonkey4eva** [comment]
I believe civitai does have it in use, but currently only for newly uploaded models, they at least thus far have not reprocessed it onto older existing models

**Comment by brendanhoar** [comment]
I verified that an AutoV3 hash from a recent model on the site works via the API (though the API documentation has not yet been updated to specify that AutoV3 hashes are supported).

**Comment by Lawrr** [comment]
Thanks all. Can confirm I see this working now. I initially tried this and got no results due to trying to use the entire hash, but it seems like the autov3 hash is just the first 12 characters of it.
