### ISSUE TITLE
Error on saving picture with comfyUI custom workflow

### ISSUE THREAD

**Issue by begin2** [mcmonkeyprojects/SwarmUI#260]
### Expected Behavior

save image

### Actual Behavior

error: ComfyUI execution error: SwarmSaveImageWS.save_images() missing 1 required positional argument: 'bit_depth'

### Steps to Reproduce

add comfyui workflow and generate image

### Debug Logs

2024-09-13 09:09:51.654 [Debug] Failed to process comfy workflow for inputs T2IParamInput(prompt: DMT Art Style, The Mummy Desert Expeditions, highest quality photograph of beautiful fullbody of woman, extreme detailed skin texture,  vast deserts, ancient tombs, Egyptian artifacts, mystical, adventurous, richly detailed, bright colors, surreal visuals,..., model: flux_n/topmodel_v40, seed: 1795390865, steps: 20, cfgscale: 1, aspectratio: 3:4, width: 896, height: 1152, scheduler: simple, fluxguidancescale: 5, comfyuicustomworkflow: PARSED%testfs%{
  "1": {
    "inputs": {
      "enabled": true,
      "swap_model": "${comfyrawworkflowinputtextreactorfaceswapnodeswapmodelb:inswapper_128.onnx}",
      "facedetection": "${comfyrawworkflowinputdropdownreactorfaceswapn..., automaticvae: True, negativeprompt: ) with raw workflow { "1": { "inputs": { "enabled": True, "swap_model": "inswapper_128.onnx", "facedetection": "retinaface_resnet50", "face_restore_model": "GFPGANv1.4.onnx", "face_restore_visibility": 1, "codeformer_weight": 0.5, "detect_gender_input": "no", "detect_gender_source": "no", "input_faces_index": "0", "source_faces_index": "0", "console_log_level": 1, "input_image": [ "8", 0 ], "source_image": [ "2", 0 ] }, "class_type": "ReActorFaceSwap", "_meta": { "title": "ReActor 🌌 Fast Face Swap" } }, "2": { "inputs": { "image": "DSC_5047.JPG", "upload": "image" }, "class_type": "LoadImage", "_meta": { "title": "Load Image" } }, "7": { "inputs": { "seed": 1795390865, "steps": 20, "cfg": 1, "sampler_name": "euler", "scheduler": "simple", "denoise": 1, "model": [ "9", 0 ], "positive": [ "10", 0 ], "negative": [ "11", 0 ], "latent_image": [ "12", 0 ] }, "class_type": "KSampler", "_meta": { "title": "KSampler" } }, "8": { "inputs": { "samples": [ "7", 0 ], "vae": [ "9", 2 ] }, "class_type": "VAEDecode", "_meta": { "title": "VAE Decode" } }, "9": { "inputs": { "ckpt_name": "flux_n\\topmodel_v40.safetensors" }, "class_type": "CheckpointLoaderSimple", "_meta": { "title": "Load Checkpoint" } }, "10": { "inputs": { "text": "DMT Art Style, The Mummy Desert Expeditions, highest quality photograph of beautiful fullbody of woman, extreme detailed skin texture,  vast deserts, ancient tombs, Egyptian artifacts, mystical, adventurous, richly detailed, bright colors, surreal visua...", "clip": [ "9", 1 ] }, "class_type": "CLIPTextEncode", "_meta": { "title": "CLIP Text Encode (Prompt)" } }, "11": { "inputs": { "text": "", "clip": [ "9", 1 ] }, "class_type": "CLIPTextEncode", "_meta": { "title": "CLIP Text Encode (Prompt)" } }, "12": { "inputs": { "width": 896, "height": 1152, "batch_size": 1 }, "class_type": "EmptyLatentImage", "_meta": { "title": "Empty Latent Image" } }, "13": { "inputs": { "bbox_model_name": "bbox/face_yolov8m.pt", "bbox_threshold": 0.5, "bbox_dilation": 10, "bbox_crop_factor": 3, "bbox_drop_size": 10, "sam_model_name": "sam_vit_b_01ec64.pth", "sam_dilation": 0, "sam_threshold": 0.93, "bbox_expansion": 0, "mask_hint_threshold": 0.7, "mask_hint_use_negative": "False", "morphology_operation": "dilate", "morphology_distance": 0, "blur_radius": 9, "sigma_factor": 1, "image": [ "8", 0 ], "swapped_image": [ "1", 0 ] }, "class_type": "ReActorMaskHelper", "_meta": { "title": "ReActor 🌌 Masking Helper" } }, "200": { "inputs": { "images": [ "13", 0 ] }, "class_type": "SwarmSaveImageWS", "_meta": { "title": "Save Image" } } }
2024-09-13 09:09:51.654 [Debug] Refused to generate image for local: ComfyUI execution error: SwarmSaveImageWS.save_images() missing 1 required positional argument: 'bit_depth'

### Other

it was working well till last update

**Comment by mcmonkey4eva** [comment]
should be fixed now

**Comment by begin2** [comment]
Yes! I confirm that it's now working well. Thanks for hyperspeed fix :)
