### ISSUE TITLE
Command line flag `--data_dir` not implemented?

### ISSUE THREAD

**Issue by mbac** [mcmonkeyprojects/SwarmUI#261]
### Expected Behavior

Hi!

Running Swarm v. 0.9.2.2 (2024-09-13 11:21:23).

When I launch Swarm with the `--data_dir` command line flag, I'd expect the app to switch its Data directory

### Actual Behavior

Whenever I use the flag:

```
18:27:16.871 [Warning] Unused command line flag 'data_dir'
```

`echo -e "Starting SwarmUI with config at $SWARM_CONFIG_DIR"`

This reports the correct directory…

### Steps to Reproduce

```
# RunPod provisioning script
export $SWARM_DIR="/workspace/SwarmUI"
export SWARM_CONFIG_DIR="/workspace/podstarter/config/swarm"
    
if [[ "$*" != *"--vanilla"* ]]; then
        echo -e "Starting SwarmUI with config at $SWARM_CONFIG_DIR"
        bash "$SWARM_DIR/launch-linux.sh" \
            --launch_mode none \
            --host 0.0.0.0 \
            --data_dir "$SWARM_CONFIG_DIR"
fi
```

### Debug Logs

https://paste.denizenscript.com/View/126478

### Other

According to one user on the Discord channel, the flag might not be implemented yet? 

Thanks…

**Comment by mcmonkey4eva** [comment]
oh, no, was working fine, just mistakenly displayed the unused warning. fixed

**Comment by mbac** [comment]
Hi,

I'm now running v. 0.9.3.1 and I'm encountering kind of a similar problem. When using both `--data_dir` and `--settings_file`, upon launch I get:
```
12:08:03.510 [Warning] Unused command line flag 'settings_file'
```
However, when I omit `--settings_file`, Swarm seems to ignore `--data_dir` and it loads with default settings.

**Comment by mcmonkey4eva** [comment]
olol, exact same case as before, the next line after the relevant line from before, just got missed. I fixed and double checked to make sure there's no other CLI flags with the same outdated call

re the settings part: it was statically set to `Data/Settings.fds` instead of `{DataDir}/Settings.fds`, ie the settings path didn't care about your data path setting. I've updated it to now take the datadir into account for the default settings path, and same for the backends file

**Comment by FurkanGozukara** [comment]
@mcmonkey4eva can we set root directory from cli ? is it datadir?

**Comment by mcmonkey4eva** [comment]
`--data_dir` controls the data root (for Settings file, Backends file, User database, Wildcards, a few other things)

**Comment by FurkanGozukara** [comment]
@mcmonkey4eva ty for answer

it would be amazing if we could set these 2 from cli 

![image](https://github.com/user-attachments/assets/fddaff79-3ef6-414f-87a7-f81f72e1f8bd)

![image](https://github.com/user-attachments/assets/a6515268-22eb-4a2f-a19c-d1f0836d7830)

**Comment by mcmonkey4eva** [comment]
If you need to automate either of those values, you should just emit prebuild Settings.fds and Backends.fds files and use the CLI args to point at those
