### ISSUE TITLE
Broken autocompletion for booru tags

### ISSUE THREAD

**Issue by Jelosus2** [mcmonkeyprojects/SwarmUI#262]
### Expected Behavior

When typing, for example `white_s`, be able to see the new results. 

### Actual Behavior

When typing `white_` and then adding something else it doesn't display the list anymore.

### Steps to Reproduce

Using any booru tag csv list. Not sure if there's some setting that triggers this but I'm currently using this ones:
![image](https://github.com/user-attachments/assets/e70f7622-c104-4c83-894a-5f9b7e4b3c5d)

### Debug Logs

https://paste.denizenscript.com/View/126497

**Comment by Jelosus2** [comment]
I want to convert the underscores in spaces, that's why I use the "Spaces" mode. The issue is the following: If I want to autocomplete `hair tie in mouth` I would write `hair_tie` and the select the tag I'm searching for in the list but now if after typing `hair` I add an underscore the list is gone.

**Comment by Jelosus2** [comment]
This is what I mean
![image](https://github.com/user-attachments/assets/d3334243-8641-4c30-8318-5dbf9e5450a2)
![image](https://github.com/user-attachments/assets/e679b9e9-a582-471f-86f6-6c564ee1fb0c)
After typing an underscore the list is hidden, I want to be able to do like `hair_tie_in_mo` with the list still present and when i hit enter it replaces the underscores with spaces and at the same time autocompleting the tag I selected from the list, I hope is more clear now.

**Comment by mcmonkey4eva** [comment]
Oh, yep, it was searching the spaced version instead of the underscore version -- fixed, and tossed in a bonus protection in case the source file had spaces in it
