### ISSUE TITLE
GGUF flux

### ISSUE THREAD

**Issue by Maelstrom2014** [mcmonkeyprojects/SwarmUI#266]
### Your question

Hi All!
I read several times in docs about gguf models, and dont understand how to 'see it' in Swarmui. Please make more detailed instructions. That's my questions:
1) Where to put directory in settings Swarmui where my gguf flux models located
2) Have I to rename extension to .safetensors? .gguf not visible in ui
3) In menu model - choose model  - edit meta: is no FLUX type model achitecture
the only way i use flux its with comfyui workflow.
Thanx for your detailed unswer!

**Comment by Kanareika** [comment]
Create folder named "diffusion_models" in your models folder, put them there. No need to rename.

**Comment by Maelstrom2014** [comment]
> Create folder named "diffusion_models" in your models folder, put them there. No need to rename.
ok, but
1) links (windows sohrtcuts) files not seen in ui. I dont want have several copies of models. 
2) There is no FLUX in meta edit menu - Architecture: What to put here?

**Comment by mcmonkey4eva** [comment]
@Kanareika  Do not create a folder, it will automatically exist.

@Maelstrom2014 you have the legacy Stability version, please follow the SwarmUI readme to install the modern independent SwarmUI

**Comment by Maelstrom2014** [comment]
YES thanx!
