### ISSUE TITLE
Flux fp8_e4m3fn All available backends failed to load the model. / ERROR: Could not detect model type of

### ISSUE THREAD

**Issue by XZVB12** [mcmonkeyprojects/SwarmUI#268]
### Expected Behavior

Image generation

### Actual Behavior

All available backends failed to load the model. / ERROR: Could not detect model type of: /AI/ComfyUI/models/checkpoints/flux1-dev-fp8.safetensors

### Steps to Reproduce

1. run comfyUI : python main.py --fp8_e4m3fn-unet --fp8_e4m3fn-text-enc
2. run SwarmUI: ./launch-linux.sh
3. choose model and vae
4. input prompt
5. press generate

### Debug Logs

[Init] === SwarmUI v0.9.2.2 ===
[Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
[Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
[Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
[Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
[Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
[Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
[Init] Parsing command line...
[Init] Loading settings file...
[Init] Re-saving settings file...
[Init] Applying command line settings...
[Debug] [Load Time] Initial settings load took 0.14s (0.14s from start)
[Debug] [Load Time] Extension PreInit took 0.02s (0.16s from start)
[Init] Prepping options...
[Init] CPU Cores: 12 | RAM: 31.27 GiB total, 18.39 GiB available
[Init] GPU 0: NVIDIA GeForce RTX 3060 | Temp 46C | Util 41% GPU, 26% Memory | VRAM 12.00 GiB total, 10.03 GiB free, 1.63 GiB used
[Debug] [Load Time] Prep Objects took 0.12s (0.28s from start)
[Debug] [Load Time] Web PreInit took 0s (0.28s from start)
[Debug] [Load Time] Extensions Init took 0.01s (0.3s from start)
[Debug] [Load Time] Prep Utils took 0s (0.3s from start)
[Debug] [Load Time] Languages load took 0.04s (0.34s from start)
[Init] Loading models list...
[Debug] [Load Time] Model listing took 0.03s (0.37s from start)
[Init] Loading backends...
[Init] Loading backends from file...
[Debug] [Load ComfyUI API By URL #0] Waiting to load...
[Debug] [Load ComfyUI API By URL #0] Will now load...
[Init] Initializing backend #0 - ComfyUI API By URL...
[Debug] [Load ComfyUI API By URL #0] Will attempt to load value set...
[Debug] [Load Time] Backends took 0.01s (0.37s from start)
[Init] Prepping API...
[Debug] [Load Time] API took 0s (0.38s from start)
[Init] Prepping webserver...
[Init] Backend request handler loop ready...
[Debug] [Load Time] [Web] WebApp builder prep took 0.07s (0.07s from start)
[Debug] [Load Time] [Web] WebApp build took 0.04s (0.1s from start)
[Debug] [Load Time] [Web] exception handler took 0s (0.1s from start)
[Debug] [Load Time] [Web] StartStop handler took 0s (0.1s from start)
[Debug] [Load Time] [Web] static files took 0s (0.1s from start)
[Debug] [Load Time] [Web] core use calls took 0.06s (0.16s from start)
[Debug] [Load Time] [Web] core maps took 0s (0.16s from start)
[Init] Scan for web extensions...
[Debug] [Load Time] [Web] end took 0s (0.17s from start)
[Debug] [Load Time] Web prep took 0.17s (0.55s from start)
[Init] Readying extensions for launch...
[Debug] [Load Time] Extensions pre-launch took 0s (0.55s from start)
[Init] Launching server...
[Init] Starting webserver on http://localhost:7801
[Debug] [Load Time] Web launch took 0.05s (0.6s from start)
[Init] Current git commit marked as date 2024-09-16 04:50:15
[Init] Swarm is up to date! You have version 0.9.2.2, and 0.9.2-Beta is the latest.
[Init] Program is running.
[Debug] [Load ComfyUI API By URL #0] Got valid value set, will parse...
[Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
[Debug] [Load ComfyUI API By URL #0] Done parsing value set.
[Info] Creating new admin session 'local' for 127.0.0.1
[Debug] [Load ComfyUI API By URL #0] Got valid value set, will parse...
[Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
[Debug] [Load ComfyUI API By URL #0] Done parsing value set.
[Debug] Data refreshed!
[Info] User local requested 1 image with model 'flux1-dev-fp8.safetensors'...
[Debug] [BackendHandler] Backend request #1 for model flux1-dev-fp8.safetensors, maxWait=7.00:00:00.
[Debug] [BackendHandler] backend #0 will load a model: flux1-dev-fp8.safetensors, with 1 requests waiting for 0 seconds
[Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: ERROR: Could not detect model type of: /AI/ComfyUI/models/checkpoints/flux1-dev-fp8.safetensors
[Warning] [BackendHandler] backend #0 failed to load model flux1-dev-fp8.safetensors
[Debug] Will deny backends: 0
[Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
[Debug] [BackendHandler] Backend request #1 finished.
[Debug] Refused to generate image for local: All available backends failed to load the model.
[Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'api/userdata/workflows%2F.index.json'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/scripts/app.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/scripts/api.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/scripts/widgets.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/scripts/ui.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/scripts/ui/imagePreview.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/kjweb_async/svg-path-properties.min.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/kjweb_async/protovis.min.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/kjweb_async/marked.min.js'
[Debug] ComfyBackendDirect call was misrouted, rerouting to '/ComfyBackendDirect/kjweb_async/purify.min.js'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor'
[Debug] Comfy backend direct websocket request to ws, have 1 backends available
[Debug] Comfy backend direct offset for new user is 0
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor/GPU/0'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor/GPU/0'
[Debug] ComfyUI redirection gave non-200 code: '400' for URL: PATCH 'api/crystools/monitor/GPU/0'
[Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'api/userdata/workflows%2F.index.json'
[Debug] ComfyUI redirection gave non-200 code: '404' for URL: HEAD 'extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico'
[Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'api/pysssss/autocomplete'
[Debug] ComfyUI redirection gave non-200 code: '404' for URL: HEAD 'extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico'
[Info] User local requested 1 image with model 'flux1-dev-fp8.safetensors'...
[Debug] [BackendHandler] Backend request #2 for model flux1-dev-fp8.safetensors, maxWait=7.00:00:00.
[Debug] [BackendHandler] backend #0 will load a model: flux1-dev-fp8.safetensors, with 1 requests waiting for 0 seconds
[Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: ERROR: Could not detect model type of: /AI/ComfyUI/models/checkpoints/flux1-dev-fp8.safetensors
[Warning] [BackendHandler] backend #0 failed to load model flux1-dev-fp8.safetensors
[Debug] Will deny backends: 0
[Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
[Error] [BackendHandler] Backend request #2 failed: All available backends failed to load the model.
[Error] [BackendHandler] Backend request #2 failed: All available backends failed to load the model.
[Debug] [BackendHandler] Backend request #2 finished.
[Debug] Refused to generate image for local: All available backends failed to load the model.

### Other

This issue only occurs in 'Generate' tab. I can easily generate images in the comfy workflow tab or directly through the comfyUI interface.
In the comfyUI console I get the following error message:
```
!!! Exception during processing !!! ERROR: Could not detect model type of: /AI/ComfyUI/models/checkpoints/flux1-dev-fp8.safetensors
Traceback (most recent call last):
File "/AI/ComfyUI/execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/AI/ComfyUI/execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/AI/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/AI/ComfyUI/nodes.py", line 540, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/AI/ComfyUI/comfy/sd.py", line 525, in load_checkpoint_guess_config
raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: /AI/ComfyUI/models/checkpoints/flux1-dev-fp8.safetensors

Prompt executed in 26.03 seconds
```

**Comment by The-Istar** [comment]
Did you put the file in the correct folder? Looking at the output it does not look like it.

From the Docs: "Put dev/schnell in (Swarm)/Models/diffusion_models"

[https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md](https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md)

**Comment by The-Istar** [comment]
I agree with you though, some automation/intelligence behind the model loader would be nice. I have had to move models in between folders myself a couple of times already as well. It is.. cumbersome.

f automation is not possible, maybe something to change the model type in the menu or metadata? So I don't have to save my models in all there different folders but can have them in 1 place. That would be nice.

**Comment by XZVB12** [comment]
> Did you put the file in the correct folder? Looking at the output it does not look like it.

my models are located in the folder SwarmUI/Models/Stable-Diffusion/ and /AI/ComfyUI/models/checkpoints/
At the moment I am using symbolic links, but I also tried to physically copy a file, but it didn’t change anything.

**Comment by XZVB12** [comment]
I tried to physically move the model from /AI/ComfyUI/models/checkpoints/ to SwarmUI/Models/Stable-Diffusion/ and got a new error message:
SwarmUI:
```
[Info] User local requested 1 image with model 'flux1-dev-fp8.safetensors'...
[Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI errored: {
"error": {
"type": "prompt_outputs_failed_validation",
"message": "Prompt outputs failed validation",
"details": "",
"extra_info": {}
},
"node_errors": {
"4": {
"errors": [
{
"type": "value_not_in_list",
"message": "Value not in list",
"details": "ckpt_name: 'flux1-dev-fp8.safetensors' not in ['fenrisxl_fenrisFluxV1.safetensors', 'ratatoskrAnimalCreature_v40FP8.safetensors', 'sd3_medium_incl_clips.safetensors']",
"extra_info": {
"input_name": "ckpt_name",
"input_config": [
[
"fenrisxl_fenrisFluxV1.safetensors",
"ratatoskrAnimalCreature_v40FP8.safetensors",
"sd3_medium_incl_clips.safetensors"
],
{
"tooltip": "The name of the checkpoint (model) to load."
}
],
"received_value": "flux1-dev-fp8.safetensors"
}
}
],
"dependent_outputs": [
"9"
],
"class_type": "CheckpointLoaderSimple"
}
}
}
[Warning] [BackendHandler] backend #0 failed to load model flux1-dev-fp8.safetensors
[Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
```
comfyUI:
```
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
- Value not in list: ckpt_name: 'flux1-dev-fp8.safetensors' not in ['fenrisxl_fenrisFluxV1.safetensors', 'ratatoskrAnimalCreature_v40FP8.safetensors', 'sd3_medium_incl_clips.safetensors']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

**Comment by XZVB12** [comment]
> Also, have you downloaded the required text encoders for Flux? You should have a clip_l.safetensors file and a t5***.safetensors file in your models/clip directory.

yes


> SwarmUI/Models/Stable-Diffusion/ is _not_ the correct directory for the flux1-dev-fp8 mode

![изображение](https://github.com/user-attachments/assets/682b416f-b98e-4d26-b7c5-4dca3cca60a7)

**Comment by jwax33** [comment]
Did you download one of those two specific models from those two links?  Otherwise, flux1-dev-fp8.safetensors does not go in that directory.  Those two models have the text encoders built in to them already, in which case you would not need the encoders in your models/clip directory.

**Comment by XZVB12** [comment]
> Did you download one of those two specific models from those two links

No, because the text does not specify that these models are modified I assumed they are identical to my

Folder models/unet does not exist for me, I moved models to models/diffusion_models and now it started loading t5xxl_enconly.safetensors , although I already have the 8fp version and I told him to use it 
![изображение](https://github.com/user-attachments/assets/d338ba32-8302-4907-86f0-d03962b0cb72)

We’ll wait for the result

**Comment by jwax33** [comment]
The text encoder thing may be a bug. I remember someone else reporting Swarm not respecting text encoder choices in Discord before.  That said, someone else said they ran each different T5 encoder and there is virtually no distinguishable difference in image output between any of them, for what that's worth.

models/unet was the original and now deprecated folder.  The "new" folder for it is the models/diffusion_models folder so it would be normal for you not to have the unet folder if you only recently installed SwarmUI.

**Comment by XZVB12** [comment]
Well, after the download I got this error:
```
[Info] t5xxl_enconly.safetensors download at 100.0%...
[Info] Downloading complete, continuing.
[Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI errored: {
"error": {
"type": "prompt_outputs_failed_validation",
"message": "Prompt outputs failed validation",
"details": "",
"extra_info": {}
},
"node_errors": {
"100": {
"errors": [
{
"type": "value_not_in_list",
"message": "Value not in list",
"details": "clip_name1: 't5xxl_enconly.safetensors' not in ['clip_g.safetensors', 'clip_l.safetensors', 'ratatoskrclip_l_V1.safetensors', 't5xxl_fp8_e4m3fn.safetensors']",
"extra_info": {
"input_name": "clip_name1",
"input_config": [
[
"clip_g.safetensors",
"clip_l.safetensors",
"ratatoskrclip_l_V1.safetensors",
"t5xxl_fp8_e4m3fn.safetensors"
],
{}
],
"received_value": "t5xxl_enconly.safetensors"
}
}
],
"dependent_outputs": [
"9"
],
"class_type": "DualCLIPLoader"
}
}
}
[Warning] [BackendHandler] backend #0 failed to load model flux1-dev-fp8.safetensors
[Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
[Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
```
So I had to create a symbolic link for t5xxl_enconly.safetensors in /AI/ComfyUI/models/clip/ that would start working, which is again strange. Swarm downloads files to its folders, but when generating it looks for them on comfyUI
After this, the generation really started.
Thank you for your answers/ patience.
I tried to replace t5xxl_enconly.safetensors with a symbolic reference to t5xxl_fp8_e4m3fn.safetensors , but it didn’t work I get an error:
`invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node SwarmClipTextEncodeAdvanced does not exist. ', 'details': "Node ID '#6'", 'extra_info': {}}` 
it seems to not want to work with fp8_e4m3fn version, although the version it is download has no problems
If you don’t need more information about the clip load I will mark the topic as resolved.
