### ISSUE TITLE
wildcard how to use in grid mode

### ISSUE THREAD

**Issue by Maelstrom2014** [mcmonkeyprojects/SwarmUI#270]
### Your question

Cant use it. I made a wildcard in wc tab, but cant understand how to use it in grid mode. Logic of interface in unintuitive.
on - off of "text" (on left top)  does not matter.

![wilodcards](https://github.com/user-attachments/assets/4c0b1ed7-6ac6-4363-b3a7-33a8ebd9d9c1)

ALSO i cant use wildcard  in "text" field on left top. Why?

**Comment by mcmonkey4eva** [comment]
wildcards are processed for the `prompt` input, whereas you have a custom input from a custom workflow, which does not currently process secondary behaviors like wildcards
