### ISSUE TITLE
Allow Model select in Presets

### ISSUE THREAD

**Issue by kostya12071** [mcmonkeyprojects/SwarmUI#273]
### Feature Idea

Currently almost all settings can be selectively configured as part of the Preset, except for the Model name.  It would be useful to be able to set the Model name as well.   This is especially useful when there are multiple versions of the model -- Dev.1 vs Schnell for example, where you might want to use Schnell for previews and Dev.1 for final rendering.  Without this option, user must manually switch models after enabling or disabling the Preset.

**Comment by SouthbayJay** [comment]
You can do it already. I’m not at my pc to take a screenshot but there's a checkbox to show advanced options

**Comment by SouthbayJay** [comment]
Ok so yeah down at the bottom you'll see two checkboxes to show a lot more options.. There's pretty much every setting you can possibly want in a preset... 

![image](https://github.com/user-attachments/assets/02d4f732-5140-4f6c-b5fc-fa52f61b57d6)

<img width="253" alt="{01F471BE-26B5-4352-BC52-A577113D3FCF}" src="https://github.com/user-attachments/assets/321e8b51-5fe8-46eb-83e6-0b0a3ffe4d53">
