### ISSUE TITLE
How can I get seed of interrupted picture?

### ISSUE THREAD

**Issue by Ilya87** [mcmonkeyprojects/SwarmUI#278]
### Your question

How can I get seed of interrupted picture generation, when seed was set to -1?

**Comment by mcmonkey4eva** [comment]
not the most convenient, but you can find it in Server->Logs, a lot of secondary info is included in the Debug logs output while generating

Im going to swap this issue to a _Feature Request_ for pre-emitting metadata over websocket generations to allow the frontend to show approximate metadata on incomplete generations (probably with a `generation incomplete` in `progress percent: x.x%` or something tack on)

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/user-attachments/assets/71afc4e6-0c1a-4aae-a92c-a53f8a7d38ac)

Added ^, with a little `preview_notice` tacked on, which goes away when gen is done.
If you interrupt it will remain.
