### ISSUE TITLE
comfyui won't work inside swarmUI

### ISSUE THREAD

**Issue by DeDe43ISR** [mcmonkeyprojects/SwarmUI#279]
### Your question

CmfyUI is loading fine but when I try to use it inside SwarmUI from the tab Comfy Workflow it just doesn't load.
it's show some part of Comfy but I can't load a workflow or do anything.
It worked just fine yesterday.
![Screenshot_2024_09_22-2](https://github.com/user-attachments/assets/0b483eb9-c51a-4334-81f8-3f9929dee5a6)

ComfyUI log :
![Screenshot_2024_09_22-3](https://github.com/user-attachments/assets/7b48a719-ff0c-4a62-a96a-d16e1de2d546)

ComfyUI :
![Screenshot_2024_09_22-4](https://github.com/user-attachments/assets/1438b679-6348-4141-98dc-dba17344ca9e)

### Logs

https://paste.denizenscript.com/View/126703

**Comment by mcmonkey4eva** [comment]
`Current git commit marked as date 2024-08-17 02:41:29`

Your swarm hasn't been updated in over a month, just go to Server->Update&Restart and it will likely resolve the issue
