### ISSUE TITLE
Memory Use/Leak with Image History

### ISSUE THREAD

**Issue by richardtallent** [mcmonkeyprojects/SwarmUI#286]
### Expected Behavior

Image History thumbnails and previews are sent to the browser but not stored in memory once they have been processed.

### Actual Behavior

In the latest version, there seems to be a memory leak or other long-term storage of photos from the folder where the Image History sits. My folder had several thousand past images in folders by day (~5GB of JPEG files). After the latest update, startup was noticeably slower and memory usage kept climbing until the .NET process crashed at around 40GB.

### Steps to Reproduce

Have a very large image history. Once I moved all of the old folders and left only folders from the past week, it's fine.

### Debug Logs

Alas, didn't capture anything before I moved the files and got it working again.

### Other

In my case, the folder where the images are stored is a mapped network drive on MacOS. So iterating folders and files can be a little slow. I don't think this was responsible for the runaway RAM use, but thought it was worth mentioning.

**Comment by mcmonkey4eva** [comment]
After both analysis of the relevant code and active testing (I flooded past 2000 images into history on a test instance of Swarm and spammed refresh button and all) + memory profiling (via yourkit snapshots), I can't find any sign of a memory leak related to image history handling.

Best guesses are (1) possibly the metadata database was corrupted in a weird way that didn't error but did spam memory? not sure, LiteDB usually just errors out if the file is corrupt. or of course (2) unrelated cause of the issue that's lost to time until you can replicate it again.

**Comment by mcmonkey4eva** [comment]
the Utilities->Reset All Metadata button does that automatically for you

**Comment by brendanhoar** [comment]
> the Utilities->Reset All Metadata button does that automatically for you

It does, but it also scans the 40k primary and secondary models on the system, so I only do that when I want to sync the metadata. :)

B
