### ISSUE TITLE
Segment only largest finding - very useful to inpaint main face only

### ISSUE THREAD

**Issue by FurkanGozukara** [mcmonkeyprojects/SwarmUI#287]
### Feature Idea

Currently I couldn't find a way to inpaint largest face only

It also doesn't sort them from largest to smallest - this would also work

So if you can tell me which files to modify to add this feature I can also try to make a pull request

But I would appreciate very much if you had added it

Use cases

`<segment:yolo-face_yolov9c.pt-largest,0.6,0.9>`

or

`<segment:yolo-face_yolov9c.pt-1,0.6,0.9>` - auto sorted by largest and first one inpainted

**Comment by FurkanGozukara** [comment]
> The actual impl has to be in the swarm yolo python node, but it also needs a new parameter added, probably just a _Segmentation Sort Order_ param under _Regional Prompting_ group to select between sort by left-right vs top-bottom vs largest-smallest

ok so i need to modify

src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra\SwarmYolo.py

and the other file name? full path please

**Comment by abaddouh** [comment]
`src/Text2Image/T2IParamTypes.cs` starting around line 612

**Comment by mcmonkey4eva** [comment]
and the workflow generator code

and there's a launch-windows-dev script to apply updates. You do need a restart that's not avoidable.

**Comment by FurkanGozukara** [comment]
> and the workflow generator code
> 
> and there's a launch-windows-dev script to apply updates. You do need a restart that's not avoidable.

thank you from which file it will take the input?

likle

`<segment:yolo-face_yolov9c.pt,0.6,0.9,largest>`

or

`<segment:yolo-face_yolov9c.pt-largest,0.6,0.9>`

it looks pretty easy to implement

**Comment by FurkanGozukara** [comment]
thank you so much @aimerib  

https://github.com/mcmonkeyprojects/SwarmUI/pull/289

**Comment by aimerib** [comment]
@FurkanGozukara you're welcome! I chose to go the path mcmonkey suggested, using the params to control sorting instead of the prompt syntax. The yolo prompt syntax is already pretty heavy, and keeping it from getting more complex would be nice. The params accomplish the same thing, I think. Of note, if you use sorting, it will only return the first match after the sort. There's some room here for it to not do that.
