### ISSUE TITLE
remote Swarm-API-Backend mistakenly adding internal parameters for the backend routing that end up visible in the UI

### ISSUE THREAD

**Issue by sguart** [mcmonkeyprojects/SwarmUI#288]
### Expected Behavior

Configured a Remote SwarmUI API Backend.

Generate multiple images so that the remote backend is utilized.

Disable the remote backend.

Generate a image.

Check previously generated images, there should be no changes to the parameters associated with the image.

Enable the remote backend again

Generate more images which utilize the remote backend.

Check the generated images, the save parameters associated with those images shouldn't have "Exact Backend" and "DoNotSave" added to them, if the users had not done so themselves.

### Actual Behavior

In the expected behavior above,

once the remote back end is disabled and then image is generated using the local backend.

some of previously generated images' saved parameters will be updated to include "Exact Backend ID" and "DoNotSave"

after re-enable the remote backend and then generate image, the image that is send to remote backend will have its saved parameters appended with "Exact Backend ID" and "DoNotSave" parameters.

### Steps to Reproduce

Configure a remote SwarmUI API backend
Generate images so it sends to the remote backend
Disable remote backend
Generate a image
Check previously generated images, some of them will now have additional saved parameters, "Exact Backend ID" and "DoNotSave"
Enable remote backend
Generate images so it send to the remote backend
The image that was send to the remote backend, its save parameters will include "Exact Backend ID" and "DoNotSave" parameters

### Debug Logs

There is no log as this doesn't result in any error in the log.
Users have to inspect the generated images to see the saved parameters list has changed without any interaction.

### Other

https://github.com/mcmonkeyprojects/SwarmUI/discussions/284 has more details

**Comment by Thedougler** [comment]
I have this bug too quite a slowdown to workflow

**Comment by mcmonkey4eva** [comment]
Is this only when interrupting generations? or... how are you triggering this?

I did a test and it doesn't normally happen, but when interrupting a generation it does have the stray values

**Comment by mcmonkey4eva** [comment]
above commit excludes internally used params from preview metadata, which solves at least the case I was able to replicate. Please let me know if there's other cases that can trigger those showing up

**Comment by sguart** [comment]
thank you for the fix, however it doesn't resolve the issue completely.

after more detail testing, the behavior is now with the backend disable functionality.
here are the steps:
1. configured a remote swarmui api backend
2. generate 3 images (image 1 is local, image 2 is remote, image 3 is local) (however, remote's hardware is slow.)
3. 3 images generated, the order is (image 1 and image 2 are locally generated and image 3 is done by remote, due to remote hardware is slow.)
4. at this moment, all three images don't have "exact backend" and "donotsave" in the saved parameters list.
5. go to backend tab and disable remote backend, wait for save backend message.
6. look at previously generated images, image 2's save parameters now have "exact backend:0" and "donotsave:true" appended to its saved parameters list (image 2 is the second local generated image)

so, the issue remains with the enable/disable backend toggle.  when the user disabled the remote backend, the UI retroactively alter the save parameters of previously generated image.

before your fix, there will be two images that have the saved parameters list updated with "exact backend:0" and "donotsave:true"

**Comment by mcmonkey4eva** [comment]
That. doesn't even make any sense. That's not even how any of the relevant moving parts function at all.

Make sure your remote backend got updated to the new commit, not just your local one
