### ISSUE TITLE
Unusable When You Have MANY Loras Locally

### ISSUE THREAD

**Issue by Ameno-Sagiri** [mcmonkeyprojects/SwarmUI#291]
### Expected Behavior

The UI Is usable 

### Actual Behavior

The UI runs at extremely low framerates and frequently locks up, sometimes to the point that the entire tab dies (Chrome, Degoogled Chromium, Vivaldi, Firefox, makes no difference). Sometimes I will try to type in a prompt and have to wait a full 10+ seconds before what I typed actually appears, etc, or before it lets me click on anything, or before my click from 20 seconds ago finally has an effect. It's like working with a very slow slideshow. I have a great deal of patience, and I can firmly say this is in an unusable state for how trial-and-error AI is.

### Steps to Reproduce

Have 2183 loras installed locally (Or seemingly over 2000?)

### Debug Logs

https://paste.denizenscript.com/View/126818

### Other

I've used SwarmUI for almost 2 months now, and had nearly no issues with it (other than some metadata related issues with loras). I'm actually not specifically sure when this problem started, but it happened somewhere between having 1900-2200 loras - nothing I do in the UI will alleviate the issues (other than if I search for something in the lora tab that has very few results, though the lag still somewhat persists in some of the menus, I'm assuming it's because it's not trying to load up the entire compendium of loras all at once when I filter them?). I tried all the lora views (cards/thumbnails/etc) and that seemed to have no impact. I did notice it slowly got laggier, and after going on a hunt for more loras over the last week, it is now unusable. 

Unrelated, but I started using SwarmUI after InvokeAI because Invoke became unusable for the very same reason... just that took far less loras before I had problems with it. I get this is a very... unique and possibly niche issue, but it's still a problem.

**Comment by brendanhoar** [comment]
I'm in the same pickle, @mcmonkey4eva says I should have fewer models, lol. Don't have a fix, just some suggestions.

One thing to try might be to use the Reset All Metadata button. Sometimes there's some problems with the cached metadata in the directory/central ldb files.

Also, if you have remote/slow storage, you can try enabling the DoBackendDataCache option in the Server/Server Configuration page - it may or may not help.

Lastly, I've mostly given up on the search capability of the gui picker, instead I use the <lora: and <embed: invocations almost exclusively. The text search on those works pretty well.

**Comment by Ameno-Sagiri** [comment]
> I'm in the same pickle, @mcmonkey4eva says I should have fewer models, lol. Don't have a fix, just some suggestions.
> 
> One thing to try might be to use the Reset All Metadata button. Sometimes there's some problems with the cached metadata in the directory/central ldb files.
> 
> Also, if you have remote/slow storage, you can try enabling the DoBackendDataCache option in the Server/Server Configuration page - it may or may not help.
> 
> Lastly, I've mostly given up on the search capability of the gui picker, instead I use the <lora: and <embed: invocations almost exclusively. The text search on those works pretty well.

Thanks for the reply.

In regards to the storage speed, I do have every model on a Samsung Pro 980 NVME drive, so speed technically shouldn't be the issue when it comes to filesystem. An alternative I found that may work for you is I have deployed SwarmUI with Stability Matrix which has its own built in Lora browser that's more robust than the one in SwarmUI, and it's just an extra step of sorting and clicking.

I suspected an official answer (not yours) I might have gotten would be "have less models", but I would rather not consider that a valid solution from someone in development, and find that to be a bit of a cop-out answer to ignore a problem rather than fix it, just because it doesn't directly affect most people and isn't on a priority list. I feel that if it can be done, it should be made to work the way it's intended.

I just wanted to point out that Stability Matrix's lora browser is functional still and seems to handle any amount of local models I have, but I do realize that's more of a standalone desktop application and is not running through a webUI, so there must be some limitations I am just not aware of as I do not program, though I've been around programmers a lot of my life, enough to know some of the problems they may face, it's not alien to me.

I have attempted your two solutions. I am not quite sure at the moment if it was a permanent fix, but toggling DoBackendDataCache has possibly made a difference, it's not lagging all that badly even after loading up a checkpoint and some loras and generating a few things. Will update if it goes back to heavy lag again.

**Comment by mcmonkey4eva** [comment]
Somewhat related to the topic, albeit not to OP's specific issue, commit https://github.com/mcmonkeyprojects/SwarmUI/commit/7bb98bcb63ea935f4b2a3151827cd6dc8d229aa3 makes changing selections around in the UI much faster to update (previously when selecting models on a long model list it'd noticeably freeze for a second before updating, now it's effectively instant, minus a 10ms deduplication delay)
