### ISSUE TITLE
Yolo masking face vs default segment face masking has huge huge difference

### ISSUE THREAD

**Issue by FurkanGozukara** [mcmonkeyprojects/SwarmUI#292]
There can be masked are difference but where is coming this inpainting difference? Same model same seed

First image default face masking

`a photo of ohwx man wearing an amazing white suit and a red shirt, wearing eyeglasses, wearing a black tie and has red hair color and very long thick blue beard and he is in a luxury coffee shop in paris<segment:face-1,0.6,0.5>photo of ohwx man with very long thick blue beard`

![image](https://github.com/user-attachments/assets/360a44c6-0b08-4be1-b58a-1ab4f499e24b)

second image is yolo masking

`a photo of ohwx man wearing an amazing white suit and a red shirt, wearing eyeglasses, wearing a black tie and has red hair color and very long thick blue beard and he is in a luxury coffee shop in paris<segment:face-1,0.6,0.5>photo of ohwx man with very long thick blue beard`

![image](https://github.com/user-attachments/assets/f55b594f-5632-4eb8-8f97-481b37d2f888)

**Comment by mcmonkey4eva** [comment]
different masks yield different results lol. You can fiddle the advanced settings under regional prompting to improve issues from if the segment model yielded weak results, particularly lowering the value of `Segment Threshold Max` might help

**Comment by FurkanGozukara** [comment]
> different masks yield different results lol. You can fiddle the advanced settings under regional prompting to improve issues from if the segment model yielded weak results, particularly lowering the value of `Segment Threshold Max` might help

isnt mask only position of pixels or i am understanding wrong?

**Comment by mcmonkey4eva** [comment]
Mask is the pixels of the strength per each pixel. White is fully masked, black is fully unmasked, and there's a whole grayscale range in between for partial masks.
Setting the *max* value compresses that range - eg if you set it to `0.5`, then any partial mask that's at least 0.5 (middle gray) is treated as a full match (pure white).

A lot of "my results look ugly with automasking" complaints come down to unexpectedly low-strength matches leading to very small changes to the source image

**Comment by FurkanGozukara** [comment]
> Mask is the pixels of the strength per each pixel. White is fully masked, black is fully unmasked, and there's a whole grayscale range in between for partial masks. Setting the _max_ value compresses that range - eg if you set it to `0.5`, then any partial mask that's at least 0.5 (middle gray) is treated as a full match (pure white).
> 
> A lot of "my results look ugly with automasking" complaints come down to unexpectedly low-strength matches leading to very small changes to the source image

Thank you so much for answer

So

<segment:face-1,0.6,0.5>

Vs

<segment:face-1,0.6,0.1>

That 0.1 will change more right have stronger, will be more white stronger masked?

**Comment by FurkanGozukara** [comment]
> The value inside the prompt syntax is the _minimum_.
> 
> Maximum is controlled by the max parameter as I mentioned earlier ![image](https://private-user-images.githubusercontent.com/4000772/372257184-ba8508b6-cee8-40f8-8f27-da2cfc44fd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MzczNDQsIm5iZiI6MTcyNzczNzA0NCwicGF0aCI6Ii80MDAwNzcyLzM3MjI1NzE4NC1iYTg1MDhiNi1jZWU4LTQwZjgtOGYyNy1kYTJjZmM0NGZkNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMjI1NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY1NThiYjIwOTc1YmE0ZDY2ZDliZDUzMmYzYjU3MmFkYzZlMzk1ZmViMzNiYWE1OWNhMGFiYzJmZDE1N2VmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Hkqoazq9GTrVGvcW7bpTSMvCxhZ8sa1vkfhP2SXLSt0)

thank you so much so we need to reduce segment threshold max - by the way it is impossible to understand what it does from description alone :D
