### ISSUE TITLE
Yaml wildcards

### ISSUE THREAD

**Issue by faustoserone** [mcmonkeyprojects/SwarmUI#298]
### Feature Idea

Hi, I wanted to know if the implementation of yaml files in wildards is planned. Thanks.

**Comment by mcmonkey4eva** [comment]
Please post feature requests for things you want to be able to do, not for systems to copypaste from other UIs. I don't think the yaml file format used by that auto extension is particularly good at solving any problems that Swarm doesn't already handle well.

**Comment by faustoserone** [comment]
Sorry, I'm new to Swarm Ui and thought I'd ask something useful. Sorry again. Thanks

**Comment by SouthbayJay** [comment]
> Sorry, I'm new to Swarm Ui and thought I'd ask something useful. Sorry again. Thanks

Come over to the Discord server, we discussed this a couple weeks ago and have a pretty good solution. Here's an invite link, when you get there ping me "SouthbayJay" and I can help you converting the yaml files. 

https://discord.gg/nyNkHN9N

**Comment by faustoserone** [comment]
Thanks! But I'm new on Discord too. How can I ping you? Be patient, I'm very old man :(

**Comment by SouthbayJay** [comment]
No worries, I'm old also.. 51 to be exact lol.. Join the discord server with the link I posted, find your way to the "open-help-chat" channel, link below) and then you can use @SouthbayJay to ping me. That will notify that my name was mentioned and I'll know where to look.. I'm heading off to bed shortly but I will be back on in the morning, currently 11pm here on the west coast.. 

https://discord.com/channels/1243166023859961988/1243167879147421719

**Comment by faustoserone** [comment]
Many Thanks!
