### ISSUE TITLE
Multi-user setup

### ISSUE THREAD

**Issue by matbee-eth** [mcmonkeyprojects/SwarmUI#3]
Is there a rough guide on how to enable multi user support?
I see references to user id's, and X-SWARM-USER_ID headers and a `--user_id` flag.

Do I simply need to expose my comfy service and launch the SwarmUI with `--user_id whatever-user-id`, or do I simply just set a "master" swarm as a backend (or both)?

**Comment by mcmonkey4eva** [comment]
The multi-user engine is still a work-in-progress.

You can indeed launch as a different user with `--user_id`, or present a frontend proxy that applies user IDs with that header.

In the future there will be a proper interface to allow users to select accounts / register / admin configure accounts / etc., that's just not built yet

**Comment by mcmonkey4eva** [comment]
Initial multi-user engine functionality is now available, check the Discord  https://discord.gg/q2y38cqjNw  's `#development` channel for info
