### ISSUE TITLE
NF4 flux model generation error

### ISSUE THREAD

**Issue by Ilya87** [mcmonkeyprojects/SwarmUI#300]
### Expected Behavior

SwarmUI version 70b920af216105cc04748912a1cd695d7d526c1c
Checkpoint fluxunchainedNF4_unchained11NF4Unet
photorealism, cat smoking cigar in cap, white background
Image generated, as it was in August, 30

### Actual Behavior

Error

### Steps to Reproduce

Remote connection
fluxunchainedNF4_unchained11NF4Unet checkpoint
vae - ae, clip_l, and t5xxl_fp8_e4m3fn seleted in Advanced model addition tab.

### Debug Logs

https://paste.denizenscript.com/View/127010

**Comment by mcmonkey4eva** [comment]
Comfy instance crashed, probably from lack of VRAM/RAM

So, main thing is, add a decently sized pagefile on that machine

Secondarily, use GGUF-Q4 instead of NF4. GGUF is much stabler in general

**Comment by mcmonkey4eva** [comment]
cuda out of memory indicates VRAM loading failures, usually code errors or just impossible requests. out of true total memory is indicated by rapid hard crashing. Adding a pagefile increases your maximum memory capacity (by borrowing a bit from datadrive, very slow but works) and can prevent the hard crash (though if you're relying too much on pagefile you'll feel it as entire system slowing down / chugging while you generate).

Again: add a pagefile. And use GGUF formatted models whenever you can.

**Comment by Ilya87** [comment]
Thank you! +2 Gb to pagefile solved the problem.
