### ISSUE TITLE
Web page grid generation: add checkbox option "Do not generate html for SKIP: items" and associated capability

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#304]
### Feature Idea

Sometimes it becomes clear after the fact (during grid generation) that not only is it a waste of time to include a particular parameter value in the grid generation of image but it's a waste of time displaying it within the grid as well (whether or not some/all images have been generated for that particular parameter value).

Unfortunately, removing values can have side effects if any values beyond that value have generated.

I would not want SKIP: to, _by default_, not _display_ associated parameter value results. 

However it would be nice to have an option at the top of generation that would skip generating the html for those values, which would remove useless images from the grid page. One could toggle it on and off as needed, even if all targeted images are generated, to recreate the page with and without values that are currently tagged with SKIP:.

### Other

N/A

**Comment by mcmonkey4eva** [comment]
Removing a value shouldn't have side effects. If you want something entirely gone, remove it. Skip is specifically for when you don't want it completely gone
