### ISSUE TITLE
<random: doesn't work the same in flux and sdxl

### ISSUE THREAD

**Issue by laurentopia** [mcmonkeyprojects/SwarmUI#310]
### Expected Behavior

<random: colorful, muted colors, almost monochromatic> <random: whimsical, realistic, cartoony>
would output permutations

### Actual Behavior

it always outputs almost monochromatic realistic on every generation

### Steps to Reproduce

set images to 100
prompt:
dog <random: colorful, muted colors, almost monochromatic> <random: whimsical, realistic, cartoony>
select flux and generate = all images have a random permutation of these terms
select sdxl and generate = all images have the same prompt

### Debug Logs

https://paste.denizenscript.com/View/127101

**Comment by mcmonkey4eva** [comment]
Has nothing to do with model class. See same prior issue here https://github.com/mcmonkeyprojects/SwarmUI/issues/275#issuecomment-2362549830

**Comment by laurentopia** [comment]
this is well hidden
![image](https://github.com/user-attachments/assets/89b9a3b4-8727-4ff6-9290-e750000e2b1c)
this should be moved from internal to core
