### ISSUE TITLE
Comfy backend can't launch after i used the update function; clean installs now have same problem

### ISSUE THREAD

**Issue by gbgh2024** [mcmonkeyprojects/SwarmUI#314]
### Your question

About a week ago I hit 'update' on a perfectly working SwarmUI install.
Since then it's been unable to launch the comfy backend, debug logs linked below but the warnings are:

15:22:12.177 [Init] Self-Start ComfyUI-0 on port 7822 is loading...
15:22:37.965 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
15:22:37.965 [Warning] [ComfyUI-0/STDERR]   File "D:\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 229, in <module>
15:22:37.965 [Warning] [ComfyUI-0/STDERR]     load_extra_path_config(config_path)
15:22:37.966 [Warning] [ComfyUI-0/STDERR]   File "D:\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 194, in load_extra_path_config
15:22:37.966 [Warning] [ComfyUI-0/STDERR]     for y in conf[x].split("\n"):
15:22:37.966 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^
15:22:37.967 [Warning] [ComfyUI-0/STDERR] AttributeError: 'bool' object has no attribute 'split'

As stated in the title, I now have the same problem on clean installs. Presume this is me being clueless and my new installs aren't actually clean. As far as I know, I've removed & reinstalled python, git, dotnet, and then swarmUI itself.

Any ideas?
Sorry for taking up your time and thanks for all the hard work.

### Logs

https://paste.denizenscript.com/View/127133

**Comment by Princessity** [comment]
I had a similar issue when I decided to update a minute ago. I was able to sorta fix it by going to my ComyUI/update and manually updating from there. I suspect maybe the SwarmUI update failed to also update the backend?

**Comment by gbgh2024** [comment]
That did indeed fix it. Thank you!!
