### ISSUE TITLE
Feature  contribution - basic sequence handling in prompt

### ISSUE THREAD

**Issue by barelyuseless** [mcmonkeyprojects/SwarmUI#316]
### Feature Idea

I'd like to add simple sequence handling to the prompt parser, to allow for predictable transition through a list of options generation to generation.

At the moment I've got code working locally to support two new prompt keywords:

`seq`: uses the same separator syntax as `random`, but progresses through the items in the list in order, looping back to the start when the end is reached.
eg `<seq:first thing|second thing|third thing>`

`wildcardseq`: the same idea but applied to the contents of a wildcard file - it will be iterated through in order, with back-to-start looping when the end is reached.
eg `<wildcardseq:myWildcardName>`

It's not a complex implementation, like the behaviour of combinatorial selection in some other prompt engines, but it does give a basic in-order walk of a list of things, which is what I wanted to use. If this would be more broadly useful, I'm happy to open a PR, just wanted to check in here first as per `CONTRIBUTING.md`.

**Comment by mcmonkey4eva** [comment]
Tools -> Grid Generator providers a much nicer interface for this than prompt syntax

**Comment by barelyuseless** [comment]
Perhaps I missed it in the documentation, but is there a way to get the Grid Generator to loop through entries in a file in order? Or to combine several such loops?
