### ISSUE TITLE
Trigger Phrase Prompt Syntax

### ISSUE THREAD

**Issue by re3me** [mcmonkeyprojects/SwarmUI#317]
### Feature Idea

Utilizing the prompt syntax can be powerful and helps keep your prompt and work organized. I really like how SwarmUI has approached this thus far. I really like the idea of auto filling in trigger phrases for LoRA's. However, the feature does need some added fidelity for prompt control. I suggest that the syntax could be something along line of <trigger:x> where x corresponds to the LoRA ID that is used when applying weights.

**Comment by mcmonkey4eva** [comment]
At the point where you specifying which lora's trigger to use, what's the value over just copy/pasting that lora's trigger phrase in manually?

**Comment by brendanhoar** [comment]
I was also thinking along the lines of <trigger:y> where y represents the number of words to extract from the trigger area, as some metadata has stuff like "charname, outfit type #1; charname, outfit type #2; ..."

This type of syntax is mostly for grids when comparing models/submodels. When working on specific outputs, yeah, it's better to just capture the trigger words and handle them manually.

**Comment by re3me** [comment]
> At the point where you specifying which lora's trigger to use, what's the value over just copy/pasting that lora's trigger phrase in manually?

Speed and ease is the main thing to gain here.

**Comment by mcmonkey4eva** [comment]
> I was also thinking along the lines of trigger:y where y represents the number of words to extract from the trigger area, as some metadata has stuff like "charname, outfit type 1; charname, outfit type 2; ..."

Edit the metadata to have the trigger phrase be whatever you expect the actual trigger phrase to be, and put the rest under Usage Hint or Description
