### ISSUE TITLE
Generation tab -> add [Clear] [ X ] button for "filter parameters"

### ISSUE THREAD

**Issue by senelya** [mcmonkeyprojects/SwarmUI#320]
### Feature Idea

it is very handy to search needed parameters but it is very long to select and delete text that is already there. So [ X ] button would greatly improve the usability of this field. 
![image](https://github.com/user-attachments/assets/97691938-a8a1-41b4-b0db-79113bc00bca)

**Comment by mcmonkey4eva** [comment]
added thanks to @Jelosus2 https://github.com/mcmonkeyprojects/SwarmUI/pull/453
