### ISSUE TITLE
Grid Generate Forever

### ISSUE THREAD

**Issue by PharahLong** [mcmonkeyprojects/SwarmUI#321]
### Feature Idea

Hi, first I'd like to express my thanks for your work on this project. The feature I'd like to request is: 'Generate Grid Forever '. Sometimes when my computer is free, I can leave it running to test LoRa without having to estimate how long until the job is done

**Comment by mcmonkey4eva** [comment]
Huh?

**Comment by mcmonkey4eva** [comment]
You can cancel a generation at any time, and if you interrupt a named webpage format grid, you can simply reuse it later at any time
