### ISSUE TITLE
First time installing, git clone but unable to build on Windows 11

### ISSUE THREAD

**Issue by vidu3k333** [mcmonkeyprojects/SwarmUI#326]
### Your question

I tried to install .NET 8.0.10, then it gave me this error:
![image](https://github.com/user-attachments/assets/324f8e99-2745-4fdf-8838-3107bde16809)
tried to search for dotnet-host-8.0.8-win-x64.msi to no avail, I installed 8.0.8 and it worked, but when I tried to run launch-windows.bat it gives:
`The system cannot find the path specified.
""
""
"WARNING: You did a git pull without building. Will now build for you..."
""
""
The system cannot find the path specified.
The system cannot find the file specified.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
Press any key to continue . . .`

and when I tried install-windows.bat I got the log bellow.

### Logs

`Found an existing package already installed. Trying to upgrade the installed package...
Found Microsoft .NET SDK 8.0 [Microsoft.DotNet.SDK.8] Version 8.0.403
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Admin\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.DotNet.SDK.8.8.0.403-2024-10-15-08-03-48.258.log
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
Cloning into 'SwarmUI'...
remote: Enumerating objects: 20667, done.
remote: Counting objects: 100% (3399/3399), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 20667 (delta 3275), reused 3306 (delta 3222), pack-reused 17268 (from 1)
Receiving objects: 100% (20667/20667), 11.88 MiB | 13.00 MiB/s, done.
Resolving deltas: 100% (16399/16399), done.
The system cannot find the path specified.
""
""
"WARNING: You did a git pull without building. Will now build for you..."
""
""
The system cannot find the path specified.
The system cannot find the file specified.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
Press any key to continue . . .`

**Comment by mcmonkey4eva** [comment]
From https://dotnet.microsoft.com/en-us/download/dotnet/8.0 
Grab this:
![image](https://github.com/user-attachments/assets/09127c95-a877-4e5d-b949-3274880d836a)

And install, and restart, and try again

**Comment by vidu3k333** [comment]
i already installed it as stated above, so i just uninstalled and reinstall. now after reinstalling i got this:

`The system cannot find the path specified.
""
""
"WARNING: You did a git pull without building. Will now build for you..."
""
""
The system cannot find the path specified.
The system cannot find the file specified.
error: The source specified has already been added to the list of available package sources. Provide a unique source.
  Determining projects to restore...
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
  Failed to restore E:\SwarmUI\src\SwarmUI.csproj (in 86 ms).

Build FAILED.

E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
E:\SwarmUI\src\SwarmUI.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exist.
    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:00.60
The system cannot find the path specified.
The system cannot find the path specified.
Press any key to continue . . .`

after this i created the 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' folder and it worked, so i'm just leave this here in case anyone else has problems
