### ISSUE TITLE
Embedding sanity check - needs adjustment

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#330]
### Expected Behavior

Warning message tells you how to fix it.

### Actual Behavior

Warning message can be misleading.

### Steps to Reproduce

Put an embedding in the embedding subtree in a folder, but include a space in the name of the subfolder.
Start up SwarmUI.

Warning return is similar to:
> ...__to org/text_vintagemap_f.pt' contains spaces in its name, which will cause it to not parse properly on the backend. Please rename the file.

The solution given is to rename the file, however, to pass the check as it is written, it is the subdirectory that needs to be renamed.

### Debug Logs

N/A

**Comment by mcmonkey4eva** [comment]
The subdirectory is part of the filename, so it's not wrong, but I'll clarify it
