### ISSUE TITLE
Workflows Saved Location (Simple Tab)

### ISSUE THREAD

**Issue by boricuapab** [mcmonkeyprojects/SwarmUI#333]
### Your question

Where do the workflows that we save to use in the simple tab get saved to in Windows?

**Comment by mcmonkey4eva** [comment]
The saved workflows are not in comfy's native format, they are in a Swarm-specific format to contain all the additional metadata. If you need to transfer them or something, they're in `(Swarm)/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows`
