### ISSUE TITLE
SwarmUI Node Pack Installing Into Standalone Comfy

### ISSUE THREAD

**Issue by boricuapab** [mcmonkeyprojects/SwarmUI#334]
### Your question

I was wondering if the SwarmUI node pack is able to be installed in a separate standalone comfy, 

Primarily the swarm input nodes so that I can work on making workflows specifically to be ran in the swarm ui.

I searched manager for them but couldn't find them.

**Comment by mcmonkey4eva** [comment]
They're not in manager but you can easily add your swarm path to any comfy install via the extra model paths file, check your `(SwarmUI)/Data/comfy-auto-model.yaml` for an autogenerated valid one that links your swarm models and swarm's nodes.
