### ISSUE TITLE
Comfy Math SDXL Resolution Dropdown node

### ISSUE THREAD

**Issue by boricuapab** [mcmonkeyprojects/SwarmUI#335]
### Your question

I was looking for a way to expose the comfy math sdxl resolutions drop down selection into the Generation/Simple tabs using the swarm input dropdown node, but am not sure how to set this up.

**Comment by mcmonkey4eva** [comment]
Er... what node?

Generally what you do for dropdowns is just convert Widget to Input, connect a SwarmInputDropdown, and empty out the values field (if the dropdown values are empty, it will autopopulate based on what you connect it to). Note that there's two outputs from SwarmInputDropdown, the magic empty one is able to connect anywhere when the normal one won't connect.
