### ISSUE TITLE
SwarmUI can't use alternate paths to models, lora etc.

### ISSUE THREAD

**Issue by NPDX909** [mcmonkeyprojects/SwarmUI#34]
![3](https://github.com/mcmonkeyprojects/SwarmUI/assets/173012089/b8bde4e9-2de7-4300-8aaa-8182cf42059c)
### Your question

I set the paths up in the Server Configuration tab. I reloaded the server. ComfyUI backend seemed to add the paths during launch (?)  (See images)

No models found, no loras found, etc. What's happening

![1](https://github.com/mcmonkeyprojects/SwarmUI/assets/173012089/2e55e353-e864-41c6-b936-299b4ab3ca4b)
![2](https://github.com/mcmonkeyprojects/SwarmUI/assets/173012089/62728049-2150-4147-aa32-9dbedd6b8e19)
01:55:51.758 [Init] === SwarmUI v0.9.0.1 Starting at 2024-06-28 01:55:51 ===
01:55:51.796 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
01:55:51.806 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
01:55:51.806 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
01:55:51.807 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
01:55:51.808 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
01:55:51.808 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
01:55:51.843 [Init] Parsing command line...
01:55:51.845 [Init] Loading settings file...
01:55:51.870 [Init] Re-saving settings file...
01:55:51.890 [Init] Applying command line settings...
01:55:51.903 [Debug] [Load Time] Initial settings load took 0.14s (0.14s from start)
01:55:51.916 [Debug] [Load Time] Extension PreInit took 0.02s (0.16s from start)
01:55:51.917 [Init] Prepping options...
01:55:52.008 [Debug] [Load Time] Prep Objects took 0.09s (0.25s from start)
01:55:52.009 [Debug] [Load Time] Web PreInit took 0s (0.25s from start)
01:55:52.012 [Init] Current git commit marked as date 2024-06-27 20:09:06
01:55:52.016 [Debug] [Load Time] Extensions Init took 0.02s (0.27s from start)
01:55:52.017 [Debug] [Load Time] Prep Utils took 0s (0.27s from start)
01:55:52.032 [Debug] Local version is 0.9.0.1, remote version is 0.6.4.0, relative is 1
01:55:52.033 [Init] Swarm is up to date! Version 0.9.0.1 is the latest.
01:55:52.050 [Debug] [Load Time] Languages load took 0.03s (0.3s from start)
01:55:52.051 [Init] Loading models list...
01:55:52.071 [Init] CPU Cores: 16 | RAM: 31.92 GiB total, 20.15 GiB available
01:55:52.071 [Init] GPU 0: NVIDIA GeForce RTX 2080 | Temp 35C | Util 26% GPU, 16% Memory | VRAM 8.00 GiB total, 7.57 GiB free, 249.00 MiB used
01:55:52.406 [Debug] [Load Time] Model listing took 0.36s (0.66s from start)
01:55:52.407 [Init] Loading backends...
01:55:52.408 [Init] Loading backends from file...
01:55:52.416 [Debug] [Load Time] Backends took 0s (0.66s from start)
01:55:52.416 [Init] Prepping API...
01:55:52.416 [Init] Initializing backend #0 - ComfyUI Self-Starting...
01:55:52.417 [Init] Backend request handler loop ready...
01:55:52.418 [Debug] [Load Time] API took 0s (0.66s from start)
01:55:52.419 [Init] Prepping webserver...
01:55:52.450 [Debug] [Load Time] [Web] WebApp builder prep took 0.02s (0.02s from start)
01:55:52.491 [Debug] [Load Time] [Web] WebApp build took 0.05s (0.06s from start)
01:55:52.493 [Debug] [Load Time] [Web] exception handler took 0s (0.06s from start)
01:55:52.494 [Debug] [Load Time] [Web] StartStop handler took 0s (0.06s from start)
01:55:52.495 [Debug] [Load Time] [Web] static files took 0s (0.06s from start)
01:55:52.549 [Debug] [Load Time] [Web] core use calls took 0.06s (0.13s from start)
01:55:52.555 [Debug] [Load Time] [Web] core maps took 0s (0.13s from start)
01:55:52.556 [Init] Scan for web extensions...
01:55:52.559 [Debug] [Load Time] [Web] end took 0s (0.13s from start)
01:55:52.559 [Debug] [Load Time] Web prep took 0.16s (0.81s from start)
01:55:52.560 [Init] Readying extensions for launch...
01:55:52.561 [Debug] [Load Time] Extensions pre-launch took 0s (0.81s from start)
01:55:52.561 [Init] Launching server...
01:55:52.562 [Init] Starting webserver on http://*:7801
01:55:52.604 [Debug] [Load Time] Web launch took 0.03s (0.84s from start)
01:55:52.605 [Init] Program is running.
01:55:53.111 [Init] Launch web browser...
01:55:53.354 [Debug] [comfy node pull (ComfyUI-SAI_API)/STDOUT] Already up to date.
01:55:53.360 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.
01:55:53.361 [Debug] Status of comfy node pull (ComfyUI-SAI_API) after process end is RUNNING
01:55:53.376 [Debug] [comfy node pull (sd-dynamic-thresholding)/STDOUT] Already up to date.
01:55:53.386 [Debug] Status of comfy node pull (sd-dynamic-thresholding) after process end is RUNNING
01:55:53.387 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.
01:55:54.194 [Debug] [comfy node pull (ComfyUI-SAI_API)/STDOUT] Already up to date.
01:55:54.202 [Debug] Status of comfy node pull (ComfyUI-SAI_API) after process end is RUNNING
01:55:54.204 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.
01:55:54.922 [Info] Creating new admin session 'local' for ::1
01:55:55.339 [Debug] Request for Stable-Diffusion model OfficialStableDiffusion/sd_xl_base_1.0 rejected as not found.
01:55:55.890 [Debug] Request for Stable-Diffusion model OfficialStableDiffusion/sd_xl_base_1.0 rejected as not found.
01:55:58.223 [Debug] [ComfyUI (Git Pull)/STDOUT] Already up to date.
01:55:58.229 [Debug] Status of ComfyUI (Git Pull) after process end is RUNNING
01:55:58.230 [Info] Self-Start ComfyUI (Git Pull) exited properly.
01:55:59.207 [Debug] [comfy node pull (sd-dynamic-thresholding)/STDOUT] Already up to date.
01:55:59.213 [Debug] Status of comfy node pull (sd-dynamic-thresholding) after process end is RUNNING
01:55:59.214 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.
01:55:59.216 [Debug] Requested generic launch of dlbackend/comfy/ComfyUI/main.py on GPU 0 from ComfyUI-0
01:55:59.221 [Debug] (ComfyUI-0 launch) Adding path D:\SwarmUI\dlbackend\comfy\python_embeded
01:55:59.221 [Debug] (ComfyUI-0 launch) Will use python: D:\SwarmUI\dlbackend\comfy\python_embeded\python.exe
01:55:59.225 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
01:56:01.134 [Debug] [ComfyUI-0/STDERR] Total VRAM 8192 MB, total RAM 32684 MB
01:56:01.135 [Debug] [ComfyUI-0/STDERR] pytorch version: 2.3.1+cu121
01:56:01.144 [Debug] [ComfyUI-0/STDERR] Set vram state to: NORMAL_VRAM
01:56:01.147 [Debug] [ComfyUI-0/STDERR] Device: cuda:0 NVIDIA GeForce RTX 2080 : cudaMallocAsync
01:56:02.105 [Debug] [ComfyUI-0/STDERR] Using pytorch cross attention
01:56:03.147 [Debug] [ComfyUI-0/STDERR] Adding extra search path checkpoints D:\A1111\stable-diffusion-webui\Stable-Diffusion
01:56:03.149 [Debug] [ComfyUI-0/STDERR] Adding extra search path vae D:\A1111\stable-diffusion-webui\VAE
01:56:03.149 [Debug] [ComfyUI-0/STDERR] Adding extra search path vae D:\A1111\stable-diffusion-webui\Models\VAE
01:56:03.150 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras D:\A1111\stable-diffusion-webui\Lora
01:56:03.150 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras D:\A1111\stable-diffusion-webui\Models\Lora
01:56:03.151 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras D:\A1111\stable-diffusion-webui\Models\LyCORIS
01:56:03.152 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\Models\ESRGAN
01:56:03.152 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\Models\RealESRGAN
01:56:03.153 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\Models\SwinIR
01:56:03.153 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\Models\upscale-models
01:56:03.154 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\Models\upscale_models
01:56:03.154 [Debug] [ComfyUI-0/STDERR] Adding extra search path embeddings D:\A1111\stable-diffusion-webui\embeddings
01:56:03.155 [Debug] [ComfyUI-0/STDERR] Adding extra search path embeddings D:\A1111\stable-diffusion-webui\Models\embeddings
01:56:03.156 [Debug] [ComfyUI-0/STDERR] Adding extra search path hypernetworks D:\A1111\stable-diffusion-webui\Models\hypernetworks
01:56:03.156 [Debug] [ComfyUI-0/STDERR] Adding extra search path controlnet D:\A1111\stable-diffusion-webui\controlnet
01:56:03.157 [Debug] [ComfyUI-0/STDERR] Adding extra search path controlnet D:\A1111\stable-diffusion-webui\Models\ControlNet
01:56:03.157 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip_vision D:\A1111\stable-diffusion-webui\Models\clip_vision
01:56:03.158 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip_vision D:\A1111\stable-diffusion-webui\Models\clip_vision
01:56:03.159 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip D:\A1111\stable-diffusion-webui\Models\clip
01:56:03.159 [Debug] [ComfyUI-0/STDERR] Adding extra search path unet D:\A1111\stable-diffusion-webui\Models\unet
01:56:03.160 [Debug] [ComfyUI-0/STDERR] Adding extra search path gligen D:\A1111\stable-diffusion-webui\Models\gligen
01:56:03.161 [Debug] [ComfyUI-0/STDERR] Adding extra search path ipadapter D:\A1111\stable-diffusion-webui\Models\ipadapter
01:56:03.163 [Debug] [ComfyUI-0/STDERR] Adding extra search path yolov8 D:\A1111\stable-diffusion-webui\Models\yolov8
01:56:03.164 [Debug] [ComfyUI-0/STDERR] Adding extra search path tensorrt D:\A1111\stable-diffusion-webui\Models\tensorrt
01:56:03.164 [Debug] [ComfyUI-0/STDERR] Adding extra search path clipseg D:\A1111\stable-diffusion-webui\Models\clipseg
01:56:03.165 [Debug] [ComfyUI-0/STDERR] Adding extra search path custom_nodes D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
01:56:03.166 [Debug] [ComfyUI-0/STDERR] Adding extra search path custom_nodes D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
01:56:04.887 [Debug] [ComfyUI-0/STDERR] 
01:56:04.889 [Debug] [ComfyUI-0/STDERR] Import times for custom nodes:
01:56:04.889 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: D:\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\websocket_image_save.py
01:56:04.890 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI-SAI_API
01:56:04.891 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\sd-dynamic-thresholding
01:56:04.892 [Debug] [ComfyUI-0/STDERR]    0.1 seconds: D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon
01:56:04.892 [Debug] [ComfyUI-0/STDERR]    1.2 seconds: D:\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra
01:56:04.893 [Debug] [ComfyUI-0/STDERR] 
01:56:04.893 [Debug] [ComfyUI-0/STDERR] Starting server
01:56:04.894 [Debug] [ComfyUI-0/STDERR] 
01:56:04.895 [Debug] [ComfyUI-0/STDERR] To see the GUI go to: http://127.0.0.1:7821
01:56:07.374 [Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
01:56:07.377 [Init] Self-Start ComfyUI-0 on port 7821 started.
01:56:07.377 [Debug] ComfyUI-0 self-start port 7821 loop ending (should now be alive)
01:56:07.819 [Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
01:56:08.245 [Debug] Data refreshed!

**Comment by mcmonkey4eva** [comment]
Are the models missing in Swarm's Generate tab model browser,  or the Comfy tab CheckpointLoader node, or both?

Are you sure, that, yknow, there's actually models in the relevant folder?

**Comment by FurkanGozukara** [comment]
I had to restart cmd after I changed paths

No other way worked
