### ISSUE TITLE
IP Adapter "FaceID Portrait" for style transfer not found and does not download

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#343]
### Expected Behavior

Find or Download the IP Adapter model for "FaceID Portrait".

### Actual Behavior

Gives an error that IP Adapter model is not found. Does not automatically download any model.

### Steps to Reproduce

Selected the IP Adapter "FaceID Portrait" from the list of IP Adapter models with a photo in the prompt.
Start generation.

![image](https://github.com/user-attachments/assets/2d76e7fd-8444-49f0-9223-1b2f0aa5ba0c)

### Debug Logs

Moving this issue from the Stability repo, so I just have this screenshot of the logs.
My build is already from this repo, just posted in the wrong place.

![image](https://github.com/user-attachments/assets/48b67689-978d-4655-9065-d4d17c464a74)

Looking in my Models folder, only these models were present:

![image](https://github.com/user-attachments/assets/5e69aadc-0f31-469b-837c-677f19f5238b)

**Comment by mcmonkey4eva** [comment]
should be good now
