### ISSUE TITLE
SD3.5 TensorRT

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#345]
### Feature Idea

SD3.5 needs support for TensorRT

![image](https://github.com/user-attachments/assets/97a4ab07-6d0f-4202-bff2-1004e2760637)

**Comment by mcmonkey4eva** [comment]
it probably requires an update to https://github.com/comfyanonymous/ComfyUI_TensorRT first? unless the comfy node already works with it somehow

it also probably won't work on consumer hardware, as TRT has crazy high requirements to build an engine
