### ISSUE TITLE
maces MpS support

### ISSUE THREAD

**Issue by yangboz** [mcmonkeyprojects/SwarmUI#348]
### Feature Idea

if Mac MPS could be supported ,it will be greatly helpful.  to avoid following error:
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

thanks for you guys effort for it. 

### Other

used Macosx M1 14.6.1 (23G93)  Docker version 26.1.3, build b72abbb  Docker Compose version v2.27.3   tested it .

**Comment by mcmonkey4eva** [comment]
Mac is supported: https://github.com/mcmonkeyprojects/SwarmUI?tab=readme-ov-file#installing-on-mac

For Mac + Docker I don't even know how you would do that, considering Mac GPU is mac exclusive ie there wouldn't be linux drivers able to run in docker

**Comment by yangboz** [comment]
> Mac is supported: https://github.com/mcmonkeyprojects/SwarmUI?tab=readme-ov-file#installing-on-mac
> 
> For Mac + Docker I don't even know how you would do that, considering Mac GPU is mac exclusive ie there wouldn't be linux drivers able to run in docker
yes,  I mean if M serials MPS can be detected and implemented it will be much better.
