### ISSUE TITLE
"Reuse Parameters" does not replace the current LoRAs when the reused image has none

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#35]
### Expected Behavior

When the reused image does not contain any LoRAs, the currently selected LoRAs should be removed to "match" the LoRAs used in the reused image.

### Actual Behavior

Any currently selected LoRAs remain selected, even though they were not used in the reused image.

### Steps to Reproduce

1. Select at least 1 LoRA
2. Select an image which does not contain any LoRAs and click "Reuse Parameters"
3. See the LoRA from step 1 is still selected

### Debug Logs

```powershell
N/A
```

**Comment by mcmonkey4eva** [comment]
Fixed
