### ISSUE TITLE
Found that <lora:> only works with <object:> and <segment:> but not with <region:>

### ISSUE THREAD

**Issue by MegaCocos** [mcmonkeyprojects/SwarmUI#350]
### Feature Idea

Would be fantastic to have an option to call different <lora:> inside of <region:> prompts, like inside of <object:> and <segment:> prompts. It was implemented in Regional Prompt extension for AUTOMATIC1111, very useful. 

### Other

Anyway, the article "Advanced Prompt Syntax" would be more complete and more extended, as Swarm prompting is very interesting and different from other's GUIs, really love SwarmUI for prompt options. <object:> command is not explained at all, was investigating what really means Strengh option of <object:> and in my case seems not affecting at all, a bit confused about what number to use.

**Comment by mcmonkey4eva** [comment]
regional loras is waiting on the ComfyUI patch_hooks branch to be finished https://github.com/comfyanonymous/ComfyUI/tree/patch_hooks

region/object are intentionally undocumented as they need better development and a proper UI rather than just documenting the cursed placeholder prompt syntax
