### ISSUE TITLE
Models tabs - add a "Details view

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#354]
### Feature Idea

Any chance we could get a "Details" view (like windows explorer, just one column for filepath...perhaps with adjustable width columns for other metadata, perhaps sortable)? 

The current "List" doesn't work well with long paths to models.

**Comment by mcmonkey4eva** [comment]
added

**Comment by mcmonkey4eva** [comment]
(Not very involved atm, just a basic view format, can't muck with columns at all currently)

**Comment by mcmonkey4eva** [comment]
will consider https://github.com/mcmonkeyprojects/SwarmUI/issues/124 as the open feature request for more control over the table
