### ISSUE TITLE
Possible to install without model download?

### ISSUE THREAD

**Issue by maniac-0s** [mcmonkeyprojects/SwarmUI#355]
### Your question

I am trying to install this on Arch Linux. Problem here I am on a rather slow LTE connection that's also limited in volume. I couldn't find a way to install it without downloading a model as I already have a folder with more than 200 SD and Flux models. The 6 GB download is totally unneccessary but would take almost half an hour here (if the connection doesn't interrupt and forces me to start over again).

**Comment by mcmonkey4eva** [comment]
yeah there's options in the installer for what you want or don't want

**Comment by FurkanGozukara** [comment]
@maniac-0s yep just shown in this video how to install on windows and runpod - public video : https://youtu.be/-zOKhoO9a5s
