### ISSUE TITLE
install-windows.bat fail

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#358]
### Expected Behavior

install dotnet and git

download
install-windows.bat

start in admin CMD

log below
(should i add the dotnet path manualy ???)

### Actual Behavior

error

### Steps to Reproduce

...

### Debug Logs

Das System kann den angegebenen Pfad nicht finden.
""
""
"WARNING: You did a git pull without building. Will now build for you..."
""
""
Das System kann den angegebenen Pfad nicht finden.
Das System kann die angegebene Datei nicht finden.
error: Die angegebene Quelle wurde der Liste der verfügbaren Paketquellen bereits hinzugefügt. Geben Sie eine eindeutige Quelle an.

Usage: dotnet nuget add source [arguments] [options]

Arguments:
  PackageSourcePath  Pfad zur Paketquelle.

Options:
  -n|--name                       Name der Quelle.
  -u|--username                   Der Benutzername, der beim Herstellen einer Verbindung mit einer authentifizierten Quelle verwendet werden soll.
  -p|--password                   Kennwort, das beim Herstellen einer Verbindung mit einer authentifizierten Quelle verwendet werden soll.
  --store-password-in-clear-text  Ermöglicht das Speichern von Anmeldeinformationen für portierbare Paketquellen durch Deaktivieren der Kennwortverschlüsselung.
  --valid-authentication-types    Eine durch Trennzeichen getrennte Liste gültiger Authentifizierungstypen für diese Quelle. Legen Sie diese Option auf "basic" fest, wenn der Server NTLM oder eine Aushandlung ankündigt und Ihre Anmeldedaten über den Basismechanismus gesendet werden müssen, z. B. bei Verwendung eines persönlichen Zugriffstokens (PAT) mit einer lokalen Azure DevOps Server-Instanz. Andere gültige Werte sind "negotiate", "kerberos", "ntlm" und "digest", aber diese Werte sind wahrscheinlich nicht sinnvoll.
  --protocol-version              The NuGet server protocol version to be used. Currently supported versions are 2 and 3. See https://learn.microsoft.com/nuget/api/overview for information about the version 3 protocol. Defaults to 2 if not specified.
  --configfile                    Die NuGet-Konfigurationsdatei. Sofern angegeben, werden nur die Einstellungen aus dieser Datei verwendet. Falls nicht angegeben, wird die Hierarchie der Konfigurationsdateien aus dem aktuellen Verzeichnis verwendet. Weitere Informationen finden Sie unter https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help                       Show help information

MSBuild-Version 17.9.8+b34f75857 für .NET
  Wiederherzustellende Projekte werden ermittelt...
e:\SwarmUI\src\SwarmUI.csproj : error NU1301: Der Dienstindex für die Quelle "https://api.nuget.org/v3/index.json" konn
te nicht geladen werden.
  Fehler beim Wiederherstellen von "e:\SwarmUI\src\SwarmUI.csproj" (in "5,73 sec").

Fehler beim Buildvorgang.

e:\SwarmUI\src\SwarmUI.csproj : error NU1301: Der Dienstindex für die Quelle "https://api.nuget.org/v3/index.json" konn
te nicht geladen werden.
    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:06.26
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Drücken Sie eine beliebige Taste . . .

e:\SwarmUI>

### Other

it give not an usual way
like create an environment
activate it
and than
pip install -r requierement.txt

**Comment by mcmonkey4eva** [comment]
It looks like your computer failed to connect to https://api.nuget.org/v3/index.json which is required for at least the first launch to download necessary dependencies.

You might need to:
(A) just wait a bit and try again
(B) restart your computer
(C) disable any VPN/firewall/whatever might interfere with network connections
(D) A previous user found that deleting their NuGet folder helped, which for Windows would be `%appdata%/NuGet` and `%localappdata%/NuGet`, albeit I don't think that's relevant in this case

**Comment by FurkanGozukara** [comment]
using warp vpn (from cloudflare) enabled installation also helps a lot - i saw so many people fixed network related issues

**Comment by kalle07** [comment]
oh thx ...
yes it was in my DNS blocklist
i will see how it runs after install   ;)
