### ISSUE TITLE
vae list feature

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#361]
### Feature Idea

maybe the list can be ordered alphabetical ...

and on start it is no option
Automatic
after i choose Automatic its in the list after i choose another one its gone again

**Comment by mcmonkey4eva** [comment]
what

**Comment by kalle07** [comment]
![image](https://github.com/user-attachments/assets/61d7e7e8-d0e5-4cc7-bfa7-c3e5d5a6d35e)


the model list 
![image](https://github.com/user-attachments/assets/6c566cbe-c4c1-4c36-abb3-f064ca779334)

is ordered 
first numbers and than upper and than lower case letters

1
2
3
A
B
C
a
b
c


thats confusing ^^

**Comment by mcmonkey4eva** [comment]
Ah, sorry, I tend to forgot that parameter even exists. Pushed a fix for all 3 points (the "Automatic", the VAE List being unsorted, and the sort orders being case sensitive)

**Comment by kalle07** [comment]
?
models are still unsorted for 90% windows users uses swarmui ?!?
first upper than lower , why ?

I have heard that this is difficult to program, you can copy paste from
https://github.com/oobabooga/text-generation-webui
maybe here you find a hint 
[ui_model_menu.py](https://github.com/oobabooga/text-generation-webui/blob/main/modules/ui_model_menu.py)


![grafik](https://github.com/user-attachments/assets/a39ab965-a9a0-48ee-83cf-8ffd5be619ef)
