### ISSUE TITLE
Save option with one click for generated image

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#369]
### Feature Idea

i like to generate one image after another or 12 in a row
and when I look at them individually, I want to save them immediately (mostly standard download folder)

so one click save option 

the option that the menu order can be added with "download" at first position

![grafik](https://github.com/user-attachments/assets/5e82366a-9e2c-47a8-9f03-a93ec8cae332)

**Comment by mcmonkey4eva** [comment]
If you want most or all gens saved, you know that happens by default, right? And if you only want some images saved separately as better than the rest, that's what `Star` is for

**Comment by kalle07** [comment]
i see ... okay than iam with it...

i was unfamiliar with that star
