### ISSUE TITLE
handle flux model all in one

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#375]
### Expected Behavior

model function

### Actual Behavior

see below

### Steps to Reproduce

choose this model
https://civitai.com/models/895985?modelVersionId=1002767

all inside clip, vae, t5xxl
-> in Forge it runs without any error and without any vae,clip and t5xxl

### Debug Logs

11:46:38.043 [Info] User local requested 1 image with model 'fluxDevSchnellBaseUNET_fluxDevFP32NF4.safetensors'...
11:46:38.618 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
11:46:38.619 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
11:46:38.619 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
11:46:38.620 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.620 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
11:46:38.621 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
11:46:38.621 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.622 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
11:46:38.622 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
11:46:38.623 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
11:46:38.623 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
11:46:38.623 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.624 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 885, in load_unet
11:46:38.624 [Warning] [ComfyUI-0/STDERR]     model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
11:46:38.625 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.625 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 728, in load_diffusion_model
11:46:38.626 [Warning] [ComfyUI-0/STDERR]     model = load_diffusion_model_state_dict(sd, model_options=model_options)
11:46:38.626 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.627 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 719, in load_diffusion_model_state_dict
11:46:38.627 [Warning] [ComfyUI-0/STDERR]     model.load_model_weights(new_sd, "")
11:46:38.628 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_base.py", line 224, in load_model_weights
11:46:38.628 [Warning] [ComfyUI-0/STDERR]     m, u = self.diffusion_model.load_state_dict(to_load, strict=False)
11:46:38.628 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:46:38.629 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2584, in load_state_dict
11:46:38.629 [Warning] [ComfyUI-0/STDERR]     raise RuntimeError(
11:46:38.630 [Warning] [ComfyUI-0/STDERR] RuntimeError: Error(s) in loading state_dict for Flux:
11:46:38.630 [Warning] [ComfyUI-0/STDERR]       size mismatch for img_in.weight: copying a param with shape torch.Size([98304, 1]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
11:46:38.729 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: Error(s) in loading state_dict for Flux:

200 lines more and in the end...

11:46:38.767 [Warning] [BackendHandler] backend #0 failed to load model fluxDevSchnellBaseUNET_fluxDevFP32NF4.safetensors
11:46:39.042 [Warning] [BackendHandler] All backends failed to load the model 'e:\WebUI_Forge\webui\models\diffusion_models/fluxDevSchnellBaseUNET_fluxDevFP32NF4.safetensors'! Cannot generate anything.
11:46:39.043 [Error] [BackendHandler] Backend request #6 failed: All available backends failed to load the model 'e:\WebUI_Forge\webui\models\diffusion_models/fluxDevSchnellBaseUNET_fluxDevFP32NF4.safetensors'.
11:46:39.044 [Error] [BackendHandler] Backend request #6 failed: All available backends failed to load the model 'e:\WebUI_Forge\webui\models\diffusion_models/fluxDevSchnellBaseUNET_fluxDevFP32NF4.safetensors'.

**Comment by mcmonkey4eva** [comment]
`FP32NF4`
what the hell is this file that's both fp32 (hwot?) and nf4 (ew)

Generally an "all in one" model (read: ordinary model) goes in the `Stable-Diffusion` folder, only the "unet"/"backbone"/"diffusion_model" models go in diffusion_models

nf4 support is a bit limited as it was quickly disregarded in favor of GGUF, which is similar to nf4 but just works better

**Comment by kalle07** [comment]
i see but these model 25% faster in sec/iter  ...
