### ISSUE TITLE
add model hashes so civitai can link models

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#378]
### Feature Idea

implement metadata for lora so that civitai can read that, the prompt is working but lora not

usual in forge also the hash included

Steps: 25, Sampler: [Forge] Flux Realistic, Schedule type: DDIM, CFG scale: 1, Distilled CFG Scale: 3.5, Seed: 1915272077, Size: 800x1200, Model hash: 0c6631c392, Model: !flux1DevFp8_v10, Lora hashes: "makeup_art_FLUX_v1: 801f5d2c1395",

**Comment by mcmonkey4eva** [comment]
this is a planned feature

**Comment by mcmonkey4eva** [comment]
Oh, this was added recently, via a server config setting that defaults off

**Comment by kalle07** [comment]
for me it dont work, i checked the box

now the hash are included

  "sui_models": [
    {
      "name": "Flux1DevFp8_v10.safetensors",
      "param": "model",
      "hash": "0x2f3c5caac0469f474439cf84eb09f900bd8e5900f4ad9404c4e05cec12314df6"
    },
    {
      "name": "ae.safetensors",
      "param": "vae",
      "hash": "0xddec9c299f56c1178e6281a12167f2ebec9aa4de8fce81e234a687bb231d5b6d"
    },
    {
      "name": "flux/123/123.safetensors",
      "param": "loras",
      "hash": "0x79c100e8e1b5dba7cae57ff04fe702164b2efcf6cb4060086cddb66ec2f97314"
    }

but it is not recognized on civitai ... at least not instantly (like a1111 or forge)
I waited another 10 minutes ... nothing

i have copy above how forge doeas the meta-data save

**Comment by mcmonkey4eva** [comment]
civitai doesn't read the metadata yet, they still need to add support on their end

**Comment by jtreminio** [comment]
I created a small Python script that converts SwarmUI's metadata to the format Civitai expects: https://github.com/jtreminio/swarmui_exif_to_civitai
