### ISSUE TITLE
Seamless Tiling doesn't work with SD3

### ISSUE THREAD

**Issue by mediastacks** [mcmonkeyprojects/SwarmUI#38]
### Expected Behavior

When "Seamless tileable" option in "Sampling" is set to "true", SD3 (like any other model) supposed to generate images that can be stacked together with no identifiable seams. It works perfectly with SDXL and earlier SD versions.

SDXL image
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/69261677/c2923839-25b4-43a2-8ec9-21bacfb4d6a1)

### Actual Behavior

Regardless of prompt details, sampler methods, and most importantly, activation of "Seamless Tileable" tooggle, the resulting image is not a seamless tileable pattern, as seen below.

SD3 image (all the same parameters otherwise)
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/69261677/86022b51-a343-4147-8b31-cb0cc957b021)

### Steps to Reproduce

- Model: sd3_medium_incl_clips_t5xxlfp8
- Resolution: 1024 x 1024
- Prompt example: seamless pattern, large autumn leaves, minimal
- Any sampler method, CFG and number of steps

### Debug Logs

```powershell
There are no errors, all seems normal.
```

**Comment by mediastacks** [comment]
BTW thank you for developing this amazing UI. I was deterred by the complexity of ComfyUI but your interface is very clean and accessible, allowing to use all the power of Comfy without necessarily dealing with nodes. And a great learning tool allowing to see exactly how things are done in ComfyUI. Just wanted to show a little bit of appreciation :)

**Comment by mcmonkey4eva** [comment]
Unfortunately making SD3 seamless will require a whole new trick to it - for SD1/SDXL, seamless tileable uses a conv padding alteration, but SD3 does not use conv layers at all. I believe the VAE seamless mode still works but that's only a small part of it, the mmdit doesn't have an immediately clear way to make it seamless

**Comment by mediastacks** [comment]
> Unfortunately making SD3 seamless will require a whole new trick to it - for SD1/SDXL, seamless tileable uses a conv padding alteration, but SD3 does not use conv layers at all. I believe the VAE seamless mode still works but that's only a small part of it, the mmdit doesn't have an immediately clear way to make it seamless

This is unfortunate. Can anything be done about this?

**Comment by mcmonkey4eva** [comment]
In theory, yes.

In practice... needs somebody who understands neural network internals to spend significant time on it. Or some janked up tiled-offset hack or something.

So probably out of scope for just a Swarm feature request. If/when somebody does find a good way to do seamless on SD3, it can be added to Swarm though

**Comment by Crono141** [comment]
I know this is closed, but just to add, this issue applies to FLUX models as well.
