### ISSUE TITLE
Yolov8 in Segment not using correct SwarmYoloDetection Node

### ISSUE THREAD

**Issue by re3me** [mcmonkeyprojects/SwarmUI#381]
### Your question

When using yolov8 detection in a segment following the suggested prompt syntax from https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Prompt%20Syntax.md#automatic-segmentation-and-refining the backend doesnt appear to load the correct node. It loads SwarmClipSeg Node and not SwarmYoloDetection Node. Because of this the detection does not function. I am not sure if this is a user error on my behalf. Syntax example used in prompt: `<segment:face_yolov8n-seg2_60.pt,0.4,0.5>" {face prompt}`

**Comment by FurkanGozukara** [comment]
syntax for yolo

<segment:yolo-face_yolov8n-seg2_60.pt,0.7,0.5>
