### ISSUE TITLE
run FLUX fp8 model

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#385]
### Expected Behavior

run in default parameter set

i tryed 3 different fp8 models  (11GB)

### Actual Behavior

...

### Steps to Reproduce

...

### Debug Logs

with ae

17:17:53.475 [Info] User local requested 1 image with model 'flux1-schnell_fp8_unet.safetensors'...
17:17:53.476 [Warning] [BackendHandler] No backends match the request! Cannot generate anything. Backends refused for the following reason(s):
- Request requires model 'ae-f16.gguf' but the backend does not have that model
17:17:53.476 [Error] [BackendHandler] Backend request #14 failed: No backends match the settings of the request given! Backends refused for the following reason(s):
- Request requires model 'ae-f16.gguf' but the backend does not have that model

with ae-f16.gguf
image is generating but after that

17:18:27.578 [Info] User local requested 1 image with model 'flux1-schnell_fp8_unet.safetensors'...
17:19:53.784 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
17:19:53.785 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
17:19:53.785 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
17:19:53.785 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:19:53.786 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
17:19:53.787 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
17:19:53.787 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:19:53.787 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
17:19:53.788 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
17:19:53.788 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
17:19:53.789 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
17:19:53.789 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:19:53.790 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 284, in decode
17:19:53.790 [Warning] [ComfyUI-0/STDERR]     images = vae.decode(samples["samples"])
17:19:53.791 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:19:53.791 [Warning] [ComfyUI-0/STDERR]   File "e:\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 332, in decode
17:19:53.792 [Warning] [ComfyUI-0/STDERR]     memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
17:19:53.792 [Warning] [ComfyUI-0/STDERR]                                                             ^^^^^^^^^^^^^^
17:19:53.793 [Warning] [ComfyUI-0/STDERR] AttributeError: 'VAE' object has no attribute 'vae_dtype'
17:19:53.793 [Warning] [ComfyUI-0/STDERR]

it runs without VAE "NONE"

but is that right ???

**Comment by kalle07** [comment]
sry 2 run, one not
-> black image 
  ... i dont know  why , in FORGE all tree run ?!?

you can delete that issue  .. i cant  ;)

**Comment by mcmonkey4eva** [comment]
the `_unet` suffix means it needs to be store in the `diffusion_models` folder instead of the normal folder

See docs https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#black-forest-labs-flux1-models for more model usage info
