### ISSUE TITLE
compfy workflow

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#386]
### Feature Idea

all models in folder 
diffusion_models
dont be aviable yet ...

**Comment by mcmonkey4eva** [comment]
what

**Comment by kalle07** [comment]
![grafik](https://github.com/user-attachments/assets/385bf52d-8454-4484-9728-6bc5f2cfae9d)

here only the models inside folder
Models\Stable-Diffusion\

not the flux models inside
Models\diffusion_models\

**Comment by mcmonkey4eva** [comment]
yes diffusion_models is a different folder corresponding to different nodes

When in doubt, set up generations on the Generate tab, then hit "import from generate tab" to see what nodes are needed
