### ISSUE TITLE
System.IO.PathTooLongException with /API/ListImages and /API/OpenImageFolder when SaveFiles is false in User Settings

### ISSUE THREAD

**Issue by cvrunmin** [mcmonkeyprojects/SwarmUI#393]
### Expected Behavior

data image should be correctly handled as data url, not a normal file path
For /API/ListImages, the image in memory should be shown
For /API/OpenImageFolder, it should be a no-op, or a popup should be displayed, telling user that this image is in memory
For /API/ToggleImageStarred, the image shall be saved and also starred, or a no-op

### Actual Behavior

Error dialog is popped up

### Steps to Reproduce

1. turn SaveFiles in User Settings into false
2. generate any image you like
3. click any of "Star", "View In History", "Open In Folder"

### Debug Logs

https://paste.denizenscript.com/View/127834

**Comment by mcmonkey4eva** [comment]
Fixed (in the UI rather than the API, since those buttons make no sense to present for unsaved images)
