### ISSUE TITLE
Add auto complete/ a easier way to copy trigger words for Lora

### ISSUE THREAD

**Issue by cvrunmin** [mcmonkeyprojects/SwarmUI#394]
### Feature Idea

Now the ways of adding trigger words for lora can be concluded into three ways:
1. adding <trigger> as prompt
2. copying the trigger words by:
   1. switching display format of LoRA tab into Card modes; find your LoRA card; highlight the trigger phrase; copy; paste it on prompt
   2. In any display format of LoRA tab, click 'Edit metadata' of your LoRA; copy values of trigger phrase; click cancel; paste it on prompt
3. type it by yourself

However, the methods have their own weakness, especially when the LoRA contains the concept of (a) character(s), with trigger phrase separated on clothes:
1. The first method always fill in everything, blocking users to make characters with different looks.
2. The second method is complex as:
   1. Users seem to be forced to use Card display format if they want to copy trigger phrase without making popups; and
   2. Copying at 'Edit metadata' dialog is dangerous as user is too dumb to keep it intact.
3. User is too dumb to remember trigger phrase for the third method.

This issue suggests a new way that allows users to input trigger phrase they needed, not necessarily all phrases as in <trigger>. We may take examples from the AI drawing service in the market. For example:
1. in CivitAI, the trigger words are listed, allowing users to one click copying them, and then paste them in the prompt:
![image](https://github.com/user-attachments/assets/350f5eb6-d91a-47c3-81d8-509ae197c277)
2. in tensor.art, the tirgger words are listed allowing users to add them directly to the prompt:
![image](https://github.com/user-attachments/assets/6254ffd8-4f42-42f5-b6e2-50fcadb2f9ff)

With this, trigger phrase is also suggested to be a list of "phrases" when stored in the metadata, allowing selecting subsets of phrases, which the subset is provided by the LoRA author.

### Other

Related issue: #317. While that issue suggests a new syntax, this issue suggest a GUI change instead.

**Comment by pupphelper** [comment]
+1 a better way to handle adding trigger words would be amazing.

**Comment by southbayjay** [comment]
> +1 a better way to handle adding trigger words would be amazing.

You can add your trigger words to the metadata of the model, which should already be there if you used the built in Swarm model downloader. All you need to remember is to add this syntax to your prompt `<trigger>` that works with ANY lora that has trigger words stored in the models metadata..

If you didn't use the Swarm model downloader you can also grab the URL from Civit website where you get the model, go into the "edit metadata" and use the link to import all the metadata from Civit. Don't forget to click "save" at the bottom once you finish the import.

**Comment by southbayjay** [comment]
Also you both are welcome to come by the official SwarmUI discord server and get help or ask questions there.. 

https://discord.gg/XDGYCWBG
