### ISSUE TITLE
Support Greater Than 2 Axis Grid Image

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#395]
### Feature Idea

i generate a grid like 

![grafik](https://github.com/user-attachments/assets/f9a4e56d-3931-4b55-b8b1-ca647ca0df56)

it was saved as an image one column and 15 rows
why not real XYZ image?
how can i get an image like in FORGE
3 column (CFG)
5 rows (Steps)

**Comment by mcmonkey4eva** [comment]
"Grid Image" format only supports 2 axes.
"Web Page" will render up to 4 axes at once (with clickables to swap the axes at will between as many more as you have)

**Comment by kalle07** [comment]
thy... why not automatic? you can copy/paste from forge  ;)

and these "Dry Run", its possible to get a grit with black images how it would be look like ?
