### ISSUE TITLE
Seed values roll at each generation when setting seed value in prompt box & seed values are n+1 for segment masks

### ISSUE THREAD

**Issue by re3me** [mcmonkeyprojects/SwarmUI#398]
### Your question

Hello, I am not sure if this is a user error or setting somewhere that i missed in the wiki files but I have noticed that when generating images one at a time and I click the generate button that each subsequent click rolls the seed n+1. This is not helpful when trying to compare settings. If I set a seed in the prompt I expect all generations to hold the seed value until I choose otherwise. And to add to this when I looked at the comfy workflow to figure out if something is set there that I could fix I discovered that all the seed values for any segments also roll the base seed+1. While this isnt as much of an issue it does make a difference and actually explains some odd results that i have gotten with prior generations. Can we set the seed from the generate tab and ensure it doesnt change so I dont have to go to the comfy tab and copy/paste the seed where needed? Let me know if this is actually an issue and Ill open a ticket. 

### Other

![image](https://github.com/user-attachments/assets/d5c17a92-f9fd-4e12-b472-49e66095b6b1)

**Comment by mcmonkey4eva** [comment]
The first part was a bug that was already fixed, just update.

The segment part is intentional - if you run the same seed *on the same image directly* you get corrupt results, so anything that directly applies onto the same image in Swarm automatically offsets the seed to prevent corruption. Try a simple refiner workflow in comfy (ie sampler pipes directly into sampler again, with start at step a bit forward) with the same seed between all of the samplers and you'll see this.

**Comment by re3me** [comment]
Thank you!

**Comment by brendanhoar** [comment]
Was this fixed for the case where the Images value > 1? E.g. Seed is 0, Images is 5. If I wait for a run of five images to generate (0-4) and finish, then click generate, I get the same 5 images (0-4) again. But if I hit generate before the images are done, it creates images for the next five seeds (5-9). The behavior wasn't always there, I don't think.

B

**Comment by mcmonkey4eva** [comment]
yes that case works exactly as intended in my local, so the fix for the issue applied to that fine

**Comment by brendanhoar** [comment]
> yes that case works exactly as intended in my local, so the fix for the issue applied to that fine

Huh. In basic tests it seems fixed, but I keep running into it from time to time and I can't figure out how to repro it. Frustrating. [Yes, updated.]
