### ISSUE TITLE
recycle bin for output

### ISSUE THREAD

**Issue by snottyone** [mcmonkeyprojects/SwarmUI#40]
### Feature Idea

an option to enable recycle bin deletion for output files in windows and linux
thank you :)

**Comment by mcmonkey4eva** [comment]
Added new option in server config:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/57668f05-d925-41ad-bcea-d67fab126cd8)

Tested on Windows. The internet says the method I use should work on other platforms too.
