### ISSUE TITLE
"Match Init Image Res" and/or "Match Init Image Aspect Ratio" options

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#401]
### Feature Idea

When an Init image is set for the prompt, would be good to have options appear in the resolution settings to either "Match Init Img Res" or "Match Init Img Aspect".
Not sure how the aspect ratio would work but i say that specifically because some reference images i might use could have crazy high resolutions, so i would just usually get an approximate aspect ratio to match with a lower resolution.
Would be handy instead of having to set the Custom resolution manually.

**Comment by mcmonkey4eva** [comment]
added, button next to the Init Image input
