### ISSUE TITLE
Image editor paintbrush color doesn't change immediately

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#408]
### Expected Behavior

Click on color pallete then close paint with the new color.

### Actual Behavior

Will start coloring with the previous color first after clicking in the image editor, the second click will be the new color.

### Steps to Reproduce

Open image editor
Select a color from the color palette.
Click on the image once to start drawing without clicking to the side to close the color palette first.

### Debug Logs

Don't have them right now.

**Comment by mcmonkey4eva** [comment]
This doesn't happen for me, on either Firefox or Chrome.
