### ISSUE TITLE
Mask isn't getting saved to image?

### ISSUE THREAD

**Issue by nikolatesla20** [mcmonkeyprojects/SwarmUI#410]
### Expected Behavior

If I open the Image editor and draw a mask it should remain as part of the image

### Actual Behavior

Mask gets reset anytime I open the image editor

### Steps to Reproduce

Open or drag an image into SwarmUI
Choose "edit image"
Edit the mask
Close the image editor
Re-open the image editor

Defect/confusing: The mask is gone

### Debug Logs

no logs available for this bug

### Other

Image is a JPEG. Perhaps this is a problem?
SwarmUI version  v0.9.3.1

**Comment by mcmonkey4eva** [comment]
yes, masks aren't an inherent part of an image, they're just input to the generator, so they're not in the image file anywhere. If you close the editor and open it fresh it of course is reset from fresh, and does not persist your old inputs.

**Comment by nikolatesla20** [comment]
But the mask doesn't appear to work. After I draw the mask the inpaint
doesn't work it just creates a whole new image
