### ISSUE TITLE
ComfyUI backend doesnt work with Stable Video Diffusion XT 1.1 for creating image to video. Are there others that work?

### ISSUE THREAD

**Issue by borris345** [mcmonkeyprojects/SwarmUI#411]
### Expected Behavior

To create a short video

All available backends failed to load the model 'G:\SwarmUI\Models\diffusion_models/stableVideoDiffusion_img2vidXt11.safetensors'.

### Actual Behavior

![image](https://github.com/user-attachments/assets/cedbe0b9-313c-45a7-9316-670194d73f54)

### Steps to Reproduce

1, Load Stable Video Diffusion XT 1.1
2, Type prompt
3, Generate video

### Debug Logs

https://paste.denizenscript.com/View/128089

**Comment by borris345** [comment]
still the same problem.

**Comment by mcmonkey4eva** [comment]
oh, use the `Image To Video` param group, don't select it as the base model - the base model should be a regular text to image. SVD is Image-To-Video, meaning it cannot do Text-To-Video, meaning something else has to do the Text-To-Image step.
