### ISSUE TITLE
On the way to invoke model generation using requests.

### ISSUE THREAD

**Issue by 493226363** [mcmonkeyprojects/SwarmUI#414]
### Your question

I successfully used SwarmUI to run the generative model, using the Web interface. But I wanted to use the request to invoke the runtime model. I looked at the Web side and used JS code to communicate with Socket requests. But I don't understand JS code and can't understand the whole request and the format of the request parameters. I don't know if there is already request support in SwarmUI that I didn't find, or if there are direct requests to the ComfyUI backend examples that I could refer to.

**Comment by mcmonkey4eva** [comment]
I don't entirely understand the question, but sounds like you're wanting the API docs? https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/API.md
