### ISSUE TITLE
About how to use API to call Mochi model video generation

### ISSUE THREAD

**Issue by 493226363** [mcmonkeyprojects/SwarmUI#417]
I need an API to generate videos from Mochi models. I checked the API documentation and couldn't find a way to use the API for video generation. I tried to use the text-to-image API, but it didn't work, I wasn't sure what parameters were needed. Is there any documentation on how to use it?

**Comment by mcmonkey4eva** [comment]
Docs are @ https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/API.md

Works the same as anything else as far as the API is concerned. When in doubt, run Mochi in the UI first then replicate the network call
