### ISSUE TITLE
add image name to information

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#418]
### Feature Idea

add image name to these list

![grafik](https://github.com/user-attachments/assets/b678ce1e-25ed-4ffe-9dbe-c0efc7307b77)

ok, i generate 20 images to get the best one and i dont want to press "star" and i dont want use the image history
so i browse with eg irfan-view on a second monitor to watch them in full-screen ... i get one good image , i see the name but i can only find the image in swarm-ui if i use the image-history

**Comment by mcmonkey4eva** [comment]
double-click an image to view it full-screen inside the UI, you can use arrow keys to scroll through them. It automatically uses the context of where you clicked it from - if you click from batchview, it arrow key scrolls through, if you click in history, it scrolls through your history

**Comment by kalle07** [comment]
i see but i dont see the saved image name and in addition i can not pic them as "STAR" in full screen ... therefore, in my opinion, it may make more sense to change something at this point
and i have two monitors one for generate and one to view image in fullscreeen (portrait)
