### ISSUE TITLE
Incorrect aspect ratio when using upscale 2x button

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#42]
### Expected Behavior

Image metadata contains the correct aspect ratio matching the original image when using "Upscale 2x"

### Actual Behavior

Image metadata contains the aspect ratio that is selected in the parameters on the left of the UI.

### Steps to Reproduce

1. Generate an image (say with aspect ratio 1:1)
2. Change the aspect ratio parameter on the left of the UI (e.g. 2:3)
3. Select the previously generated image and click "Upscale 2x"
4. Notice the new image is correctly 2x the size of the original with 1:1 aspect ratio, but the metadata has 2:3 as the aspect ratio.

### Debug Logs

```powershell
N/A
```

### Other

When you try load the image back in with "Reuse parameters" it then tries to load it with the incorrect aspect ratio thats in the metadata.

**Comment by mcmonkey4eva** [comment]
fixed
