### ISSUE TITLE
Inconsistent randomization with wildcardseed and ranged tags

### ISSUE THREAD

**Issue by PetrK39** [mcmonkeyprojects/SwarmUI#421]
### Expected Behavior

Consistent and repeatable randomization of `<random>` and `<wildcard>` tags when using the `wildcardseed`.

### Actual Behavior

The `wildcardseed` resets after using tags with specified ranges (e.g., `<random[1-2]>`). Tags with constant values (e.g., `<random[2]>`) work as expected.  
After using `<random>` or `<wildcard>` with a range, every subsequent use of these tags in the prompt provides random values, even when the `wildcardseed` is set.  
Tags used before the ranged ones are not affected.  

Screenshots:  
    
![Image00001](https://github.com/user-attachments/assets/e99bccfd-9ffd-4fd5-9824-cba5a9fc625a)
![Image00002](https://github.com/user-attachments/assets/57f47724-2908-4f55-bded-63a28d3120f5)
![Image00003](https://github.com/user-attachments/assets/a011cd6c-996c-4a80-9387-c9d7e3b63763)
![Image00004](https://github.com/user-attachments/assets/1a02ac90-f811-4ec1-97e8-7c586960e588)

### Steps to Reproduce

1. Set `wildcardseed` to any value except `-1` (e.q., `123`) (`seed` doesn't affect this)
2. Use prompt: `<random:1, 2, 3, 4, 5> <random[1-5]:11, 22, 33, 44, 55> <random:111, 222, 333, 444, 555>`
2.1 Alternatively use wildcards the same way
3. Generate a few images (3+)
4. Notice consistency of first <random> and inconsistency of second and subsequent.

### Debug Logs

https://paste.denizenscript.com/View/128228

**Comment by PetrK39** [comment]
I suppose this happens because of the nature of seeded pseudo random.  
When you take a random amount of numbers from the middle of a pool, there's no way to get the same number when you're waiting for it.
So, unfixable then?

**Comment by mcmonkey4eva** [comment]
Oh, oops, that `1-3` input wasn't using the seeded random. Fixed
