### ISSUE TITLE
SwarmUI won't boot after upgrading the OS

### ISSUE THREAD

**Issue by suede299** [mcmonkeyprojects/SwarmUI#422]
### Your question

03:19:31.967 [Init] Swarm is up to date! You have version 0.9.3.1, and 0.9.3-Beta is the latest.
03:19:31.968 [Init] Program is running.
03:19:32.476 [Init] Launch web browser...
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Interop+Shell32.ShellExecuteExW(SHELLEXECUTEINFO*)
   at System.Diagnostics.Process+ShellExecuteHelper.ShellExecuteFunction()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

The same is true with update.bat

**Comment by suede299** [comment]
run_nvidia_gpu.bat can start comfyui directly, so it is not a problem with dlbackend

**Comment by mcmonkey4eva** [comment]
oh christ that's not a fun error to have.

The "good option" is _probably_ all you need is to uninstall and reinstall dotnet 8 https://dotnet.microsoft.com/en-us/download/dotnet/8.0 and it'll resolve itself.
The "bad option" is your OS upgrade went wrong and something is corrupt in your windows system32. Hopefully that's not the case.

**Comment by suede299** [comment]
Resolved, hope this helps someone else.
I reinstalled the .net sdk and the problem remains.
Finally opened SwarmUI.sln with visual studio and it would prompt to install the .net desktop development tool and change SwarmUI.sln. By the time the installation was complete, my SwarmUI started up fine.
