### ISSUE TITLE
Add Subfolder Specification for Output Images

### ISSUE THREAD

**Issue by PetrK39** [mcmonkeyprojects/SwarmUI#423]
### Feature Idea

I would like to propose a new feature that would greatly enhance the organization and management of generated images. Currently, all output images are saved directly into a single folder, which can become cluttered and difficult to manage, especially when working on multiple workflows.  
Add a parameter in the "Generate" tab on the left side of the interface that allows users to specify a subfolder for the output images. This subfolder could be named based on a user-defined prefix so it can be reused with "Reuse parameters" button.

**Comment by mcmonkey4eva** [comment]
User -> User Settings -> Outpath Builder -> Format -> set it to whatever you want, using whatever params you want. You can eg define folders to be based on model or whatever, or even do `[personalnote]` and then abuse the `Personal Note` param under Swarm Internal to be a freehand folder name
