### ISSUE TITLE
The new "Progress bar" over the preview is dumb, it just gets in the way. Can we turn that off?

### ISSUE THREAD

**Issue by nikolatesla20** [mcmonkeyprojects/SwarmUI#425]
### Feature Idea

In latest SwarmUI , I realize it seemed like a cool idea to put a spinning progress circle over the preview, but its honestly just unhelpful since it blocks your view of the image, for you being able to tell if it's looking how you want in the first place.

### Other

Don't over do the UI please.

**Comment by mcmonkey4eva** [comment]
yes, you can turn it off, click the gear icon at the top left of the batch area
