### ISSUE TITLE
Mochi 1 not creating anything at all

### ISSUE THREAD

**Issue by borris345** [mcmonkeyprojects/SwarmUI#428]
### Your question

All available backends failed to load the model 'H:\SwarmUI\Models\Stable-Diffusion/OfficialStableDiffusion\mochi1PreviewVideo_fp8Scaled.safetensors'. when i try to do a text to video. 

### Logs

https://paste.denizenscript.com/View/128250

**Comment by mcmonkey4eva** [comment]
Use this copy of the model: https://huggingface.co/Comfy-Org/mochi_preview_repackaged/blob/main/all_in_one/mochi_preview_fp8_scaled.safetensors

The ones you have are `diffusion_models` versions, which naturally go in the `diffusion_models` folder and need some special handling

**Comment by borris345** [comment]
Something went wrong while generating images.

Looks like its doing something then just as its finished it throws that error.

https://paste.denizenscript.com/View/128252

**Comment by mcmonkey4eva** [comment]
That type of sudden crash without an error message, especially right while it's starting up the VAE, implies out of memory crash.

See the notes in the docs @ https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#genmo-mochi-1-text2video re VAE Tile params
