### ISSUE TITLE
Activating a LORA inside <Preset:>

### ISSUE THREAD

**Issue by Cubiko123** [mcmonkeyprojects/SwarmUI#429]
### Your question

I am trying to make a list of <Preset:> so that if I generate 30 images, it will pick random ones from a 30 presets pool, each one with its LORA inside.
The issue is that if I write, for example:

<preset:<lora:example:0.8>, activation text1, activation text2, activation text3>

SwarmUI will say in the console,that the "activations texts" will be ignored.
Now, I'm pretty sure this happens because it opens the initial < symbol and it closes it with the LORA > symbol.
Doing so, the LORA is active, but it won't contain the activation words since they are ignored.

Is there anything I can do to fix this?
Also, sorry for my bad English.

**Comment by mcmonkey4eva** [comment]
make presets on the Presets subtab, not, whatever that is.
