### ISSUE TITLE
Allow Model Downloader to parse URLs where only a single model version exists

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#43]
### Feature Idea

I download new models frequently and one I tried in Utilities -> Model Downloader is: [epiCRainbowDash](https://civitai.com/models/541224)

Swarm returns the message:

`Status: URL appears to be a CivitAI link, but not a specific model. Please use the path of a specific model.`

I cannot find a link to the specific model so I'm unable to download through Swarm and had to do it manually.

Then in Edit Model Metadata, I entered the URL but it refused to link and pull any metadata. So now this model sits there in the list with the default thumbnail and no info.

I don't know if this should be a feature request or a bug report because Model Downloader expects a link to a file, not a page. However, the model definitely exists at that URL but Model Downloader can't see it.

I'm guessing it's down to there being only one model version available. Any time there are v1.0, v2.0, etc. there is no problem as clicking on each version number returns a URL specific to that version, therefore allowing Model Downloader to see it and proceed.

So I'm filing this as a feature request, asking that Model Downloader be able to parse URLs where only a single model version exists.

**Comment by mcmonkey4eva** [comment]
How did you get that URL?
You linked `https://civitai.com/models/541224`
Anywhere on the civit website I open that model from - eg from search, from the author's model list, etc. it gives me
`https://civitai.com/models/541224/epicrainbowdash`

**Comment by mcmonkey4eva** [comment]
Added parsing for the nameless format of URLs. Very curious how you even got that URL though, civit doesn't provide links like that anywhere I can find
