### ISSUE TITLE
While using the download utility the directory doesn't appear to update based on the model type. 

### ISSUE THREAD

**Issue by re3me** [mcmonkeyprojects/SwarmUI#430]
### Your question

While using the download utility the directory doesn't appear to update based on the model type. It is stuck pulling up my LoRA folder even if I want to save a chkpt. 

running version: SwarmUI v0.9.3.1 (2024-11-18 16:47:14)

![image](https://github.com/user-attachments/assets/169864df-a3e1-409a-8f7e-ee03ec85bdaa)

**Comment by mcmonkey4eva** [comment]
It, uh, sure does update the folder based on the "Model Type". Make sure you don't hit the "Download" button until the metadata loads (sometimes it takes a second). Also make sure your paths are set correctly under server configuration

**Comment by re3me** [comment]
You are so responsive! Thank you! 

Not sure what is going on. Ill update my file paths to see if this helps reset anything. Below is my current configuration. 

![image](https://github.com/user-attachments/assets/ef36085a-465d-41d6-b4a7-0fef1c440f70)

**Comment by mcmonkey4eva** [comment]
ftr sdmodelfolder should be `Stable-diffusion`, sdlorafolder should be `Lora`, etc. for all the model subtypes - they are relative to your root. They should work fine as you have them still though.

The screenshotted download in OP should have gone to `D:\AI\AIModels\Stable-diffusion\Other\epiCRealism_XL_VX-FinalKISS.safetensors`, as long as you hit download after metadata loaded and not before

**Comment by re3me** [comment]
Thanks again mcmonkey4eva - not sure what the issue was. I removed and updated my values for the folder locations and now it works.
