### ISSUE TITLE
LoRA Extractor for FLUX

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#431]
### Feature Idea

it fails for me 
16:38:02.581 [Error] Error in websocket handler: ComfyUI execution error: Model in folder 'checkpoints' with filename 'FLUX_01' not found.

but i choose and use the model before in the generation tab
and its located in
\diffusion_models\

**Comment by mcmonkey4eva** [comment]
more specifically it was unhappy with `diffusion_models` rather than Flux specifically. ps extracting loras from flux will take a while and use a ton of ram be warned

**Comment by mcmonkey4eva** [comment]
there are comfy nodes builtin by default for advanced merging, i do want to have a proper interface in swarm for it eventually yeah
