### ISSUE TITLE
Swap Fullscreen Image to New Image

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#432]
### Feature Idea

There are times when i want to see the new generated images as they are generated, and set the Generate mode to "Generate Forever", and I would like to do that while fullscreen.

Is it possible to add an option in the top right menu to "Replace fullscreen image with new image" that does so when the new generated image from the middle is clicked to view fullscreen?

![image](https://github.com/user-attachments/assets/7f630f9b-95d3-4d43-95fe-7e08195cac74)
![image](https://github.com/user-attachments/assets/394fcc76-8f4e-4c88-b149-d7eca7c89a21)
![image](https://github.com/user-attachments/assets/b0e3c150-1053-4421-a87a-f46fd76c7d53)

**Comment by mcmonkey4eva** [comment]
That option is under User Settings:
![image](https://github.com/user-attachments/assets/adc04f25-bbd9-4b4b-82b7-3f740585d815)
