### ISSUE TITLE
Downloading VAE from CivitAI doesn't set the right folder automatically 

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#433]
### Expected Behavior

Download a VAE model from civitai, it should go into the VAE folder automatically.

### Actual Behavior

Download folder will not change to VAE folder automatically, it will stay on the folder of the last model type it was set to (Base model or LoRA usually).

(I think I remember the same thing happens with downloading textual embeddings too, but not sure.)

### Steps to Reproduce

Launch UI
Open Download utility.
Put CivitAI link for a VAE model and download.

Or
Put a civitai link for a base model checkpoint and download that first.
Then put the link for a VAE model and download.
It will download the VAE to the base model folder instead of the VAE folder.

### Debug Logs

Don't have my computer rn.

**Comment by mcmonkey4eva** [comment]
can you please give an example link? there's not many vaes on civit last i looked

**Comment by Griphen116** [comment]
@mcmonkey4eva I just used the model filter on Civit to find VAEs.
Here's me putting the SDXL VAE link in the model downloader. The Model Type at the bottom left went to "Base Model".
https://civitai.com/models/296576/sdxl-vae?modelVersionId=333245
![image](https://github.com/user-attachments/assets/ea8852db-02a1-4395-8f31-69b0aa1dc6de)

**Comment by mcmonkey4eva** [comment]
Thank you for the link. iirc Model Type VAE did not exist on civitai at the time the model downloader was built, nice to see that exists now, albeit a bit late - the last VAE difference that mattered much was NAI vs SDv1 lol. All models since everyone just uses the base one.

Updated, works properly for that link
