### ISSUE TITLE
'Mask shrink grow' doesn't behave as expected when inpainting with 'Flux fill' model

### ISSUE THREAD

**Issue by willhsmit** [mcmonkeyprojects/SwarmUI#439]
### Expected Behavior

When using a Flux fill model with an inpainting mask with 'Mask shrink grow' turned on and set to a value, Swarm uses a cropped portion of the image near the mask as input to the generation, generates a new image of the cropped portion with the masked area repainted, and recomposites onto the fullsize original image.
 

### Actual Behavior

Swarm uses the fullsize image as input to the generation, generates a new version of the full image with the masked area repainted, resizes the fullsize image down to the cropped area around the mask, and composites it in. This results in portions of the fullsize image being repeated inside the mask, and distorts the aspect ratio of the mask.

Not sure I've explained it well, but example:
Input image:
![389207266-6da62741-36a1-4fd6-b523-4cbeb9c9bb86-crop](https://github.com/user-attachments/assets/bb2266a2-2acb-4a91-a155-a773c00a42c7)
Mask:
![mask](https://github.com/user-attachments/assets/e0b6b5e1-f2d1-46fe-9e96-7b69ca144aa8)

Prompt: Man with jacket
seed: 2003358640
model: flux1-fill-dev-Q4_K_S.gguf

Output:
![1636-a man wearing a jacket-flux1-fill-dev-Q4_K_S-2003358640](https://github.com/user-attachments/assets/1861c302-160e-4667-86ce-d225d4db3b95)

What you can see is that it's repeated the original 992x992 image inside the mask. 

### Steps to Reproduce

1. Pick a flux fill model
2. Drag an image into the UI 'Use as Init', 'Edit image'
3. Draw a mask on a portion of the image
4. Set 'Init creativity to 1', 'Mask Shrink Grow' to on and 32.
5. Generate

During generation, you can see the full original image in the preview, whereas with other models during the preview phase when 'Mask shrink grow' is on, you only see a cropped area around your mask. At the end you get the effect shown in the screenshots.

### Debug Logs

== SwarmUI logs 2024-11-24 17:00 ==
17:00:51.981 [Info] User local requested 1 image with model 'flux1-fill-dev-Q4_K_S.gguf'...
17:02:20.067 [Info] Generated an image in 2.16 (prep) and 83.84 (gen) seconds

**Comment by mcmonkey4eva** [comment]
fixed

**Comment by willhsmit** [comment]
For posterity, this is the current state of the above example, after the two commits:

https://github.com/mcmonkeyprojects/SwarmUI/commit/8eb77e578b207d28dcaa968c5412b041f662ad2d
and
https://github.com/mcmonkeyprojects/SwarmUI/commit/5e303de2f58b36ae1d5d775caf60dfe0a3687677


![1835-Man with jacket-flux1-fill-dev-Q4_K_S-2003358640](https://github.com/user-attachments/assets/6040c192-2e90-4bf3-a176-76e9b2450e69)
