### ISSUE TITLE
model resolution preset or preset inside model

### ISSUE THREAD

**Issue by kalle07** [mcmonkeyprojects/SwarmUI#440]
### Expected Behavior

it is a bug

### Actual Behavior

...

### Steps to Reproduce

create a preset with were resolution is set to 777x777
choose the preset 
apply the preset !
i see the resolution is set to 777x777

chose a model
and allways the resolution is set back to
832x1216

### Debug Logs

...

**Comment by mcmonkey4eva** [comment]
most models require resolution at least as a multiple of 8, many require x16, x32, or x64. Odd numbers are super not valid

**Comment by kalle07** [comment]
it is an example
same with 1024x680

**Comment by mcmonkey4eva** [comment]
make sure you set Aspect Ratio to Custom in the preset

**Comment by kalle07** [comment]
all presets from all models come up automatic with 832x1216

in in my preset i dont want custom i want 680x1024
