### ISSUE TITLE
Mask shrink/grow for segment syntax

### ISSUE THREAD

**Issue by CNorton84** [mcmonkeyprojects/SwarmUI#442]
### Feature Idea

I would love to see a parameter for segmentation that allows the user to specify an amount of padding around a segment mask to be included when the segmented area is inpainted. Or, to word it differently, to allow the user to control how tightly the segmented area is cropped.

Basically, I've found that when using the segment syntax to detail faces, the model is not able to blend the face adequately with the rest of the image because it can't "see" the rest of the image due to the tight cropping. You can mitigate this by increasing Segment Mask Grow and Segment Mask Blur, but that means you are modifying much more of the image than you might want to. Given how important it can be to manage how much of the image is included when detailing, I think it would be beneficial to have a way of controlling this like you can with Mask Shrink/Grow.

**Comment by mcmonkey4eva** [comment]
Parameters for this exist under Advanced -> Regional Prompting

![image](https://github.com/user-attachments/assets/06baa70b-b0d5-4389-ba57-aa10cf100df9)

**Comment by CNorton84** [comment]
I see the parameter to grow the mask, but I don't see one to expand the area around the mask that is included when the image is cropped without expanding the mask itself—like how Mask Shrink/Grow controls the size of the area around the mask when inpainting. Or am I completely missing something?

**Comment by mcmonkey4eva** [comment]
Oh, true -- added new parameter `Segment Mask Oversize` to control that

**Comment by FurkanGozukara** [comment]
@CNorton84 can  you please show example input mask and output in which scenario this is useful?

i could show in tutorial thank you so much
