### ISSUE TITLE
No custom nodes loading for me through SwarmUI

### ISSUE THREAD

**Issue by yo1nkers** [mcmonkeyprojects/SwarmUI#444]
### Expected Behavior

I should expect to be able to use custom nodes. I have downloaded a watermarking workflow that utilizes custom nodes

### Actual Behavior

Does not work

### Steps to Reproduce

Completely unsure. From what I guess, just download SwarmUI and own it for half a year lol

### Debug Logs

Pulling latest changes...
Already up to date.
21:31:42.502 [Init] === SwarmUI v0.9.3.2 Starting at 2024-11-28 21:31:42 ===
21:31:42.559 [Init] Prepping extension: ImgMetadataConverter.ImgMetadataConverter...
21:31:42.562 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
21:31:42.562 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
21:31:42.563 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
21:31:42.563 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
21:31:42.564 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
21:31:42.564 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
21:31:42.598 [Init] Parsing command line...
21:31:42.599 [Init] Loading settings file...
21:31:42.615 [Init] Re-saving settings file...
21:31:42.634 [Init] Applying command line settings...
21:31:42.661 [Init] Prepping options...
21:31:42.679 [Init] Current git commit marked as date 2024-11-28 09:32:40
21:31:42.761 [Init] [ImgMetadataConverter] loaded
21:31:42.788 [Init] CPU Cores: 16 | RAM: 15.87 GiB total, 9.35 GiB available, 47.95 GiB total page file, 31.50 GiB available page file
21:31:42.789 [Init] GPU 0: NVIDIA GeForce RTX 3060 | Temp 56C | Util 1% GPU, 1% Memory | VRAM 12.00 GiB total, 10.77 GiB free, 1.06 GiB used
21:31:42.801 [Init] Loading models list...
21:31:43.447 [Init] Loading backends...
21:31:43.448 [Init] Loading backends from file...
21:31:43.451 [Init] Prepping API...
21:31:43.452 [Init] Initializing backend #0 - ComfyUI Self-Starting...
21:31:43.453 [Init] Prepping webserver...
21:31:43.456 [Init] Backend request handler loop ready...
21:31:43.500 [Init] Swarm is up to date! You have version 0.9.3.2, and 0.9.3-Beta is the latest.
21:31:43.569 [Init] Scan for web extensions...
21:31:43.572 [Init] Readying extensions for launch...
21:31:43.573 [Init] Launching server...
21:31:43.574 [Init] Starting webserver on http://192.168.0.52:7801
21:31:43.610 [Init] Program is running.
21:31:44.122 [Init] Electron launch not yet implemented.
21:31:46.224 [Init] Self-Start ComfyUI-0 on port 7802 is loading...
21:31:54.175 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
21:31:54.176 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\egtxwhlj.py", line 8, in <module>
21:31:54.177 [Warning] [ComfyUI-0/STDERR]     import pilgram
21:31:54.178 [Warning] [ComfyUI-0/STDERR] ModuleNotFoundError: No module named 'pilgram'
21:31:54.178 [Warning] [ComfyUI-0/STDERR]
21:31:54.179 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
21:31:54.179 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 2027, in load_custom_node
21:31:54.180 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
21:31:54.180 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
21:31:54.181 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
21:31:54.182 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\__init__.py", line 38, in <module>
21:31:54.183 [Warning] [ComfyUI-0/STDERR]     from .nodes.egtxwhlj import EGWHLJ
21:31:54.183 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\egtxwhlj.py", line 10, in <module>
21:31:54.184 [Warning] [ComfyUI-0/STDERR]     subprocess.check_call(['pip', 'install', 'pilgram'])
21:31:54.184 [Warning] [ComfyUI-0/STDERR]   File "subprocess.py", line 413, in check_call
21:31:54.185 [Warning] [ComfyUI-0/STDERR] subprocess.CalledProcessError: Command '['pip', 'install', 'pilgram']' returned non-zero exit status 1.
21:31:54.186 [Warning] [ComfyUI-0/STDERR]
21:31:56.476 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
21:31:56.477 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 2027, in load_custom_node
21:31:56.478 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
21:31:56.478 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
21:31:56.479 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
21:31:56.479 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
21:31:56.480 [Warning] [ComfyUI-0/STDERR]     from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
21:31:56.480 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
21:31:56.481 [Warning] [ComfyUI-0/STDERR]     from .modules.magic_box import SeargeMagicBox
21:31:56.482 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 38, in <module>
21:31:56.483 [Warning] [ComfyUI-0/STDERR]     from .stage_latent_detailer import SeargeStageLatentDetailer
21:31:56.484 [Warning] [ComfyUI-0/STDERR]   File "X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_latent_detailer.py", line 29, in <module>
21:31:56.484 [Warning] [ComfyUI-0/STDERR]     from comfy.sample import prepare_mask
21:31:56.485 [Warning] [ComfyUI-0/STDERR] ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (X:\Stable Swarm\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py)
21:31:56.486 [Warning] [ComfyUI-0/STDERR]
21:31:59.695 [Init] Self-Start ComfyUI-0 on port 7802 started.

### Other

Not sure if there's even particularly support for custom nodes. I'm thinking there's a possibility of a conflict somewhere on my computer but it doesn't look that way.

**Comment by mcmonkey4eva** [comment]
`SeargeSDXL` node would be <https://github.com/SeargeDP/SeargeSDXL> which hasn't updated in over 7 months, and that error message looks like just comfy changed something that the custom nodes direct imported, breaking the node. That pack looks entirely unmaintained, but there might be a fork if you need em to work.

The other one I think is https://github.com/11dogzi/Comfyui-ergouzi-Nodes which is also barely maintained, and appears to be trying to violently pip install into a live process and bricking itself

(Also either way, issue is unrelated to Swarm)
