### ISSUE TITLE
flux1-dev-bnb-nf4-v2 doesn't work anymore

### ISSUE THREAD

**Issue by djdance** [mcmonkeyprojects/SwarmUI#445]
### Your question

I used to run **flux1-dev-bnb-nf4-v2** and it worked fine. I've just upgraded ComfyUI and SwarmUI. And now it can not work with flux nf4. The crash is

> ComfyUI execution error: All input tensors need to be on the same GPU, but found some tensors to not be on a GPU:
>  [(torch.Size([4718592, 1]), device(type='cpu')), (torch.Size([1, 3072]), device(type='cuda', index=0)), (torch.Size([1, 3072]), device(type='cuda', index=0)), (torch.Size([147456]), device(type='cpu')), (torch.Size([16]), device(type='cpu'))]

I tried ComfyUI alone (got the same crash), I tried all the SDXL & SD3 (they work fine). 
I googled, upgraded python, reinstalled all, it doesn't help.

Does anyone know what to do?

Thanks.

**Comment by mcmonkey4eva** [comment]
I very heavily recommend using GGUF models instead of NF4.

That error is ... something upstream, I don't really know. Either way just save the trouble and use GGUF.

**Comment by djdance** [comment]
@mcmonkey4eva 

I've tried **flux1-schnell-Q4_1** , set Flux1.Schnell arch, successfully auto downloaded missing things, restarted, but.. It crashes with _All available backends failed to load the model 'C:\SwarmUI\Models\diffusion_models/flux1-schnell-Q4_1.gguf'._

SwarmUI v0.9.3.2. Maybe I did something wrong?

In particular:


13:03:56.900 [Info] User local requested 1 image with model 'flux1-schnell-Q4_1.gguf'...
13:03:56.908 [Warning] Attempted re-download of pre-existing model 'Flux/ae.safetensors', skipping.
13:03:56.912 [Warning] Failed to load metadata for Flux/ae.safetensors:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.Stream.ReadAtLeastCore(Span`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream)
   at System.IO.Stream.ReadExactly(Byte[] buffer, Int32 offset, Int32 count)
   at SwarmUI.Text2Image.T2IModel.GetSafetensorsHeaderFrom(String modelPath) in C:\SwarmUI\src\Text2Image\T2IModel.cs:line 259
   at SwarmUI.Text2Image.T2IModelHandler.LoadMetadata(T2IModel model) in C:\SwarmUI\src\Text2Image\T2IModelHandler.cs:line 371
   at SwarmUI.Text2Image.T2IModelHandler.<>c__DisplayClass25_0.<AddAllFromFolder>b__1(String file) in C:\SwarmUI\src\Text2Image\T2IModelHandler.cs:line 620
13:03:58.920 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
13:03:58.921 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
13:03:58.922 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
13:03:58.922 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.923 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
13:03:58.924 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
13:03:58.925 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.925 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
13:03:58.926 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
13:03:58.927 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
13:03:58.928 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
13:03:58.930 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.930 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 755, in load_vae
13:03:58.931 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(vae_path)
13:03:58.932 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.932 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 34, in load_torch_file
13:03:58.933 [Warning] [ComfyUI-0/STDERR]     sd = safetensors.torch.load_file(ckpt, device=device.type)
13:03:58.934 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.934 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
13:03:58.935 [Warning] [ComfyUI-0/STDERR]     with safe_open(filename, framework="pt", device=device) as f:
13:03:58.936 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:03:58.936 [Warning] [ComfyUI-0/STDERR] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall
13:03:58.937 [Warning] [ComfyUI-0/STDERR]
13:03:59.029 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: Error while deserializing header: HeaderTooSmall
13:03:59.030 [Warning] [BackendHandler] backend #0 failed to load model flux1-schnell-Q4_1.gguf
13:03:59.901 [Warning] [BackendHandler] All backends failed to load the model 'C:\SwarmUI\Models\diffusion_models/flux1-schnell-Q4_1.gguf'! Cannot generate anything.

**Comment by djdance** [comment]
thank you very much, it works!
