### ISSUE TITLE
Text encoders failed to load

### ISSUE THREAD

**Issue by gallerix** [mcmonkeyprojects/SwarmUI#455]
### Expected Behavior

Models that do not contain text encoders should, in theory, load automatically ~OR~ give an accurate description of the problem in the logs.

### Actual Behavior

Error: **The text encoders (CLIP) failed to load. All backends failed to load the model** [main big model].

### Steps to Reproduce

Examples of models that require separate clips and vae:
- Copax Timeless - XPlus 3
- Dream Creation Light & Shadow Magician FLUX
- Flux Realistic SaMay v2

### Debug Logs

16:21:30.919 [Info] User local requested 1 image with model 'Flux/copaxTimeless_xplus3.safetensors'...
16:21:32.987 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
16:21:32.989 [Warning] [ComfyUI-0/STDERR]   File "D:\SWUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
16:21:32.990 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
16:21:32.992 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:21:32.994 [Warning] [ComfyUI-0/STDERR]   File "D:\SWUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
16:21:32.996 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
16:21:32.997 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:21:32.998 [Warning] [ComfyUI-0/STDERR]   File "D:\SWUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
16:21:33.000 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
16:21:33.001 [Warning] [ComfyUI-0/STDERR]   File "D:\SWUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
16:21:33.003 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
16:21:33.004 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:21:33.005 [Warning] [ComfyUI-0/STDERR]   File "D:\SWUI\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmInternalUtil.py", line 47, in just_load
16:21:33.007 [Warning] [ComfyUI-0/STDERR]     raise ValueError("The text encoders (CLIP) failed to load")
16:21:33.008 [Warning] [ComfyUI-0/STDERR] ValueError: The text encoders (CLIP) failed to load
16:21:33.009 [Warning] [ComfyUI-0/STDERR]
16:21:33.211 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: The text encoders (CLIP) failed to load

### Other

Why? Clip files is in folder (absolute path in server config) and selected in UI. Re-downloaded from HuggingFace, to exclude download errors.
Please add information to log output, describing the problem. Is this problem with files or problem with path?

**Comment by gallerix** [comment]
![ScreenShot_2-12-2024_18726_localhost](https://github.com/user-attachments/assets/a8aadc54-75c8-4c58-8d75-cbdeba2bc220)

**Comment by mcmonkey4eva** [comment]
if it's a DiT-only model, it needs to go in the `diffusion_models` folder rather than the usual stable diffusion folder

**Comment by gallerix** [comment]
Thanks!
