### ISSUE TITLE
CAN'T INSTALL ON LINUX

### ISSUE THREAD

**Issue by KintCark** [mcmonkeyprojects/SwarmUI#46]
I can't get this to install on linux I keep getting this error

mv: cannot stat './src/bin/live_release': No such file or directory
GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E
./launch-linux.sh: line 40: src/bin/last_build: No such file or directory
GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E

Please respond asap I want to install this today. This the 3rd time I've tried and I have more ram available

**Comment by mcmonkey4eva** [comment]
from your other issue https://github.com/Stability-AI/StableSwarmUI/issues/432

`I'm trying it on Termux android please help me`

From https://github.com/termux/proot/issues/283

you can possibly `export DOTNET_GCHeapHardLimit=1C0000000` to fix that

... but also I don't know what you expect to happen installing swarm on android? it's not... really gonna work like that, you need a PC with a GPU
