### ISSUE TITLE
Selected image from Civitai model downloader doesn't stick

### ISSUE THREAD

**Issue by Griphen116** [mcmonkeyprojects/SwarmUI#463]
### Expected Behavior

Use the selected image from Civitai as the card image for the model when downloaded.

### Actual Behavior

Not sure if this is a bug or intended behavior, but the fact that the model doenloader lets you scroll through the example photos from Civit before clicking "download" seems to imply that the one you had selected will be the one that shows up in the "Models" tab in the Generate section.

Right now it just goes with the first image from the Civit example photos when you do download it.

### Steps to Reproduce

Put a model link from Cicit in the model downloader.
Press the right or left arrow to select an example image besides the default one.
Click download.
Check the model in the Models tab under Generate.

### Debug Logs

Don't have any logs

**Comment by mcmonkey4eva** [comment]
fixed
