### ISSUE TITLE
RTX 4090 vs A 6000 - both at FP8 - Huge quality difference exactly same setup and config

### ISSUE THREAD

**Issue by FurkanGozukara** [mcmonkeyprojects/SwarmUI#464]
We know that RTX 4xxx series has special FP8 speed up and optimization

This is what I am suspecting of

Using same FP16 T5 XXL

Using same FLUX 1 fine-tuned model

Using same upscale settings and everything is same

First image on RTX A6000 machine here full config

![image](https://github.com/user-attachments/assets/10fab374-2e91-4c76-9d0f-b296279d0564)

Here the image below original output - it has metadata

https://huggingface.co/MonsterMMORPG/Generative-AI/blob/main/FP8_on_RTXA6000.png

Here second image on RTX 4090 machine (back-end is same not used --fast)

![image](https://github.com/user-attachments/assets/ddb83956-84d1-4fe8-96ea-acd18ed9fd19)

here the original image below - it has metadata

https://huggingface.co/MonsterMMORPG/Generative-AI/blob/main/FP8_on_RTX4090.png

Here imgsli comparison : https://imgsli.com/MzI0Mjgz

Zoom in to see what i mean please

When I set precision to FP16 - this problem goes away but we lose huge speed on RTX 4090

**Comment by mcmonkey4eva** [comment]
`--fast` is applied by default on RTX 40xx cards unless you uncheck server setting:
![image](https://github.com/user-attachments/assets/53482669-e2b4-4beb-bce6-06773723790b)

You can see this happening in logs with this message:
![image](https://github.com/user-attachments/assets/e59115db-af25-4ab2-8b3a-71ea971bcebe)

And of course in debug in the `[Load ComfyUI Self-Starting #0] Will add args:  ` debug message

**Comment by FurkanGozukara** [comment]
@mcmonkey4eva thank you so much

**Comment by FurkanGozukara** [comment]
@mcmonkey4eva thank you so much this fixed the issue
