### ISSUE TITLE
Headless install fails to launch

### ISSUE THREAD

**Issue by Someguitarist** [mcmonkeyprojects/SwarmUI#466]
### Expected Behavior

It launches

### Actual Behavior

It doesn't launch.  Everything looks fine until

12:51:43.213 [Init] Launch web browser to install page...
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening 'http://localhost:7801/Install'

Then it seems to stop

### Steps to Reproduce

Running Linux Headless, just type ./launch-linux.sh

### Debug Logs

Can't launch to get there.  Here's as much debug as I can give:

/SwarmUI$ sudo ./launch-linux.sh
12:51:42.194 [Init] === SwarmUI v0.9.4.0 Starting at 2024-12-06 12:51:42 ===
12:51:42.242 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
12:51:42.242 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
12:51:42.242 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
12:51:42.243 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
12:51:42.243 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
12:51:42.243 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
12:51:42.286 [Init] Parsing command line...
12:51:42.286 [Init] Loading settings file...
12:51:42.302 [Init] Re-saving settings file...
12:51:42.320 [Init] Applying command line settings...
12:51:42.361 [Init] Current git commit marked as date 2024-12-06 14:00:26
12:51:42.365 [Init] Prepping options...
12:51:42.385 [Init] CPU Cores: 16 | RAM: 94.24 GiB total, 75.33 GiB available, 4.00 GiB virtual, -96892248064 B swap
12:51:42.385 [Init] GPU 0: NVIDIA GeForce GTX 1660 Ti | Temp 43C | Util 1% GPU, 0% Memory | VRAM 6.00 GiB total, 5.13 GiB free, 678.00 MiB used
12:51:42.385 [Init] GPU 1: NVIDIA GeForce RTX 3090 | Temp 51C | Util 0% GPU, 0% Memory | VRAM 24.00 GiB total, 23.65 GiB free, 41.00 MiB used
12:51:42.508 [Init] Loading models list...
12:51:42.512 [Init] Loading backends...
12:51:42.513 [Init] Loading backends from file...
12:51:42.514 [Init] Prepping API...
12:51:42.517 [Init] Prepping webserver...
12:51:42.519 [Init] Backend request handler loop ready...
12:51:42.528 [Init] Swarm is up to date! You have version 0.9.4.0, and 0.9.4.0-Beta is the latest.
12:51:42.666 [Init] Scan for web extensions...
12:51:42.668 [Init] Readying extensions for launch...
12:51:42.668 [Init] Launching server...
12:51:42.668 [Init] Starting webserver on http://localhost:7801
12:51:42.713 [Init] Program is running.
12:51:43.213 [Init] Launch web browser to install page...
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening 'http://localhost:7801/Install'

**Comment by Someguitarist** [comment]
You replied on reddit!  Thanks!  For others searching:

Run the launch script with --host 0.0.0.0 --launch_mode none

**Comment by mcmonkey4eva** [comment]
yes. i added it to the readme too https://github.com/mcmonkeyprojects/SwarmUI?tab=readme-ov-file#alternate-manual-linux-install
