### ISSUE TITLE
question about the current solution for different people on the same pc

### ISSUE THREAD

**Issue by iraymondking** [mcmonkeyprojects/SwarmUI#468]
### Your question

if launch as a different user with --user_id for multiple people to use on the same pc with one gpu card ,when the different people run the different job,these job will be queued?

**Comment by mcmonkey4eva** [comment]
don't use that arg. i'm not really sure what the rest of your question is?

**Comment by iraymondking** [comment]
Before the new account system is released, I hope that swarmui can be used by multiple users at the same time

**Comment by mcmonkey4eva** [comment]
multiple people can use it at the same time yes, just not with separated account data trackers

**Comment by iraymondking** [comment]
When will the new account system be released?
