### ISSUE TITLE
Using SwarmUI with NPU?

### ISSUE THREAD

**Issue by pat-richter** [mcmonkeyprojects/SwarmUI#469]
### Your question

Hi, I have bought an OmnioBook Ultra with "Ryzen 9 AI 365", one of the new CPUs with NPU und iGPU. Thought I could generate images with this Laptop, but I got stuck.

Is it possible to run SwarmUI with this hardware?
Install only allows NVIDIA and (dedicated?) AMD GPU, so it downloaded the RocM versions for torch, but I think the CPU Versions are needed.

Thanks for your advice. Don't know what to do next

### Logs

01:58:41.643 [Info] User local requested 1 image with model 'sd3.5_medium.safetensors'...
01:58:46.680 [Warning] [ComfyUI-0/STDERR] !!! Exception during processing !!! HIP error: invalid device function
01:58:46.680 [Warning] [ComfyUI-0/STDERR] HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
01:58:46.683 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
01:58:46.683 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/execution.py", line 324, in execute
01:58:46.683 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
01:58:46.683 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.683 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/execution.py", line 199, in get_output_data
01:58:46.683 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
01:58:46.683 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.683 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/execution.py", line 170, in _map_node_over_list
01:58:46.683 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/execution.py", line 159, in process_inputs
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
01:58:46.684 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/nodes.py", line 67, in encode
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     return (clip.encode_from_tokens_scheduled(tokens), )
01:58:46.684 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 143, in encode_from_tokens_scheduled
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 205, in encode_from_tokens
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     o = self.cond_stage_model.encode_token_weights(tokens)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/text_encoders/sd3_clip.py", line 113, in encode_token_weights
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     lg_out, l_pooled = self.clip_l.encode_token_weights(token_weight_pairs_l)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/sd1_clip.py", line 41, in encode_token_weights
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     o = self.encode(to_encode)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]         ^^^^^^^^^^^^^^^^^^^^^^
01:58:46.684 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/sd1_clip.py", line 238, in encode
01:58:46.684 [Warning] [ComfyUI-0/STDERR]     return self(tokens)
01:58:46.684 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/sd1_clip.py", line 210, in forward
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     outputs = self.transformer(tokens, attention_mask_model, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/clip_model.py", line 137, in forward
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     x = self.text_model(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.685 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
01:58:46.685 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
01:58:46.685 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/clip_model.py", line 101, in forward
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     x = self.embeddings(input_tokens, dtype=dtype)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/clip_model.py", line 82, in forward
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return self.token_embedding(input_tokens, out_dtype=dtype) + comfy.ops.cast_to(self.position_embedding.weight, dtype=dtype, device=input_tokens.device)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
01:58:46.686 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.686 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
01:58:46.686 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
01:58:46.687 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.687 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/ops.py", line 203, in forward
01:58:46.687 [Warning] [ComfyUI-0/STDERR]     return self.forward_comfy_cast_weights(*args, **kwargs)
01:58:46.687 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.687 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/comfy/ops.py", line 199, in forward_comfy_cast_weights
01:58:46.687 [Warning] [ComfyUI-0/STDERR]     return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
01:58:46.687 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.687 [Warning] [ComfyUI-0/STDERR]   File "/var/home/patrick/Tools/ImageGeneration/interfaces/swarm-ui/SwarmUI/dlbackend/ComfyUI/venv/lib64/python3.11/site-packages/torch/nn/functional.py", line 2551, in embedding
01:58:46.687 [Warning] [ComfyUI-0/STDERR]     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
01:58:46.687 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:58:46.687 [Warning] [ComfyUI-0/STDERR] RuntimeError: HIP error: invalid device function
01:58:46.687 [Warning] [ComfyUI-0/STDERR] HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

**Comment by mcmonkey4eva** [comment]
I think it's technically possible to use a Ryzen APU, but ... not well. Even full amd gpus are a pain to deal with. Nvidia is the only hardware vendor that also invested heavily in software to get AI workable.

You'll want to search information specific to ComfyUI - comfy is the backend that actually powers the GPU-side stuff
