### ISSUE TITLE
Cannot load models (after autoupdate to 0.9.4.0?): `Return type mismatch between linked nodes: clip, CLIP != CLIP,GEMMA`

### ISSUE THREAD

**Issue by taurit** [mcmonkeyprojects/SwarmUI#471]
### Expected Behavior

I use SwarmUI to generate images using `Flux\flux1-dev-fp8.safetensors` model in a repeatable process (using HTTP API), and I haven't changed anything in my process in the last few days.

I expected it to continue working as usual, but since this morning, attempting to generate images has resulted in an error.

### Actual Behavior

Screenshot of the UI when attempting to re-use the parameters of image generated previously:

![obraz](https://github.com/user-attachments/assets/4a86ca1c-2246-4ca7-86b1-9c25e3a618b8)

### Steps to Reproduce

1) Run `launch-windows.bat`
2) Choose any model (none seems to work: flux1-dev-fp8, flux1-schnell-fp8, sd3.5_large_fp8_scaled)
3) Type some prompt
4) Click on "Generate"

### Debug Logs

https://paste.denizenscript.com/View/128941

The key fragment seems to be:

```log
ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "Return type mismatch between linked nodes: clip, CLIP != CLIP,GEMMA",
    "extra_info": {}
  },
```

### Other

I also upgraded NVIDIA drivers to the latest game-ready drivers (566.36) few hours ago, but image generation worked after that update until I re-run SwarmUI.

--- 
PS. Thanks for all the work put into this project! 😊

**Comment by mcmonkey4eva** [comment]
I believe the issue here is your Comfy backend is not properly updating

Go to Server->Backends->Click edit on the comfy backend->set updates to Forced->save

Then try again

**Comment by taurit** [comment]
Thanks for the hint! I made sure the ComfyUI backend is updated and tested on both its channels:

- Latest Swarm Validated: Comfy-Org/ComfyUI_frontend@**v1.3.44**
- Latest: Comfy-Org/ComfyUI_frontend@latest (**1.5.11**)

I still see the same error.
I'll try re-installing SwarmUI now and will let know here if that solves the issue.

**Comment by mcmonkey4eva** [comment]
Comfy *backend* is the relevant part. You're looking at the comfy frontend versions there

Your error message indicates you have a comfy backend that predates this commit https://github.com/comfyanonymous/ComfyUI/commit/4e402b11c6d692b833ee4dca6d329ec300ff0db1

**Comment by taurit** [comment]
Thanks for taking a look!

In the meantime, I re-installed SwarmUI and copied the models from the old installation; everything works now, so it looks like I had a problem with my specific configuration. It's probably not worth spending more time on this unless other people encounter the same problem.
