### ISSUE TITLE
init images grid internal error

### ISSUE THREAD

**Issue by oloboy** [mcmonkeyprojects/SwarmUI#476]
### Your question

Hi
I try to create a grid with different init images but I have un error message when I strat the generation INTERNAL ERROR
I have try to

Put the path of the imagines separatet by comma
The path of the folder
Do yo know the right way to use it?

**Comment by mcmonkey4eva** [comment]
if you want to just batch edit some images, use the Image Edit Batcher

If you need to use it specifically in a grid, yeah you gotta do some hacky stuff with custom comfy workflows and filenames. This is a known awkward limitation atm.
(Basically set up a custom comfy workflow on the Generate tab, with a `Load Image` node, and that takes a filename for inside the comfy `input` folder, so you can grid out filenames of that)
