### ISSUE TITLE
Civitai links not being updates when using "Scan Civitai for Metadata" and updating all

### ISSUE THREAD

**Issue by The-Istar** [mcmonkeyprojects/SwarmUI#478]
### Expected Behavior

That the civitai links in the description get properly updated including the correct/version ID

### Actual Behavior

After seeing this commit: [https://github.com/mcmonkeyprojects/SwarmUI/commit/f278a74d89e5a1f44daadaa43d1647be0180b668](https://github.com/mcmonkeyprojects/SwarmUI/commit/f278a74d89e5a1f44daadaa43d1647be0180b668) I decided to use the "Scan Civitai for Metadata" and selected update all. In order to update all the bad links in bulk.
However, after everything was finally done all the descriptions still had the links pointing to model number "null".
So I guess the update everything button does not update the links to the proper Model version.

### Steps to Reproduce

Have a model with model version "null" in the description and scan for metadata

### Debug Logs

[https://paste.denizenscript.com/View/129174](https://paste.denizenscript.com/View/129174)

**Comment by mcmonkey4eva** [comment]
added a check to autoreject version=null as a valid url

**Comment by The-Istar** [comment]
Thanks, what does that mean though? Will it now update the URL now it is considered invalid?

**Comment by The-Istar** [comment]
Never mind. A quick test shows that it does. Thanks!
