### ISSUE TITLE
how to hide the top level tab?

### ISSUE THREAD

**Issue by iraymondking** [mcmonkeyprojects/SwarmUI#479]
### Your question

I need to hide some top tabs, specifically the Server, User, and Utilities tabs. I'm not familiar with ASP.NET. I tried deleting the code in Text2Image.cshtml, but it didn't work.for example ,the code blew was deleted,but the Server tab is still exist:
<li class="nav-item" role="presentation" data-requiredpermission="view_server_tab">
        <a class="nav-link translate" data-bs-toggle="tab" href="#server_tab" id="servertabbutton" aria-selected="false" tabindex="-1" role="tab">Server</a>
    </li>

    <div class="tab-pane tab-pane-vw" id="server_tab" role="tabpanel">
        
    </div>

![1734678254478](https://github.com/user-attachments/assets/e421494b-9afd-4eac-93f4-11d10b589dd5)

**Comment by mcmonkey4eva** [comment]
If you want to give restricted access to some users where they cannot modify server settings or use power utilities, the Swarm multi-account system is coming soon and has permission togglers for the different tabs and the features within.

Modifying source code is not recommended.
