### ISSUE TITLE
Norton Antivirus flagged Install-windows.bat as IDP.ALEXA.54

### ISSUE THREAD

**Issue by Highandroid** [mcmonkeyprojects/SwarmUI#482]
### Your question

Norton Antivirus flagged Install-windows.bat as IDP.ALEXA.54. Is this common?
<img width="689" alt="Screenshot 2024-12-21 104747" src="https://github.com/user-attachments/assets/19e898f0-cb91-4aee-932f-c074f9ddcf44" />

**Comment by mcmonkey4eva** [comment]
I've never personally seen that one before, however a quick google search says it's a frequent false positive:

![image](https://github.com/user-attachments/assets/9e510b34-6d69-4cc2-8d80-6f9821d8ee15)

The install-windows.bat file is a text file. If you're worried about it, you can open it up in a text editor and verify it has the same contents as the reference in the repository https://github.com/mcmonkeyprojects/SwarmUI/blob/master/install-windows.bat
Which as you can see there is a very simple script that validates the install folder is proper, installs prereqs (git and dotnet), clones swarm and launches it
