### ISSUE TITLE
Deleting a video from Image History does not delete related files

### ISSUE THREAD

**Issue by rc-gr** [mcmonkeyprojects/SwarmUI#489]
### Expected Behavior

All related files of a video should be deleted when it gets deleted from Image History. For example, if VIDEO.mp4 gets deleted, VIDEO.swarm.json, VIDEO.swarmpreview.jpg and VIDEO.swarmpreview.webp should be deleted as well. This was the case with text metadata, where VIDEO.txt or IMAGE.txt would get the deleted when the main file was deleted.

### Actual Behavior

VIDEO.mp4 is selected from Image History, gets deleted with Delete from the context menu, but VIDEO.swarm.json, VIDEO.swarmpreview.jpg and VIDEO.swarmpreview.webp still remain in the same directory.

### Steps to Reproduce

Prerequisite: Have any working T2V or I2V model loaded. Following steps will assume that a T2V model is loaded.

1. Under Text To Video, select any video format (webm, h264-mp4, prores), or gif.
2. Generate.
3. Once generation is complete, refresh Image History.
4. Delete the generation in Image History.

### Debug Logs

https://paste.denizenscript.com/View/129301

### Other

Installed on Win11.

P.S. The bitsandbytes warning probably came from the fact that I installed it while running another ComfyUI backend (for SageAttention2), and did not do so on the backend used here. This would likely go away if I imported the workflow from Generate tab (if I used a NF4 model for example) and updated bitsandbytes via ComfyManager. Could be a potential autodetection enhancement, but it's most likely not relevant in this issue.

**Comment by rc-gr** [comment]
Alternative: Provide a user setting to specify whether the related files should be deleted or not when the main file gets deleted. Eg. DeleteRelatedFilesWithMainFile

**Comment by mcmonkey4eva** [comment]
Oh, yep, that was missed. Fixed
