### ISSUE TITLE
Editing model metadata removes .json file

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#49]
### Expected Behavior

When editing model metadata, the corresponding .json file should remain, updated with the new edits.

### Actual Behavior

After saving edited metadata, the corresponding .json file is deleted.

### Steps to Reproduce

Download a model. For the sake of speed, I chose a random one from Civit which is also pretty small at 54.76 MB, so it's quick: [Jade Beyond Good and Evil - v1.0](https://civitai.com/models/556785/jade-beyond-good-and-evil?modelVersionId=619731)

Open a file manager in the location it saved to. Observe that there is both a .safetensors file and a corresponding .json file.

In Models tab, click the menu hamburger and Edit Metadata. Change the name right at the top to something else and save it.

I changed it from the default:

`Jade Beyond Good and Evil - v1.0`

to:

`Jade Beyond Good and Evil v1.0`

In the file manager, notice that the .json file has now disappeared.

After stop/start of Swarm, the thumbnail stays. Someone mentioned [here](https://github.com/mcmonkeyprojects/SwarmUI/issues/26) about Swarm changing the metadata of models by writing data into them and that due to this the hash would no longer match to Civit. Presumably this is why the thumbnail and model info stays, because it's now inside the .safetensors file itself? Plus, this kind of makes the .json file itself redundant since it appear unnecessary.

Regardless, a .json file is created by Model Downloader and then unexpectedly deleted which is why I'm filing this as a bug.

### Debug Logs

```powershell
2024-07-04 20:58:46.577 [Debug] Added Civitai API Key to download request. Original URL: https://civitai.com/api/download/models/619731
2024-07-04 20:58:48.818 [Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
2024-07-04 20:58:48.902 [Debug] Model sdxlpony/Jade Beyond Good and Evil - v10.safetensors seems to match type Stable Diffusion XL 1.0-Base LoRA
2024-07-04 20:58:49.286 [Debug] Data refreshed!
2024-07-04 20:59:31.733 [Debug] Will reapply metadata for model /config/07-StableSwarm/StableSwarmUI/Models/Lora/sdxlpony/Jade Beyond Good and Evil - v10.safetensors
2024-07-04 20:59:32.145 [Debug] Completed metadata update for /config/07-StableSwarm/StableSwarmUI/Models/Lora/sdxlpony/Jade Beyond Good and Evil - v10.safetensors
```

### Other

Interestingly, I deleted and redownloaded that model just to test doing this again. When I went to edit the metadata, following the steps above, I found that the name was already listed as 'Jade Beyond Good and Evil v1.0' - without the dash. Does this mean the metadata is also stored somewhere else, maybe in 'model_metadata.ldb'? If a user goes to Utilities -> Info -> Reset All Metadata that data would be wiped out?

**Comment by mcmonkey4eva** [comment]
Not bug, intentional behavior. The JSON data isn't currently merged in during the model downloader, but is merged into file as soon as you edit the metadata.

The metadata is stored in the model itself
