### ISSUE TITLE
Using Runpod serveless as backend

### ISSUE THREAD

**Issue by brunovianna** [mcmonkeyprojects/SwarmUI#490]
### Your question

Runpod has this serverless endpoint for A1111, which I am trying to use as a backend for a SwarmUI installaion (in a PC with no GPU). I added a backend of type "Auto1111 SD-WebUI API by URL", using runpod's endpoint URL.

But the problem seems to be that the endpoint expects a json file like 

`{
  "input": {
    "prompt": "a cute cat"
  }
}`

And I understand that swarm makes the requests using A1111 API's format, since what I get is a 404 error. Has anyone tried this? Maybe there is a runpod serveless template  that accepts A1111 requests directly, or some other way to do this translation?

This is the runpod template I'm using: https://github.com/runpod-workers/worker-a1111
Which I found out here: https://www.runpod.io/console/serverless

The idea is not to depend on a single computer but to run it on a GPU cloud.

Thanks! 

### Logs

2024-12-24 10:13:01.762 [Error] Final error (4) while initializing backend #1 - Auto1111 SD-WebUI API By URL, giving up: Failed to read JSON '404 page not found' with message: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.

**Comment by mcmonkey4eva** [comment]
Auto1111 support in swarm barely works, and that API probably isn't a pure standard a1111 anyway.

They seem to allow custom workers? So perhaps you could set up a Swarm instance as a custom worker. Swarm using another Swarm as a remote backend works very well.

**Comment by brunovianna** [comment]
Great suggestions, thanks!
