### ISSUE TITLE
BuiltinExtensions git pull failed

### ISSUE THREAD

**Issue by iraymondking** [mcmonkeyprojects/SwarmUI#492]
### Your question

 ./launch-linux.sh --launch_mode none --host 0.0.0.0
after the SwarmUI run, BuiltinExtensions git pull failed.Can I skip the git pull process?

### Logs

 Starting webserver on http://0.0.0.0:7801
14:30:32.642 [Init] Program is running.
14:30:37.991 [Info] Creating new admin session 'local' for 127.0.0.1
14:31:27.292 [Warning] Git process 'fetch' in '/home/deepin/Documents/SwarmUI' has been running for over a minute, something may have gone wrong, allowing 1 more minute to finish...
14:31:27.475 [Warning] Git process 'pull' in '/home/deepin/Documents/ComfyUI' has been running for over a minute, something may have gone wrong, allowing 1 more minute to finish...
14:31:27.526 [Warning] Git process 'pull' in '/home/deepin/Documents/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI-SAI_API' has been running for over a minute, something may have gone wrong, allowing 1 more minute to finish...
14:31:32.100 [Init] Swarm is up to date! You have version 0.9.4.0, and 0.9.4.0-Beta is the latest.
14:31:35.251 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
14:32:50.299 [Error] Self-Start ComfyUI-0 on port 7821 failed to start: The operation was canceled.
14:34:00.550 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/urllib/request.py", line 1348, in do_open
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     h.request(req.get_method(), req.selector, req.data, headers,
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 1283, in request
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self._send_request(method, url, body, headers, encode_chunked)
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 1329, in _send_request
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self.endheaders(body, encode_chunked=encode_chunked)
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 1278, in endheaders
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self._send_output(message_body, encode_chunked=encode_chunked)
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 1038, in _send_output
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self.send(msg)
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 976, in send
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self.connect()
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 1448, in connect
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     super().connect()
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/http/client.py", line 942, in connect
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     self.sock = self._create_connection(
14:34:00.551 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/socket.py", line 845, in create_connection
14:34:00.551 [Warning] [ComfyUI-0/STDERR]     raise err
14:34:00.552 [Warning] [ComfyUI-0/STDERR]   File "/root/miniconda3/envs/swarmui/lib/python3.10/socket.py", line 833, in create_connection
14:34:00.552 [Warning] [ComfyUI-0/STDERR]     sock.connect(sa)
14:34:00.552 [Warning] [ComfyUI-0/STDERR] OSError: [Errno 101] Network is unreachable

**Comment by mcmonkey4eva** [comment]
I'm. very confused about that pile of logs.
But (A) the main problem seems to be network connections failed?
(B) when the comfy backend launches, you seem to have ... python requestlib self-activating and sending something? I'm not sure why the source of the call isn't in the trace at all. But whatever request is trying to happen, is failing and crashing the comfy instance. Normally comfy shouldn't be depending on any external network calls just to launch 0.o
