### ISSUE TITLE
Add option to add unique index to output file name in ImageBatch 

### ISSUE THREAD

**Issue by martinken** [mcmonkeyprojects/SwarmUI#494]
### Feature Idea

Use case, running image batch on a set of input images to extract/crop faces and save them as images. One input image can produce multiple output images, one per face.

Currently the ImageBatch extension will fire multiple times if needed for an input image, but writes to the output directory with the same filename (based on the input image) ala https://github.com/mcmonkeyprojects/SwarmUI/blob/bae492dc2c7b7ac88ee340252bbbb9114c75bb5e/src/BuiltinExtensions/ImageBatchTool/ImageBatchToolExtension.cs#L199 

Feature would be to add an option to append an index to that output filename (possibly the one already in the metadata object)

**Comment by mcmonkey4eva** [comment]
added

**Comment by martinken** [comment]
tested locally and it works for my use case, thanks!
