### ISSUE TITLE
Lightricks LTX Video generation not working

### ISSUE THREAD

**Issue by 3ddc-solaris** [mcmonkeyprojects/SwarmUI#499]
### Expected Behavior

Expected to work as described  here: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#lightricks-ltx-video

### Actual Behavior

The following error occurs in UI when trying to generate a video: ComfyUI execution error: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.

Console (seee pastebin for full stack trace):
2024-12-30 23:18:40.598 [Warning] [ComfyUI-0/STDERR] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
2024-12-30 23:18:40.600 [Warning] [ComfyUI-0/STDERR] Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory

**But, libnvrtc.so ist installed!
/home/alex/bin/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.12/site-packages/nvidia/cuda_nvrtc/lib/libnvrtc.so.12**

### Steps to Reproduce

1. Select "ltx-video-2b-v0.9.safetensors" as model
2. Enter Prompts
3. Click "Generate"

### Debug Logs

https://paste.denizenscript.com/View/129514

### Other

OS: Kubuntu 24.04
NVIDIA GeForce RTX 4080/PCIe/SSE2

**Comment by mcmonkey4eva** [comment]
uhhh do other models work on this install? This looks like torch is failing to talk to the nvidia drivers

**Comment by 3ddc-solaris** [comment]
> uhhh do other models work on this install? This looks like torch is failing to talk to the nvidia drivers

Jeah, all text2image models are working fine (Flux, SDXL, SD 1.5).

Video Generation with "svd_xt_1_1" does not work either, but that is a different error. I'll try to solve it myself first, but if I don't succeed, I'll create a separate ticket.

I can get Lightricks LTX video to run if I set LD_LIBRARY_PATH “the hard way”: export LD_LIBRARY_PATH=/home/alex/bin/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.12/site-packages/nvidia/cuda_nvrtc/lib && ./launch-linux.sh

But I don't think that can be the last word on the subject... :D

**Comment by mcmonkey4eva** [comment]
That miiight be a python3.12 specific bug? Or it might be some other specific factor of setup. You're the first person to report this that I've seen, so... iunno. I'd be extremely hesitant to bake a custom path like that into swarm's automated setup unless more users have the exact same issue fixed in the same way.

**Comment by 3ddc-solaris** [comment]
I can understand that. I will look into the error when I have more time. Or it may resolve itself with the next driver update from Nvidia or Torch (hope dies last :D ).

In any case, thank you very much for the quick reply and I wish you happy holidays and a happy new year!
