### ISSUE TITLE
Editing model metadata rewrites the whole file

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#50]
### Expected Behavior

When editing model metadata, the edit should save instantly with the minimum of disk writes.

### Actual Behavior

The whole file is duplicated as it's rewritten, resulting in heavy disk writes.

### Steps to Reproduce

While I was testing for [this](https://github.com/mcmonkeyprojects/SwarmUI/issues/49), I noticed another peculiarity:

While going through that process to edit metadata, the whole of the file is duplicated. It's not easy to spot with a small file - you need a checkpoint.

Again, open a file manager to observe the process. Pick a large checkpoint, refreshing the file manager directly after editing and saving the metadata. There will be an extra file:

`ModelName.safetensors.tmp`

When I watch my stats, I can see the disk activity clearly:

![rewriting-whole-file](https://github.com/mcmonkeyprojects/SwarmUI/assets/174625679/44691bb8-c8c7-427a-be08-c3bc45afda23)

This is a problem if the model is stored on an HDD as it will be slow, potentially bogging down the system. If the model is on an SSD, it will cause unnecessary writes, shortening the lifespan of the SSD.

So I wonder: Why not just write the metadata to the .json file and leave the .safetensors file alone to avoid this situation altogether?

### Debug Logs

```powershell
Not relevant
```

**Comment by mcmonkey4eva** [comment]
As said in previous issue: not bug, intentional behavior.

----

That said, I've pushed an update for if you really don't want correct metadata (eg on a slow old harddrive. Which, ow, that's gotta suck using AI at all on an old harddrive). https://github.com/mcmonkeyprojects/SwarmUI/commit/f18bf2095f8181cdc560405837425f90178112d7
Adds new Server Config setting to write JSON instead:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/6e634ffb-ea29-48b3-bbf6-63750b57c82d)

**Comment by mcmonkey4eva** [comment]
`Also, can the metadata not be streamed into just the blocks containing the metadata, rather than rewrite the whole entire file, even if it's just to change a single byte? Like a delta update.`
In theory yes, in practice it's a bit weird to do because the metadata is in the head (the start of the file) not the end (generally fs handlers are happy to modify the tail of a file, but modifying the head is a bit messier).

**Comment by crazeejeeves** [comment]
In general, metadata is always preferred to 'follow' the source data. Makes any data operations also apply to the metadata. Even better if the metadata uses an open standard to maximize this value.

In-place overwrite of metadata does sound tricky.. I don't know if a copy is avoidable if the metadata fields are tightly packed. Some file formats have a padded field... Providing extra 'blank' space that permit (easier?) in-place editing. depending on how freeform the metadata is, any padding limits will eventually be hit and force trigger a copy 

Not sure if specialized metadata editors do this in a more elegant, perfromant way.

**Comment by brendanhoar** [comment]
Right. Presumably HF decided to prefix the metadata (and the tensor layout, currently in the same JSON blob) to optimize for situations where the safetensors content was being streamed vs. accessed via a local filesystem that allows for seeking. 

I'm hopeful they would be open to reexamining that decision in future safetensors definitions.

I've seen that some safetensors-creation tools (but not all) insert some page-aligned amount of padding after the JSON, presumably to allow for metadata updates during the authoring process w/o a re-layout of the file. Unfortunately, there's not a requirement to do that.

B

**Comment by mcmonkey4eva** [comment]
`So this basically renders all I've typed above... redundant... ` yes this is why I didn't get into that myself, the entire conversation from there was doomed to go on for very long like above without any productive reason to

re the padding: yeah that's somewhere deep down my todolist, it's pretty easy to do padding, on the first rewrite add a big chunk of padding and then don't re-add until size exceeds the padding limit.

`Actually, what would happen with Swarm if you don't use a .swarm.json and you add too much to the metadata? Would it simply truncate or something else?` metadata length is *practically* unlimited. In the context of padding all going too long would mean is it needs to rewrite the full file with a larger padding.

(It's also possible to do OS block alignment hackery to prevent even the rewrites, but it's not worth the effort & risk to try)

**Comment by brendanhoar** [comment]
There is a hardcoded 100MB metadata(+tensor layout json) limit baked into the safetensors rust library for safety reasons (at least, that's the reason HF gives).  Above that length, the library will report an error. Without recompiling, it is not adjustable. Deep down, ComfyUI uses it, as part of the HF safetensors python bindings.

So, one would want to be cautious about adding metadata features such as embedded images, etc.

**Comment by mcmonkey4eva** [comment]
> metadata length is *practically* unlimited

Emphasis on 'practically'
You're never gonna hit it by editing your description text or anything else Swarm will let you do.
