### ISSUE TITLE
When using IPAdapter with the standard workflow, expose the start and end sliders in the UI

### ISSUE THREAD

**Issue by ngwnos** [mcmonkeyprojects/SwarmUI#56]
### Feature Idea

It would be nice to have the start and end sliders here:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/130041288/88362be0-0aad-4293-9a11-b504d88ee9ea)
Exposed in here:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/130041288/6c5299ea-ca8b-4d15-97a0-252142edc3d9)

Without using a custom comfy workflow.

**Comment by Sisimshow** [comment]
If I could add an appendix to it, provided it's possible without much hassle, to extend this to work for ReVision and Reference Only as well.

**Comment by mcmonkey4eva** [comment]
ReVision could maaaybe be done with the same hack that makes prompt time editing work. Reference only would just need a code update to support it in the python I think.

Either way, the PR added the main request here, and those two can be posted separately if you really want em
