### ISSUE TITLE
Update documentation in this repository

### ISSUE THREAD

**Issue by SirVeggie** [mcmonkeyprojects/SwarmUI#58]
Mainly move/copy documentation from the stable repository to this one, so there's no need to keep track of two different repositories.

Also, I noticed that the docs are pretty lacking in terms of making use of custom workflows. For example the hidden mechanism of naming primitive nodes as SwarmUI: Prompt.

**Comment by mcmonkey4eva** [comment]
`Mainly move/copy documentation from the stable repository to this one, so there's no need to keep track of two different repositories.` what documentation is there but not here?

**Comment by SirVeggie** [comment]
Oops, I was just looking for the wiki tab, which was missing here. Now I realized that the docs folder does indeed exist. I suppose you could add that wiki tab, but I'm more interested in the more thorough custom workflow documentation.

**Comment by mcmonkey4eva** [comment]
added a matching wiki page that just does a link

And yes more thorough documentation in general is needed
