### ISSUE TITLE
ReVision/IPAdapter images cannot be deleted individually

### ISSUE THREAD

**Issue by maedtb** [mcmonkeyprojects/SwarmUI#61]
### Feature Idea

Users currently have no way to individually remove a specific uploaded image if more than one has been uploaded into the image prompt area.  The current workaround for this is to click the `Clear images` button and re-add all but the image you want to delete, which is not a good user experience.

Instead, there should be `X` button at the top-right of each uploaded image in the prompt image area, that lets users to remove/delete that specific image.

This isn't very complicated, so I am happy to add this myself, but I am posting this here to get a general thumbs up/down approval on the concept before I add something the Swarm team doesn't want, or if there is an alternate idea for this functionality.  🙂

**Comment by mcmonkey4eva** [comment]
Yeah that'd be fine to add.

For reference the long term goal is I want all input images (image prompt, init image, controlnet, ...) to be in one universal interface and then you can freely add new ones at will and map out what they go to at will, eg mark one as the Init Image, and then also use it as ControlNet, and then also use it for whatever, then add a second image and use that for a second controlnet, etc.
