### ISSUE TITLE
Tag AutoCompleter: render tag count value and add option to control underscore vs spaces for anime tags

### ISSUE THREAD

**Issue by Jelosus2** [mcmonkeyprojects/SwarmUI#67]
I find the built-in tag autocompleter useful but it's missing some features.

Like the tag count and automatically removing the `_` from tags with spaces (although this kinda can be solved by removing them from the imported .csv file).

I would atleast want the latest feature to be implemented into it as I don't really care about the tag count.

**Comment by mcmonkey4eva** [comment]
`I would atleast want the latest feature to be implemented into` what

**Comment by Jelosus2** [comment]
> `I would atleast want the latest feature to be implemented into` what

Haha sorry, my English is not very good. I meant adding the ability so the tag autocompleter automatically removes the underscores of tags

**Comment by Jelosus2** [comment]
Thank you! How about the spaces replacing underscores?

**Comment by mcmonkey4eva** [comment]
new user setting 'Spacing Mode' in the autocomplete category to handle that part

![image](https://github.com/user-attachments/assets/46b3c36a-a382-4149-820c-790b21ffc155)
