### ISSUE TITLE
Zero values not re-applied correctly using Reuse Parameters

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#68]
### Expected Behavior

`Init Image Creativity` and `Refiner Control Percentage` are both set to 0.

### Actual Behavior

`Init Image Creativity` is set to 0.6 (default) and `Refiner Control Percentage` is set to 0.2 (...not the default, but not 0)

### Steps to Reproduce

1. Reset params to default (start clean).
2. Add a prompt and generate image.
3. `Use As Init` on the image that was just generated.
4. Change `Init Image Creativity` to 0.
5. Enable `Refine / Upscale` and change `Refiner Control Percentage` to 0.
6. Generate image.
7. `Reuse Parameters` on the just generated image.
8. See in the parameters on the left that neither of these are set to 0 (can confirm this by running generate image again and seeing that it is different from the previous and with different metadata).

### Debug Logs

```powershell
N/A
```

**Comment by mcmonkey4eva** [comment]
fixed
