### ISSUE TITLE
Image history only cycles through batch when last image is selected

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#69]
### Expected Behavior

Any image selected from the `Image History` tab always cycles through the entire history.

### Actual Behavior

When the last created image of the latest batch is selected from the `Image History` tab, it cycles through the batch instead of the entire history. This only seems to happen when the last created image from the batch is selected. If batch is > size 1, selecting any other image from the batch from `Image History` still cycles through the entire history.

This also means for batches of size 1, it cycles through nothing. This fixes itself if you first select another image from the Image History, and then re-select the last image.

### Steps to Reproduce

1. Create a batch of images and wait for them all to finish generating
2. Click the refresh button in the Image History tab

Either:
* Select the last created image and try use left/right arrow keys to switch between images and notice it only cycles through the batch, or
* Select any image from the batch that isn't the last one and try use left/right arrow keys to switch between images and notice it cycles through the entire history

### Debug Logs

```powershell
N/A
```

### Other

Wasn't sure whether this behaviour was intended/intentional, but given selecting any other image from the same batch in the image history doesn't trigger this, it seemed unlikely to me.

**Comment by mcmonkey4eva** [comment]
That is an impressively obscure edge case -- fixed

**Comment by Lawrr** [comment]
Thanks for the fix. Quite a common workflow for me actually. I prefer using the history over the batch view on the right. So I'd often generate -> refresh history -> subconsciously click the last image and run into this issue.
