### ISSUE TITLE
Yolo segmentation seems to only detect one face

### ISSUE THREAD

**Issue by Michoko92** [mcmonkeyprojects/SwarmUI#7]
Hi,

First, thank you for this awesome UI! I'm trying to generate an image, where all faces will be fixed, like in the ADetailer extension of A1111.

Here is my prompt:

```
oil painting of a male actor in a theatre full of people in the 1920s, black short hair with gomina, wearing a hamlet costume, fantasy art by greg olsen
<segment:yolo-face_yolov8m-seg_60.pt>
```

However, it just fixes the face of my main character, not all faces in the crowd. I tried to lower the detection threshold, but still, only one face seems to be detected (other faces are clearly identifiable though, and ADetailer in A1111 works as expected). 

```
oil painting of a male actor in a theatre full of people in the 1920s, black short hair with gomina, wearing a hamlet costume, fantasy art by greg olsen
<segment:yolo-face_yolov8m-seg_60.pt,0.6,0.2>
```

Do you have a suggestion to fix this, and have all faces detected, please? Thank you!

**Comment by FurkanGozukara** [comment]
I think we can have options like, top biggest 1, 2, 3 or like all detections

**Comment by Michoko92** [comment]
> I think we can have options like, top biggest 1, 2, 3 or like all detections

Normally, if you use "-1" at the end of the model name, it will pick the first face identified. -2 means the second, and so on. If we put nothing, like I did, it should fix all detected faces, if I'm not mistaken. However, I like you idea, like using "+x" instead on "-x" to pick the x first faces that were identified.

**Comment by mcmonkey4eva** [comment]
You can test mask results with Advanced -> Regional Prompting -> Save Segment Mask
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/20b2a501-2d1b-4ddb-ba38-a45346d399db)

I tested that with prompt `a photo of two women smiling <segment:yolo-face_yolov8m-seg_60.pt> beautiful smiling faces`
and it very definitely masked both faces:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/7394e021-97ac-4be8-bcac-b3b4a367a1e7)


With your prompt, it skipped some of the background faces but got a bunch:
![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/ba5692d0-9256-4c1c-b3d5-6175f9e78952)

**Comment by Michoko92** [comment]
Hi,

Thank you for your reply and explanations. Saving the mask allowed me to play with this feature, and in some cases, I indeed have a few more faces detected. But nothing similar to ADetailer, which detects many more faces. In SwarmUI, only the most obvious faces, looking at the camera, are detected. Even if I try to lower the detection threshold to the maximum, it detects many fewer faces than ADetailer (only 3 or 4, while ADetailer detects dozens). Do you know if there is a way to make the Yolo model more sensitive? (as it is mainly useful for fixing smaller faces that are generally more deformed and less detailed). Thank you!

**Comment by mcmonkey4eva** [comment]
The only reason it'd be different in adetailer vs swarm when using the exact same yolo model, is if the threshold minimum of `0.01` is somehow too high (unlikely?).
More likely reason is just maybe your adetailer is using a different yolo model that you need to copy over

**Comment by FurkanGozukara** [comment]
Can we inpaint only largest detected face?

<segment:yolo-face_yolov9c.pt-2,0.6,0.5>

how to modify this?

**Comment by mcmonkey4eva** [comment]
Open a separate feature request for that

**Comment by FurkanGozukara** [comment]
> Open a separate feature request for that

can you tell me which file i need to look edit i will try to make a pull request

my aim is `segment:yolo-face_yolov9c.pt-largest,0.6,0.5`
