### ISSUE TITLE
Swarm webrouting - relative paths or path prefix

### ISSUE THREAD

**Issue by StefanoBalocco** [mcmonkeyprojects/SwarmUI#72]
I'm trying to run swarmui behind nginx in a specific path.
When I open http://vhost.lan/swarmui/, it redirect to http://vhost.lan/Text2Image instead of http://vhost.lan/swarmui/Text2Image

I didn't found any setting to specify a prefix path and/or any setting to force swarmui to use relative paths.

There is a way?

**Comment by mcmonkey4eva** [comment]
as I'm not currently at home I don't have easy access to muck about with webservers to test against, but the above commit should make all or at least most paths relative, and thus work as intended. If anything doesn't work please let me know
