### ISSUE TITLE
Changing Custom Workflow parameters in the Generate tab prevents updating with a new Workflow

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#75]
### Expected Behavior

I'd like to change a Comfy Workflow and be able to send it to the Generate tab as-is when there are sliders already enabled there. I would expect that this action would override the values in the Generate tab, or else I wouldn't have clicked that button.

### Actual Behavior

The parameters in the Generate tab stay put and don't update.

### Steps to Reproduce

After testing with [this](https://github.com/mcmonkeyprojects/SwarmUI/issues/74), I've found that if you enable the sliders, you cannot then go into the Comfy Workflow tab, change some things, then click 'Use This Workflow In Generate Tab' and have those new parameters appear in the Generate tab.

If you disable the sliders, then click 'Use This Workflow In Generate Tab', the changed values in the Workflow still don't update.

If you click at the bottom left to Disable the Workflow, then click in the Comfy Workflow tab to 'Use This Workflow In Generate Tab', it re-enables the sliders with the old values.

If in the Comfy Workflow tab, you click 'Remove Workflow From Generate Tab', then click 'Use This Workflow In Generate Tab', the values also still do not update.

How is this supposed to work? How do I get my Comfy Workflow into the Generate tab and overwrite the old values?

### Debug Logs

```powershell
Not relevant.
```

**Comment by mcmonkey4eva** [comment]
Uncheck a parameter and it will automatically use whatever value is in the workflow. Checking a parameter is to intentionally override the workflow.

**Comment by mcmonkey4eva** [comment]
`the parameters remain unchecked and neither update, nor re-enable.`
... Yes? Why would Use Workflow forcibly enable an override?
Disabled == not overridden == uses whatever's in the workflow

**Comment by mcmonkey4eva** [comment]
The above new commit makes it so that if:
- The parameter was edited, then unchecked
- You reuse a workflow
the value itself will display the new value visually, and you'll start from that if you enable it

And of course, if toggler checked, it will still persist the custom value

hopefully that makes it less confusing
