### ISSUE TITLE
Upscale without refine?

### ISSUE THREAD

**Issue by richardtallent** [mcmonkeyprojects/SwarmUI#76]
### Your question

Hi! In A1111, my normal approach was to not use refiner steps, but to just to a 2x Lanczos directly on the output from the model before saving.

However, in StableSwarmUI, there doesn't seem to be a way to skip the refining part and just upscale:

- Trying to choose "---" as the refiner model leads to an error
- Setting Refiner Control Percentage to 0 leads to no upscaling
- Using the "2x" button in the More menu for the preview image also runs the refiner
- Playing with Refiner Method had no effect.

Am I missing a nuance in the UI?

### Other

I tried posting on Discord first. Maybe this is a bug, but I'm assuming for now it's either a Feature Request or a dumb user problem. Also searched there, saw some similar questions but no replies.

**Comment by mcmonkey4eva** [comment]
`Setting Refiner Control Percentage to 0 leads to no upscaling` this was the correct method, and it is indeed bugged -- fixed!
