### ISSUE TITLE
Customizable CLIP folder path

### ISSUE THREAD

**Issue by japppie** [mcmonkeyprojects/SwarmUI#79]
### Expected Behavior

When setting a custom path in 'Server configuration', there should be a 'Clip' path but there is not.

### Actual Behavior

After setting a custom path, TripleClipLoader node still looks to:
SwarmUI\dlbackend\comfy\ComfyUI\models\clip

### Steps to Reproduce

Change ModelRoot path
Add TripleClipLoader in ComfyUI
Try to select a clip model from ModelRoot path/Clip
 - only models from 'SwarmUI\dlbackend\comfy\ComfyUI\models\clip' will be found

<img width="620" alt="image" src="https://github.com/user-attachments/assets/a94fbdda-821b-4511-b2ef-4e732d038642">

### Debug Logs

```powershell
None
```

**Comment by mcmonkey4eva** [comment]
CLIP models will be loaded from `(ModelRoot)/clip`
So, in your case, `C:\Users\Jasper\Documents\AI models\clip`

A feature request to customize this path is valid enough, although I'm not sure why you'd need to?

**Comment by japppie** [comment]
You're correct, somehow my clip folder defaulted to the SwarmUI folder untill I restarted SwarmUI.
Now it defaults to my (ModelRoot)/clip folder which would be expected behavior
