### ISSUE TITLE
CivitAI downloader - Handling filenames with slash symbol on Windows.

### ISSUE THREAD

**Issue by Kanareika** [mcmonkeyprojects/SwarmUI#8]
I tried to download this Lora (warning: NSFW images): https://civitai.com/models/287657/oroborus-savagexthicc-style-lora
Got an error: "Error: Failed to download the model due to internal exception. "
In the console window, there is exception: 
```
Failed to download the model due to internal exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\sd_models\Lora\Oroborus\Savagexthicc - Style LoRA - Oroborus PonyXL.download.tmp'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
```

So, basicaly, instead of full filename, Windows interpreted it like a local path.

**Comment by mcmonkey4eva** [comment]
Pushed fix to autocreate directories as-needed based on your save name

![image](https://github.com/mcmonkeyprojects/SwarmUI/assets/4000772/17cc3bdc-473b-4df3-9caf-11a695f2b97d)
Note that ^ the default save name for this model has a `/` in it, so it will go into a folder named `Oroborus` - if you don't want this, just remove the `/` from the save name before you click download
