### ISSUE TITLE
Right clicking registers as left click - Linux

### ISSUE THREAD

**Issue by truethug** [mcmonkeyprojects/SwarmUI#80]
### Expected Behavior

I'm using Linux Xubuntu 22.04. This happens in both firefox and chrome. 
This only happens in the large image preview (on the generate tab if you click the main generated image so it's full screen).
right click brings up context menu (save as etc). 

### Actual Behavior

The right click context menu is brought up but a left click is also registered so moving the mouse moves the image like it was grabbed. 

### Steps to Reproduce

generate an image
click on the thumbnail to see full screen
right click to save
move the mouse

### Debug Logs

```powershell
there is nothing related in the logs.
```

**Comment by mcmonkey4eva** [comment]
I don't know that I'd even call that a bug, it's just, a thing? It's fine. But either way I've blocked right click counting for panning anyway.

**Comment by truethug** [comment]
is there a dev branch? right click panning is what I'm seeing. 
I have not read the code
the right click gets the down button , right click menu comes up (save as. etc) after saving the button released, 
the behavior is the button is still clicked

**Comment by mcmonkey4eva** [comment]
just go to Server tab -> click Update and Restart at the bottom (make sure you're running SwarmUI, not the legacy Stability version, per the migration notice that was linked in your previous issue)

**Comment by truethug** [comment]
Thank you this bug can be closed :)
