### ISSUE TITLE
Mask Inversion

### ISSUE THREAD

**Issue by davidgoering** [mcmonkeyprojects/SwarmUI#9]
It would be great if it were possible to quickly and easily invert a mask in img2img.
Either in the image editor to be able to right click and invert the mask, or on prompt level which causes an inversion node to be added.

**Comment by mcmonkey4eva** [comment]
Note OP was originally also asking about `<segment:` for the same request

**Comment by mcmonkey4eva** [comment]
For the first part, within the Image Editor, there's now an `Invert` button when you right-click a layer

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/user-attachments/assets/012201cb-30ed-4d59-adbb-669c9f340c1d)

You can now do negative thresholds to invert segment masks
