### ISSUE TITLE
[ Feature Request ] Tac Completer

### ISSUE THREAD

**Issue by ThesiiNCey** [mcmonkeyprojects/SwarmUI#90]
### Feature Idea

Would it be possible to implement a tag autocomplete like this?

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

**Comment by mcmonkey4eva** [comment]
Swarm native supports autocompletions since months ago, see docs here https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Autocompletions.md

**Comment by ThesiiNCey** [comment]
i dont mean for loras or something i mean for prompts like ( sitting, 2d, flying, falling )

**Comment by Jelosus2** [comment]
> i dont mean for loras or something i mean for prompts like ( sitting, 2d, flying, falling )

Can't you read the docs? It also includes a section for prompt autocompletion. And the settings for it are in User -> User Settings
