### ISSUE TITLE
[FEATURE REQUEST] Add a "prompt weight" option in the ReVision parameters

### ISSUE THREAD

**Issue by Michoko92** [mcmonkeyprojects/SwarmUI#93]
### Feature Idea

When we use IP-Adapter in the ReVision parameters, we can set the IP-Adapter Weight, Start and Stop values, but we can't set the prompt weight type. It would be nice to have a menu allowing to choose either "Standard", "Prompt is more important" and "Style transfer". Right now, if we want to use the "Style transfer" feature of IP-Adapter, we have to go to the Comfy Workflow tab.

Thank you for this amazing UI!

**Comment by mcmonkey4eva** [comment]
Added `IP-Adapter Weight Type` (Advanced param)
