### ISSUE TITLE
Some element will be removed when applying translation, and causing wrong behavior.

### ISSUE THREAD

**Issue by cy745** [mcmonkeyprojects/SwarmUI#94]
### Expected Behavior

I try to save a workflow by click the button at floating panel in the Comfy Workflow TAB, and it should show the dialog to save workflow. 

### Actual Behavior

But nothing appeared, except an error message in browsers console.
<img width="875" alt="截屏2024-07-28 02 25 32" src="https://github.com/user-attachments/assets/df746bba-69ae-4ac3-9eca-7c8fbf3b20fc">

### Steps to Reproduce

Switch to a translation, and save a workflow in the Comfy Workflow TAB

(I use Chinese, but i suspect that this issue also occurs in other languages)

### Debug Logs

```powershell
No related logs.
```

### Other

Before apply translation, there is an input element with ID="comfy_save_use_image" 
<img width="919" alt="截屏2024-07-28 02 20 24" src="https://github.com/user-attachments/assets/9bfe0756-a041-4d95-b746-24eadd67f36c">

When applying translation, the content in \<span\> is totally replaced to the translation text, which is a wrong behaviour.
<img width="945" alt="截屏2024-07-28 02 24 10" src="https://github.com/user-attachments/assets/d9f68dec-ff76-4542-8ac0-58809057b524">

**Comment by mcmonkey4eva** [comment]
fixed
