### ISSUE TITLE
Allow renaming/replacing of Custom Workflows while keeping image intact

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#96]
### Feature Idea

Due to the [other problem](https://github.com/mcmonkeyprojects/SwarmUI/issues/95) I found with the Comfy Swarm widget thingy, I found that I might like to rename some of these Custom Workflows. Some of them I gave decent names to while others were just named v1, v2, or some variation of - not really descriptive at all. However, I've since brainstormed with myself to think of really good names for them that are even betterer.

But... I only have the options for 'Replace' and 'Delete'. Replacing is close enough, though it does duplicate the saved workflow. As in: Click 'Replace', choose a new name, then it saves a copy with the new name, leaving the original intact.

So it works more like a 'Clone' button than a 'Replace' button for my purposes. Which is... Fine...?

The problem I have is that while figuring out these workflows, generating a few images and finding the workflows do what I want, then going to save them - I choose an image I've generated that perfectly shows what I've designed each workflow to do. When I do the above, I lose the image which describes it perfectly.

So I have to go to Image History in the Swarm Generate tab, then go hunting for it (assuming I remember the date or some keyword I can search for), click the image, then click on the Comfy tab, then open the widget, then click 'Replace', name it and then save it. When I generate thousands of images, finding that single perfect one again is nigh-on impossible. Especially when many generations all look similar but only one looks exactly how I'd like it to be described in one image.

When you do this same operation by clicking 'Replace', it keeps the original name and description text but not the image.

My feature request is for 'Replace' to keep the same image as it does with the text inputs.

Potentially, though: Rename 'Replace' into 'Clone' and add a separate 'Rename' option?

Thanks.

**Comment by mcmonkey4eva** [comment]
Fixed both issues (the losing images, and renaming not working)
