### ISSUE TITLE
Allow folder selection when downloading a model

### ISSUE THREAD

**Issue by richardtallent** [mcmonkeyprojects/SwarmUI#99]
### Feature Idea

I like to keep my models organized into folders within the main LORA, etc. folder.

I also like the new UI for downloading models, since it pulls important metadata too. But the current UI doesn't allow me to choose a folder within the main folder.

**Comment by richardtallent** [comment]
Great tip! I'll have to remember / type the name, but that's at least a good workaround

**Comment by mcmonkey4eva** [comment]
Should add at least tab completion for existing folders or something to make it easy, if not a dedicated folder dropdown

**Comment by mcmonkey4eva** [comment]
Oh- this was added a month or two ago.
